<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Michael Woller">

<title>Type I Error Correction: Multiple Comparison Procedures – InfoGothic</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-f418161beb48e0141c760e455f12af2c.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-4d14f3be7bc8eb7ec2287338953877e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
document.addEventListener("DOMContentLoaded", function() {
  var nav = document.querySelector(".navbar-nav");
  var li = document.createElement("li");
  li.className = "nav-item";
  li.innerHTML = '<a class="nav-link ml-onclick-form" href="javascript:void(0)" onclick="ml(\'show\', \'18mxag\', true)">Mail List</a>';
  var icons = nav.querySelector(".nav-item:has(.bi)");
  nav.insertBefore(li, icons);
});
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">InfoGothic</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../tutorials.html"> 
<span class="menu-text">Courses &amp; Tutorials</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog-posts.html"> 
<span class="menu-text">Blog Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://notes.infogothic.com"> 
<span class="menu-text">Obsidian Notes</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/michaelwoller"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://bsky.app/profile/infogothic.bsky.social"> <i class="bi bi-bluesky" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#the-multiple-comparisons-problem" id="toc-the-multiple-comparisons-problem" class="nav-link" data-scroll-target="#the-multiple-comparisons-problem">1. The Multiple Comparisons Problem</a>
  <ul class="collapse">
  <li><a href="#why-running-many-tests-is-dangerous" id="toc-why-running-many-tests-is-dangerous" class="nav-link" data-scroll-target="#why-running-many-tests-is-dangerous">Why Running Many Tests Is Dangerous</a></li>
  <li><a href="#planned-vs.-post-hoc-comparisons" id="toc-planned-vs.-post-hoc-comparisons" class="nav-link" data-scroll-target="#planned-vs.-post-hoc-comparisons">Planned vs.&nbsp;Post Hoc Comparisons</a></li>
  </ul></li>
  <li><a href="#which-correction-to-use" id="toc-which-correction-to-use" class="nav-link" data-scroll-target="#which-correction-to-use">2. Which Correction to Use?</a></li>
  <li><a href="#bonferroni-correction" id="toc-bonferroni-correction" class="nav-link" data-scroll-target="#bonferroni-correction">3. Bonferroni Correction</a>
  <ul class="collapse">
  <li><a href="#the-logic" id="toc-the-logic" class="nav-link" data-scroll-target="#the-logic">The Logic</a></li>
  <li><a href="#setting-c" id="toc-setting-c" class="nav-link" data-scroll-target="#setting-c">Setting C</a></li>
  <li><a href="#the-test-statistic-and-critical-value" id="toc-the-test-statistic-and-critical-value" class="nav-link" data-scroll-target="#the-test-statistic-and-critical-value">The Test Statistic and Critical Value</a></li>
  <li><a href="#advantage-and-limitation" id="toc-advantage-and-limitation" class="nav-link" data-scroll-target="#advantage-and-limitation">Advantage and Limitation</a></li>
  </ul></li>
  <li><a href="#tukeys-hsd" id="toc-tukeys-hsd" class="nav-link" data-scroll-target="#tukeys-hsd">4. Tukey’s HSD</a>
  <ul class="collapse">
  <li><a href="#the-logic-1" id="toc-the-logic-1" class="nav-link" data-scroll-target="#the-logic-1">The Logic</a></li>
  <li><a href="#test-equations" id="toc-test-equations" class="nav-link" data-scroll-target="#test-equations">Test Equations</a></li>
  <li><a href="#tukey-vs.-bonferroni-for-pairwise-comparisons" id="toc-tukey-vs.-bonferroni-for-pairwise-comparisons" class="nav-link" data-scroll-target="#tukey-vs.-bonferroni-for-pairwise-comparisons">Tukey vs.&nbsp;Bonferroni for Pairwise Comparisons</a></li>
  <li><a href="#an-important-limitation" id="toc-an-important-limitation" class="nav-link" data-scroll-target="#an-important-limitation">An Important Limitation</a></li>
  </ul></li>
  <li><a href="#scheffés-method" id="toc-scheffés-method" class="nav-link" data-scroll-target="#scheffés-method">5. Scheffé’s Method</a>
  <ul class="collapse">
  <li><a href="#the-logic-2" id="toc-the-logic-2" class="nav-link" data-scroll-target="#the-logic-2">The Logic</a></li>
  <li><a href="#test-equations-1" id="toc-test-equations-1" class="nav-link" data-scroll-target="#test-equations-1">Test Equations</a></li>
  <li><a href="#the-omnibus-connection" id="toc-the-omnibus-connection" class="nav-link" data-scroll-target="#the-omnibus-connection">The Omnibus Connection</a></li>
  <li><a href="#scheffé-vs.-bonferroni-when-to-use-which" id="toc-scheffé-vs.-bonferroni-when-to-use-which" class="nav-link" data-scroll-target="#scheffé-vs.-bonferroni-when-to-use-which">Scheffé vs.&nbsp;Bonferroni: When to Use Which</a></li>
  </ul></li>
  <li><a href="#implementing-mcps-in-spss" id="toc-implementing-mcps-in-spss" class="nav-link" data-scroll-target="#implementing-mcps-in-spss">6. Implementing MCPs in SPSS</a>
  <ul class="collapse">
  <li><a href="#pairwise-comparisons-with-oneway" id="toc-pairwise-comparisons-with-oneway" class="nav-link" data-scroll-target="#pairwise-comparisons-with-oneway">Pairwise Comparisons with ONEWAY</a></li>
  <li><a href="#bonferroni-with-manova" id="toc-bonferroni-with-manova" class="nav-link" data-scroll-target="#bonferroni-with-manova">Bonferroni with MANOVA</a></li>
  <li><a href="#scheffé-with-manova" id="toc-scheffé-with-manova" class="nav-link" data-scroll-target="#scheffé-with-manova">Scheffé with MANOVA</a></li>
  </ul></li>
  <li><a href="#summary-choosing-your-mcp" id="toc-summary-choosing-your-mcp" class="nav-link" data-scroll-target="#summary-choosing-your-mcp">7. Summary: Choosing Your MCP</a></li>
  <li><a href="#discussion-questions" id="toc-discussion-questions" class="nav-link" data-scroll-target="#discussion-questions">Discussion Questions</a></li>
  <li><a href="#well-done" id="toc-well-done" class="nav-link" data-scroll-target="#well-done">Well Done!</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Type I Error Correction: Multiple Comparison Procedures</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Michael Woller </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 data-anchor-id="introduction">Introduction</h2>
<p>In the previous lesson, we covered how to formulate and test contrasts after a significant omnibus ANOVA. But we left something important unaddressed: what happens when you run many of those tests? Initially, this might not be seen as a concern, however this is a <em>very</em> important aspect of psychological research. Each test you run has a chance of producing a false positive, and the more tests you run, the more that risk compounds. If you carelessly start running a bunch of tests, you will eventually get a Type I error. This fact is inevitable and enescapable.</p>
<p>Think about it this way, imagine standing in front of a mirror and inspecting yourself for flaws. Even if you are a perfectly healthy and beautiful human being, the longer and more carefully you look, the more likely you are to notice something like a blemish, an asymmetry, or a hair out of place. None of these might mean anything, but the sheer act of repeated searching guarantees you will eventually land on something that looks wrong, and this will cause your self esteem to plummet, even if the “flaw” was never a big deal! The more you are looking for personal flaws, the more you are going to find one regardless of how insignificant they are.</p>
<p>Type I error inflation works the same way. Each additional significance test is another pass in the mirror, and the more passes you take, the more likely you are to flag something as a “real” finding purely by chance.</p>
<p>This lesson is about how to keep that risk of finding false results under control.</p>
<p>We will continue with the hypertension dataset from the previous lesson: four treatment groups (drug therapy, biofeedback, dietary modification, and a combination treatment), with blood pressure as the dependent variable. The combination treatment group had the lowest mean (<span class="math inline">\(\bar{X} = 83\)</span>), while the other three groups had means of 91.4, 93, and 92 respectively.</p>
<hr>
</section>
<section id="the-multiple-comparisons-problem" class="level2">
<h2 data-anchor-id="the-multiple-comparisons-problem">1. The Multiple Comparisons Problem</h2>
<section id="why-running-many-tests-is-dangerous" class="level3">
<h3 data-anchor-id="why-running-many-tests-is-dangerous">Why Running Many Tests Is Dangerous</h3>
<p>When you reject the null hypothesis at <span class="math inline">\(\alpha = .05\)</span>, you are accepting a 5% chance that you are wrong — that the effect you found is a false positive, also called a <strong>Type I error</strong>. That 5% risk is manageable for a single test.</p>
<p>The problem arises when you run many tests at once. Each individual test has its own 5% chance of a false positive, and these chances accumulate. With enough tests, it becomes nearly inevitable that at least one of your results will be a false positive, even if nothing is truly significant.</p>
<p>We distinguish two kinds of error rates:</p>
<ul>
<li><strong>Per-comparison error rate</strong> (<span class="math inline">\(\alpha_{PC}\)</span>): the false positive rate for a single test, the one you set directly (e.g., .05).</li>
<li><strong>Experimentwise error rate</strong> (<span class="math inline">\(\alpha_{EW}\)</span>): the probability of making <em>at least one</em> Type I error across the entire set of tests you are running.</li>
</ul>
<p>For a set of orthogonal contrasts, the experimentwise error rate is:</p>
<p><span class="math display">\[\alpha_{EW} = 1 - (1 - \alpha_{PC})^C\]</span></p>
<p>where <span class="math inline">\(C\)</span> is the number of comparisons being made. With just 3 comparisons at <span class="math inline">\(\alpha = .05\)</span>:</p>
<p><span class="math display">\[\alpha_{EW} = 1 - (1 - .05)^3 = 1 - (.95)^3 \approx .143\]</span></p>
<p>So your real Type I error rate is already 14%, not 5%. With 10 comparisons it climbs to about 40%. You are no longer doing science at <span class="math inline">\(\alpha = .05\)</span> — you are just conducting a lottery.</p>
</section>
<section id="planned-vs.-post-hoc-comparisons" class="level3">
<h3 data-anchor-id="planned-vs.-post-hoc-comparisons">Planned vs.&nbsp;Post Hoc Comparisons</h3>
<p>An important distinction for choosing how to control Type I error is whether your comparisons were <strong>planned</strong> or <strong>post hoc</strong>.</p>
<p>A <strong>planned contrast</strong> is one you decided to test <em>before</em> looking at the data, based on your theoretical hypotheses. You committed to it in advance.</p>
<p>A <strong>post hoc contrast</strong> is one you decided to test <em>after</em> examining the data — for example, after noticing that two particular group means look far apart.</p>
<p>This distinction matters more than it might seem. Suppose you run a four-group study and after seeing the results you decide to test the largest-looking mean difference. It feels like you are only running one test. But in reality, you implicitly scanned all possible pairwise differences before choosing that one. The comparison that “caught your eye” is almost by definition the most extreme one in the data, which means it is also the one most likely to be a false positive. You did not really run one test — you ran all of them mentally and selected the winner.</p>
<p>This means that the number of comparisons you must account for is not just the ones you formally tested, but the entire family of comparisons that your selection process implicitly considered.</p>
<hr>
</section>
</section>
<section id="which-correction-to-use" class="level2">
<h2 data-anchor-id="which-correction-to-use">2. Which Correction to Use?</h2>
<p>There is no single universal correction for Type I error inflation. The right choice depends on two things: (1) whether your comparisons were planned or post hoc, and (2) whether your comparisons are pairwise only, or include complex comparisons.</p>
<p>The decision tree below summarizes the recommendations:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/mcp-decision-tree.png" class="img-fluid figure-img" width="600"></p>
<figcaption>Decision tree for choosing a multiple comparison procedure</figcaption>
</figure>
</div>
<p>The three most common procedures are <strong>Bonferroni</strong>, <strong>Tukey</strong>, and <strong>Scheffé</strong>. We will cover each in turn, using the hypertension dataset to illustrate.</p>
<hr>
</section>
<section id="bonferroni-correction" class="level2">
<h2 data-anchor-id="bonferroni-correction">3. Bonferroni Correction</h2>
<section id="the-logic" class="level3">
<h3 data-anchor-id="the-logic">The Logic</h3>
<p>Bonferroni is the simplest approach. If you are running <span class="math inline">\(C\)</span> tests and want your overall experimentwise error rate to be <span class="math inline">\(\alpha_{EW} = .05\)</span>, you just divide your significance threshold by <span class="math inline">\(C\)</span>:</p>
<p><span class="math display">\[\alpha_{Bonferroni} = \frac{\alpha_{EW}}{C} = \frac{.05}{C}\]</span></p>
<p>Each individual comparison must then have <span class="math inline">\(p &lt; \alpha_{Bonferroni}\)</span> to be declared significant. For example, if you plan 3 comparisons:</p>
<p><span class="math display">\[\alpha_{Bonferroni} = \frac{.05}{3} = .0167\]</span></p>
<p>This is conservative — by making each individual test harder to reject, the probability of <em>any</em> of them being a false positive is held at or below .05. It is a blunt instrument but it always works, as long as you can specify <span class="math inline">\(C\)</span> in advance.</p>
</section>
<section id="setting-c" class="level3">
<h3 data-anchor-id="setting-c">Setting C</h3>
<p>Deciding what <span class="math inline">\(C\)</span> should be is where researchers sometimes go wrong. The rule is: <span class="math inline">\(C\)</span> must reflect the number of comparisons that were <em>realistically considered</em>, not just the ones you formally ran.</p>
<ul>
<li>If you planned a specific set of <span class="math inline">\(C\)</span> comparisons before data collection, <span class="math inline">\(C\)</span> is that number.</li>
<li>If you want to test all pairwise comparisons (or if your original plan was all pairwise but you ended up testing fewer), <span class="math inline">\(C\)</span> must be set to <span class="math inline">\(\frac{a(a-1)}{2}\)</span>, where <span class="math inline">\(a\)</span> is the number of groups.</li>
<li>If you intended to test a subset of pairwise comparisons but then tested additional ones after seeing the data, again <span class="math inline">\(C = \frac{a(a-1)}{2}\)</span>.</li>
</ul>
<p>The key principle: if you let the data influence which comparisons you run, your <span class="math inline">\(C\)</span> expands to cover all comparisons that could have been selected.</p>
</section>
<section id="the-test-statistic-and-critical-value" class="level3">
<h3 data-anchor-id="the-test-statistic-and-critical-value">The Test Statistic and Critical Value</h3>
<p>The F statistic and confidence interval formulas for Bonferroni contrasts are identical to those from the Contrasts lesson — nothing changes there. What changes is the <strong>critical value</strong> you compare your F statistic to. Under the Bonferroni correction with equal variances:</p>
<p><span class="math display">\[CV = F_{\alpha/C;\; 1,\; df_{error}}\]</span></p>
<p>The confidence interval formula is:</p>
<p><span class="math display">\[\hat{\psi} \pm CV \sqrt{MS_W \sum_{j=1}^{a} \left(\frac{c_j^2}{n_j}\right)}\]</span></p>
<p>where <span class="math inline">\(CV = \sqrt{F_{\alpha/C;\; 1,\; df_{error}}}\)</span>.</p>
<p>When variances are unequal, the same CV applies but the F statistic and CI use group-specific variances <span class="math inline">\(s_j^2\)</span> in place of the pooled <span class="math inline">\(MS_W\)</span>, with adjusted degrees of freedom (the Welch-style correction from the Contrasts lesson).</p>
</section>
<section id="advantage-and-limitation" class="level3">
<h3 data-anchor-id="advantage-and-limitation">Advantage and Limitation</h3>
<p>The main advantage of Bonferroni is its simplicity and flexibility — it works for any set of contrasts, pairwise or complex, planned or post hoc (as long as <span class="math inline">\(C\)</span> is finite and specifiable).</p>
<p>The limitation is power. As <span class="math inline">\(C\)</span> grows, each individual threshold becomes more and more stringent, making it harder to detect real effects. For a small number of planned comparisons, Bonferroni is excellent. For a large number, or for post hoc complex comparisons where <span class="math inline">\(C\)</span> is theoretically infinite, it breaks down.</p>
<hr>
</section>
</section>
<section id="tukeys-hsd" class="level2">
<h2 data-anchor-id="tukeys-hsd">4. Tukey’s HSD</h2>
<section id="the-logic-1" class="level3">
<h3 data-anchor-id="the-logic-1">The Logic</h3>
<p>Tukey’s Honestly Significant Difference (HSD) procedure is designed specifically for <strong>all pairwise comparisons</strong>. Rather than dividing alpha by <span class="math inline">\(C\)</span>, Tukey uses a different statistical distribution — the <strong>studentized range distribution</strong> — to set a single critical value that simultaneously controls the familywise error rate across all <span class="math inline">\(\frac{a(a-1)}{2}\)</span> pairwise comparisons.</p>
<p>The core intuition is this: if you are going to run all pairwise comparisons, the most dangerous one — the one most likely to be a false positive — is the comparison between the largest and smallest group means. Tukey asks: how large can the range between the maximum and minimum group means get just by chance, assuming all population means are actually equal? It uses the sampling distribution of this worst-case difference to set a threshold, then applies that same threshold to all pairwise comparisons.</p>
<p>Formally, Tukey computes a <span class="math inline">\(q\)</span> statistic for a pairwise comparison between groups <span class="math inline">\(g\)</span> and <span class="math inline">\(h\)</span>:</p>
<p><span class="math display">\[q = \frac{\bar{Y}_g - \bar{Y}_h}{\sqrt{MS_W / n}}\]</span></p>
<p>The maximum <span class="math inline">\(q\)</span> across all pairs, <span class="math inline">\(q_{max}\)</span>, follows the <strong>studentized range distribution</strong> with parameters <span class="math inline">\(a\)</span> (number of groups) and <span class="math inline">\(df_{error}\)</span>. From that distribution you find the critical value <span class="math inline">\(q_{CV}\)</span>, which can be converted to a critical F value:</p>
<p><span class="math display">\[F_{CV} = \frac{q_{CV}^2}{2}\]</span></p>
</section>
<section id="test-equations" class="level3">
<h3 data-anchor-id="test-equations">Test Equations</h3>
<p>Assuming equal variances, the Tukey F statistic for the pairwise comparison between groups <span class="math inline">\(g\)</span> and <span class="math inline">\(h\)</span> is:</p>
<p><span class="math display">\[F_\psi = \frac{n_g n_h (\bar{Y}_g - \bar{Y}_h)^2}{(n_g + n_h) MS_W}\]</span></p>
<p>and the confidence interval is:</p>
<p><span class="math display">\[(\bar{Y}_g - \bar{Y}_h) \pm \frac{q_{CV}}{\sqrt{2}} \sqrt{MS_W \left(\frac{1}{n_g} + \frac{1}{n_h}\right)}\]</span></p>
<p>The critical value <span class="math inline">\(q_{CV}\)</span> is looked up from a studentized range table using the number of groups <span class="math inline">\(a\)</span> and <span class="math inline">\(df_{error}\)</span>. Note that <strong>Tukey requires equal variances</strong> — if that assumption is violated, Tukey is not appropriate.</p>
</section>
<section id="tukey-vs.-bonferroni-for-pairwise-comparisons" class="level3">
<h3 data-anchor-id="tukey-vs.-bonferroni-for-pairwise-comparisons">Tukey vs.&nbsp;Bonferroni for Pairwise Comparisons</h3>
<p>When you plan to test <em>all</em> pairwise comparisons, both Tukey and Bonferroni (with <span class="math inline">\(C = \frac{a(a-1)}{2}\)</span>) control the familywise error rate at .05. However, Tukey is more powerful in this situation, because its critical value is optimized for the structure of pairwise comparisons while Bonferroni is a general-purpose correction. The advantage grows as the number of groups increases:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Groups</th>
<th>Comparisons</th>
<th>Tukey CV</th>
<th>Bonferroni CV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td>1</td>
<td>4.75</td>
<td>4.75</td>
</tr>
<tr class="even">
<td>3</td>
<td>3</td>
<td>7.12</td>
<td>7.73</td>
</tr>
<tr class="odd">
<td>4</td>
<td>6</td>
<td>8.81</td>
<td>9.92</td>
</tr>
<tr class="even">
<td>5</td>
<td>10</td>
<td>10.16</td>
<td>11.76</td>
</tr>
<tr class="odd">
<td>6</td>
<td>15</td>
<td>11.28</td>
<td>13.32</td>
</tr>
</tbody>
</table>
<p>(Critical F values shown for <span class="math inline">\(df_{error} = 12\)</span>, <span class="math inline">\(\alpha = .05\)</span>.)</p>
<p>As the table shows, Tukey’s critical value stays lower than Bonferroni’s as more groups are added, meaning it is easier to reject the null with Tukey. When the number of pairwise comparisons is small (e.g., just 2 groups), they are equivalent.</p>
<p><strong>Rule of thumb:</strong> when all pairwise comparisons are of interest, Tukey is preferred over Bonferroni.</p>
</section>
<section id="an-important-limitation" class="level3">
<h3 data-anchor-id="an-important-limitation">An Important Limitation</h3>
<p>Tukey cannot be run through MANOVA in SPSS. It must be done through the <code>ONEWAY</code> procedure. This means that for more complex designs (within-subjects, split-plot, etc.), Tukey is generally not available unless you are willing to compute it by hand.</p>
<hr>
</section>
</section>
<section id="scheffés-method" class="level2">
<h2 data-anchor-id="scheffés-method">5. Scheffé’s Method</h2>
<section id="the-logic-2" class="level3">
<h3 data-anchor-id="the-logic-2">The Logic</h3>
<p>Scheffé is designed for <strong>post hoc complex comparisons</strong> — the situation where you decide which contrasts to test only after examining the data, and your contrasts may include complex (non-pairwise) comparisons.</p>
<p>In this situation, Bonferroni does not apply because <span class="math inline">\(C\)</span> is not defined — you did not select a pre-specified set of contrasts. And Tukey does not apply because Tukey only handles pairwise differences. Scheffé handles the general case.</p>
<p>The key insight behind Scheffé is that, in a post hoc setting, you are implicitly searching across <em>all possible contrasts</em> — not just pairwise ones, but any weighted combination of group means. Among all possible contrasts, one of them will necessarily have the largest <span class="math inline">\(SS_\psi\)</span> — the largest contrast sum of squares. Scheffé identifies what the maximum <span class="math inline">\(F\)</span> statistic could be under this worst-case selection and uses that as the critical value.</p>
<p>It turns out that the worst-case contrast can capture at most all of the between-groups sum of squares, <span class="math inline">\(SS_B\)</span>. Since the omnibus F statistic is <span class="math inline">\(F_{omnibus} = SS_B / [(a-1) \cdot MS_W]\)</span>, the maximum possible contrast F is:</p>
<p><span class="math display">\[F_{max} = (a - 1) \cdot F_{omnibus}\]</span></p>
<p>This leads directly to Scheffé’s critical value:</p>
<p><span class="math display">\[CV_{Scheffé} = (a - 1) \cdot F_{.05;\; a-1,\; N-a}\]</span></p>
<p>This is a fixed value that depends only on the number of groups and the error degrees of freedom — it does not change regardless of how many contrasts you test. That is what makes Scheffé appropriate for post hoc work: you do not need to pre-specify <span class="math inline">\(C\)</span>.</p>
</section>
<section id="test-equations-1" class="level3">
<h3 data-anchor-id="test-equations-1">Test Equations</h3>
<p>Assuming equal variances, the F statistic is identical to the standard contrast F:</p>
<p><span class="math display">\[F_\psi = \frac{(\hat{\psi})^2}{\left[MS_W \sum_{j=1}^{a} \left(\frac{c_j^2}{n_j}\right)\right]}\]</span></p>
<p>The confidence interval is:</p>
<p><span class="math display">\[\hat{\psi} \pm \sqrt{(a-1) F_{.05;\; a-1,\; N-a}} \cdot \sqrt{MS_W \sum_{j=1}^{a} \left(\frac{c_j^2}{n_j}\right)}\]</span></p>
<p>You compare the calculated <span class="math inline">\(F_\psi\)</span> to <span class="math inline">\((a-1) F_{.05;\; a-1,\; N-a}\)</span>. If <span class="math inline">\(F_\psi\)</span> exceeds the critical value, the contrast is significant.</p>
<p><strong>Important:</strong> Scheffé requires equal variances. If heterogeneity of variance is present, Scheffé is not appropriate.</p>
</section>
<section id="the-omnibus-connection" class="level3">
<h3 data-anchor-id="the-omnibus-connection">The Omnibus Connection</h3>
<p>There is a useful and elegant link between Scheffé and the omnibus ANOVA: <strong>if and only if the omnibus F test is significant, at least one contrast will be significant by Scheffé’s method</strong>. Conversely, if the omnibus test is non-significant, Scheffé cannot produce any significant contrasts. This means that if your omnibus ANOVA is non-significant, you can skip Scheffé entirely — you already know the answer.</p>
</section>
<section id="scheffé-vs.-bonferroni-when-to-use-which" class="level3">
<h3 data-anchor-id="scheffé-vs.-bonferroni-when-to-use-which">Scheffé vs.&nbsp;Bonferroni: When to Use Which</h3>
<p>Both Scheffé and Bonferroni can be used for planned complex comparisons. The question is which one gives you more power (i.e., lower critical value) for your specific situation. The answer depends on how many comparisons you are making:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>C (# Comparisons)</th>
<th>Bonferroni CV</th>
<th>Scheffé CV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>4.17</td>
<td>8.76</td>
</tr>
<tr class="even">
<td>2</td>
<td>5.57</td>
<td>8.76</td>
</tr>
<tr class="odd">
<td>3</td>
<td>6.45</td>
<td>8.76</td>
</tr>
<tr class="even">
<td>4</td>
<td>7.08</td>
<td>8.76</td>
</tr>
<tr class="odd">
<td>…</td>
<td>…</td>
<td>8.76</td>
</tr>
<tr class="even">
<td>9</td>
<td>8.94</td>
<td>8.76</td>
</tr>
<tr class="odd">
<td>10</td>
<td>9.18</td>
<td>8.76</td>
</tr>
</tbody>
</table>
<p>(For <span class="math inline">\(a = 4\)</span> groups, <span class="math inline">\(df_{error} = 30\)</span>.)</p>
<p>Bonferroni’s critical value increases with <span class="math inline">\(C\)</span>, while Scheffé’s stays fixed. They cross over at around 8 comparisons. So:</p>
<ul>
<li>For a <strong>small number of planned comparisons</strong>, Bonferroni has more power and should be preferred.</li>
<li>For a <strong>large number of comparisons or post hoc complex contrasts</strong>, Scheffé is preferred (and may be the only valid option).</li>
<li><strong>Scheffé should not be used unless at least one comparison is complex.</strong> For pairwise-only post hoc comparisons, use Tukey.</li>
</ul>
<hr>
</section>
</section>
<section id="implementing-mcps-in-spss" class="level2">
<h2 data-anchor-id="implementing-mcps-in-spss">6. Implementing MCPs in SPSS</h2>
<section id="pairwise-comparisons-with-oneway" class="level3">
<h3 data-anchor-id="pairwise-comparisons-with-oneway">Pairwise Comparisons with ONEWAY</h3>
<p>The easiest way to run all three procedures for all pairwise comparisons is via the <code>ONEWAY</code> command. Just add a <code>/posthoc=</code> line:</p>
<pre class="text"><code>ONEWAY pressure BY treat
/statistics descriptives
/posthoc=tukey scheffe bonferroni.</code></pre>
<p>This produces a “Multiple Comparisons” table in the output that lists every pairwise mean difference for each correction method, along with its standard error, adjusted <span class="math inline">\(p\)</span> value, and 95% confidence interval. The output is easy to read and directly interpretable.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/3.1.png" class="img-fluid figure-img"></p>
<figcaption>ONEWAY output with Tukey, Scheffé, and Bonferroni pairwise comparisons</figcaption>
</figure>
</div>
<p>In the output, each row shows a pair of groups (I) and (J), the mean difference (I–J), the standard error, the adjusted significance value, and the 95% CI. For Tukey and Bonferroni, you can use the <span class="math inline">\(p\)</span> values directly — they are adjusted. For Scheffé in pairwise mode, the <span class="math inline">\(p\)</span> values are also valid here since ONEWAY computes them correctly.</p>
<p>This syntax works well when your goal is all pairwise comparisons. However, <strong>if you want to test specific planned contrasts or complex comparisons, you need to use MANOVA</strong> with the <code>/cinterval</code> line instead.</p>
<p><strong>Note:</strong> ONEWAY cannot do within-subjects or factorial designs. For those, you will always need MANOVA.</p>
</section>
<section id="bonferroni-with-manova" class="level3">
<h3 data-anchor-id="bonferroni-with-manova">Bonferroni with MANOVA</h3>
<p>To apply a Bonferroni correction to specific planned contrasts in MANOVA, you use the <code>/cinterval=individual(#)</code> line. The <code>#</code> is the confidence level for each <em>individual</em> interval, calculated as:</p>
<p><span class="math display">\[\# = 1 - \frac{\alpha}{C} = 1 - \frac{.05}{C}\]</span></p>
<p>For our hypertension example, suppose you planned the following 3 contrasts before data collection:</p>
<ol type="1">
<li>Drug therapy &amp; biofeedback &amp; diet vs.&nbsp;combination (<span class="math inline">\(\psi_1\)</span>)</li>
<li>Drug therapy &amp; biofeedback vs.&nbsp;diet &amp; combination (<span class="math inline">\(\psi_2\)</span>)</li>
<li>Drug therapy vs.&nbsp;biofeedback (<span class="math inline">\(\psi_3\)</span>)</li>
</ol>
<p>With <span class="math inline">\(C = 3\)</span>:</p>
<p><span class="math display">\[\# = 1 - \frac{.05}{3} = 1 - .0167 = .9833\]</span></p>
<p>The SPSS syntax is:</p>
<pre class="text"><code>MANOVA pressure BY treat (1 4)
/print=cellinfo(means)
/error=within
/cinterval =individual(.9833)
/contrast(treat) = special (1    1    1    1
                             1    1    1   -3
                             .5   .5  -.5  -.5
                             1   -1    0    0)
/design = treat(1) treat(2) treat(3).</code></pre>
<p>The number <code>.9833</code> tells SPSS to construct a 98.33% confidence interval for each individual contrast. This is what makes the family-wise error rate .05 across 3 contrasts: each comparison gets a stricter interval than the usual 95%.</p>
<p>To assess significance, compare each <span class="math inline">\(p\)</span> value in the output to your corrected <span class="math inline">\(\alpha = .05/C = .0167\)</span>. If <span class="math inline">\(p &lt; .0167\)</span>, the contrast is significant under Bonferroni.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/3.2.png" class="img-fluid figure-img"></p>
<figcaption>MANOVA output with Bonferroni correction (individual .9833 confidence intervals)</figcaption>
</figure>
</div>
<p>The output shows the <code>Coeff.</code> (your <span class="math inline">\(\hat{\psi}\)</span>), <code>Std. Err.</code>, <code>t-Value</code>, <code>Sig. t</code> (the <span class="math inline">\(p\)</span> value), and the lower and upper bounds of the confidence interval. Compare each <span class="math inline">\(p\)</span> value to <span class="math inline">\(\alpha/C\)</span>. Note that the confidence intervals printed reflect the Bonferroni-corrected width.</p>
<p><strong>To get the F statistic from this output:</strong> square the <span class="math inline">\(t\)</span>-Value. So <span class="math inline">\(t^2 = F\)</span>.</p>
<p><strong>If you plan to test 4 comparisons</strong> (across one or two MANOVA calls), the corrected confidence level would be <span class="math inline">\(1 - (.05/4) = .9875\)</span>, regardless of how many contrasts appear in each individual MANOVA call.</p>
</section>
<section id="scheffé-with-manova" class="level3">
<h3 data-anchor-id="scheffé-with-manova">Scheffé with MANOVA</h3>
<p>To apply a Scheffé correction in MANOVA, change the <code>/cinterval</code> line to use the joint and univariate Scheffé specification:</p>
<pre class="text"><code>MANOVA pressure BY treat (1 4)
/print=cellinfo(means)
/error=within
/cinterval = joint(.95) univariate(scheffe)
/contrast(treat) = special (1    1    1    1
                             1    1    1   -3
                             .5   .5  -.5  -.5
                             1   -1    0    0)
/design = treat.</code></pre>
<p>Two things have changed from the Bonferroni syntax:</p>
<p><strong>The <code>/cinterval</code> line</strong> now uses <code>joint(.95) univariate(scheffe)</code>. <code>joint(.95)</code> keeps the <em>family-wise</em> error rate at .05 across all contrasts tested together. <code>univariate(scheffe)</code> specifies the Scheffé method for each individual contrast interval.</p>
<p><strong>The <code>/design</code> line</strong> has changed from <code>treat(1) treat(2) treat(3)</code> to simply <code>treat</code>. This is critical. MANOVA uses the <code>/design</code> line not only to specify what goes in the model, but also to define what constitutes a <em>family</em> of tests. If you leave it as <code>treat(1) treat(2) treat(3)</code>, MANOVA treats each contrast as its own separate family, which sets <span class="math inline">\(\alpha_{PC} = .05\)</span> for each one individually — defeating the purpose of the correction. Writing <code>/design = treat.</code> tells MANOVA to treat all contrasts together as a single family, so the correction applies across all of them jointly.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/3.3.png" class="img-fluid figure-img"></p>
<figcaption>MANOVA output with Scheffé correction (joint .95 univariate Scheffé confidence intervals)</figcaption>
</figure>
</div>
<p><strong>Critical warning about the Scheffé output:</strong> The <span class="math inline">\(p\)</span> values in the Scheffé MANOVA output are <strong>not corrected</strong>. Do not use them for significance testing. SPSS provides the Scheffé-corrected confidence intervals and the <span class="math inline">\(t\)</span> statistics (which you square to get <span class="math inline">\(F\)</span>), but the printed <span class="math inline">\(p\)</span> values are the ordinary uncorrected ones. To assess significance with Scheffé, you must either:</p>
<ol type="1">
<li>Compare the calculated <span class="math inline">\(F_\psi = t^2\)</span> to the Scheffé critical value <span class="math inline">\((a-1) F_{.05;\; a-1,\; N-a}\)</span>, or</li>
<li>Check whether the Scheffé confidence interval excludes zero.</li>
</ol>
<p>For our hypertension example with <span class="math inline">\(a = 4\)</span> groups and <span class="math inline">\(df_{error} = 16\)</span> (since <span class="math inline">\(n = 5\)</span> per group, <span class="math inline">\(N = 20\)</span>), the Scheffé critical value is:</p>
<p><span class="math display">\[CV_{Scheffé} = (4-1) \times F_{.05;\; 3,\; 16} = 3 \times 3.24 = 9.72\]</span></p>
<p>Any contrast F statistic must exceed 9.72 to be declared significant.</p>
<hr>
</section>
</section>
<section id="summary-choosing-your-mcp" class="level2">
<h2 data-anchor-id="summary-choosing-your-mcp">7. Summary: Choosing Your MCP</h2>
<p>The choice of correction method comes down to your research context:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th>Situation</th>
<th>Recommended Procedure</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Small set of planned contrasts (pairwise or complex)</td>
<td>Bonferroni</td>
</tr>
<tr class="even">
<td>All pairwise comparisons planned or post hoc</td>
<td>Tukey</td>
</tr>
<tr class="odd">
<td>Post hoc complex comparisons</td>
<td>Scheffé</td>
</tr>
<tr class="even">
<td>Planned contrasts with many comparisons</td>
<td>Compare Bonferroni and Scheffé CVs; use the lower one</td>
</tr>
</tbody>
</table>
<p>A few additional reminders:</p>
<ul>
<li>Tukey and Scheffé <strong>require equal variances</strong>. If the homogeneity of variance assumption is violated, use Bonferroni (which can accommodate heterogeneous variances via the unequal variance formulas).</li>
<li>Tukey <strong>cannot be implemented via MANOVA</strong> in SPSS; use <code>ONEWAY</code> for Tukey.</li>
<li>For Scheffé in MANOVA, always use <code>/design = treat.</code> (not the individual contrast design) to ensure the correction applies family-wide.</li>
<li>For Scheffé, <strong>never use the output</strong> <span class="math inline">\(p\)</span> values — only use the <span class="math inline">\(F\)</span> statistic vs.&nbsp;the critical value or the confidence intervals.</li>
<li>If the omnibus ANOVA is non-significant, Scheffé will never find a significant contrast. You can skip it.</li>
</ul>
<hr>
</section>
<section id="discussion-questions" class="level2">
<h2 data-anchor-id="discussion-questions">Discussion Questions</h2>
<p><strong>Q1.</strong> Using the hypertension data, a researcher runs all 6 pairwise comparisons after looking at the data and seeing that groups 1 and 4 look particularly different. What should <span class="math inline">\(C\)</span> be set to, and why? Which method would you recommend?</p>
<p><strong>Q2.</strong> A researcher plans 3 contrasts before data collection: one complex and two pairwise. Which correction method(s) are appropriate? What would you need to compare to decide between them?</p>
<p><strong>Q3.</strong> Explain in your own words why the <span class="math inline">\(p\)</span> values in the MANOVA Scheffé output cannot be used for significance testing. What can you use instead?</p>
<p><strong>Q4.</strong> Without using <span class="math inline">\(p\)</span> values, how can you assess whether a contrast is significant? Use a worked example from the ONEWAY output above to illustrate.</p>
<p><strong>Q5.</strong> Using the decision tree, classify each of the following scenarios and identify the appropriate MCP:</p>
<ol type="a">
<li>4 groups; all 6 pairwise comparisons; planned in advance.</li>
<li>4 groups; 3 planned complex contrasts.</li>
<li>4 groups; 2 pairwise and 1 complex; decided after looking at the data.</li>
<li>4 groups; all pairwise; decided after looking at the data.</li>
</ol>
<p><strong>Q6.</strong> Suppose you have 4 groups and <span class="math inline">\(df_{error} = 30\)</span>. You are planning 4 complex comparisons. Looking at the Bonferroni vs.&nbsp;Scheffé critical value table, which method should you choose? At what number of comparisons does your answer change?</p>
<hr>
</section>
<section id="well-done" class="level2">
<h2 data-anchor-id="well-done">Well Done!</h2>
<p>You have completed the Multiple Comparisons lesson. Here is a summary of what was covered:</p>
<ul>
<li>How running multiple tests inflates the experimentwise Type I error rate</li>
<li>The distinction between per-comparison and experimentwise error rates, and the formula <span class="math inline">\(\alpha_{EW} = 1 - (1 - \alpha)^C\)</span></li>
<li>The difference between planned and post hoc comparisons, and why post hoc selection inflates <span class="math inline">\(C\)</span></li>
<li>The three main correction procedures: Bonferroni (flexible, best for small planned sets), Tukey (best for all pairwise), and Scheffé (best for post hoc complex comparisons)</li>
<li>How to implement each in SPSS using <code>ONEWAY</code> (for Tukey and simple pairwise) and <code>MANOVA</code> (for Bonferroni with <code>/cinterval=individual(#)</code> and Scheffé with <code>/cinterval=joint(.95) univariate(scheffe)</code>)</li>
<li>The critical gotcha for Scheffé: never use the output <span class="math inline">\(p\)</span> values; use the <span class="math inline">\(F\)</span> statistic vs.&nbsp;the critical value or the confidence intervals</li>
<li>The link between Scheffé and the omnibus F test</li>
</ul>


</section>

</main> <!-- /main -->
<!-- MailerLite Universal -->
<script>
    (function(w,d,e,u,f,l,n){w[f]=w[f]||function(){(w[f].q=w[f].q||[])
    .push(arguments);},l=d.createElement(e),l.async=1,l.src=u,
    n=d.getElementsByTagName(e)[0],n.parentNode.insertBefore(l,n);})
    (window,document,'script','https://assets.mailerlite.com/js/universal.js','ml');
    ml('account', '2295583');
</script>
<!-- End MailerLite Universal -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/infogothic\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>