<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Michael Woller">

<title>One-Way Within-Subjects ANOVA – InfoGothic</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-f418161beb48e0141c760e455f12af2c.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-4d14f3be7bc8eb7ec2287338953877e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
document.addEventListener("DOMContentLoaded", function() {
  var nav = document.querySelector(".navbar-nav");
  var li = document.createElement("li");
  li.className = "nav-item";
  li.innerHTML = '<a class="nav-link ml-onclick-form" href="javascript:void(0)" onclick="ml(\'show\', \'18mxag\', true)">Mail List</a>';
  var icons = nav.querySelector(".nav-item:has(.bi)");
  nav.insertBefore(li, icons);
});
</script>
<script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">InfoGothic</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../tutorials.html"> 
<span class="menu-text">Courses &amp; Tutorials</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog-posts.html"> 
<span class="menu-text">Blog Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://notes.infogothic.com"> 
<span class="menu-text">Obsidian Notes</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/michaelwoller"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://bsky.app/profile/infogothic.bsky.social"> <i class="bi bi-bluesky" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">1. Introduction</a></li>
  <li><a href="#setting-up-the-data-file" id="toc-setting-up-the-data-file" class="nav-link" data-scroll-target="#setting-up-the-data-file">2. Setting Up the Data File</a></li>
  <li><a href="#key-concepts-main-effects-interactions-simple-effects-and-marginal-means" id="toc-key-concepts-main-effects-interactions-simple-effects-and-marginal-means" class="nav-link" data-scroll-target="#key-concepts-main-effects-interactions-simple-effects-and-marginal-means">3. Key Concepts: Main Effects, Interactions, Simple Effects, and Marginal Means</a></li>
  <li><a href="#the-full-and-reduced-models" id="toc-the-full-and-reduced-models" class="nav-link" data-scroll-target="#the-full-and-reduced-models">4. The Full and Reduced Models</a>
  <ul class="collapse">
  <li><a href="#table-representation" id="toc-table-representation" class="nav-link" data-scroll-target="#table-representation">Table Representation</a></li>
  </ul></li>
  <li><a href="#running-the-omnibus-test-in-spss" id="toc-running-the-omnibus-test-in-spss" class="nav-link" data-scroll-target="#running-the-omnibus-test-in-spss">5. Running the Omnibus Test in SPSS</a></li>
  <li><a href="#choosing-your-follow-up-test-the-decision-tree" id="toc-choosing-your-follow-up-test-the-decision-tree" class="nav-link" data-scroll-target="#choosing-your-follow-up-test-the-decision-tree">6. Choosing Your Follow-Up Test: The Decision Tree</a></li>
  <li><a href="#marginal-mean-comparisons-no-interaction-significant-main-effect" id="toc-marginal-mean-comparisons-no-interaction-significant-main-effect" class="nav-link" data-scroll-target="#marginal-mean-comparisons-no-interaction-significant-main-effect">7. Marginal Mean Comparisons (No Interaction, Significant Main Effect)</a>
  <ul class="collapse">
  <li><a href="#marginal-means-in-spss" id="toc-marginal-means-in-spss" class="nav-link" data-scroll-target="#marginal-means-in-spss">Marginal Means in SPSS</a></li>
  </ul></li>
  <li><a href="#simple-effects-significant-interaction" id="toc-simple-effects-significant-interaction" class="nav-link" data-scroll-target="#simple-effects-significant-interaction">8. Simple Effects (Significant Interaction)</a>
  <ul class="collapse">
  <li><a href="#simple-effects-in-spss" id="toc-simple-effects-in-spss" class="nav-link" data-scroll-target="#simple-effects-in-spss">Simple Effects in SPSS</a></li>
  </ul></li>
  <li><a href="#cell-mean-comparisons-within-simple-effects" id="toc-cell-mean-comparisons-within-simple-effects" class="nav-link" data-scroll-target="#cell-mean-comparisons-within-simple-effects">9. Cell Mean Comparisons Within Simple Effects</a>
  <ul class="collapse">
  <li><a href="#cell-mean-comparisons-in-spss" id="toc-cell-mean-comparisons-in-spss" class="nav-link" data-scroll-target="#cell-mean-comparisons-in-spss">Cell Mean Comparisons in SPSS</a></li>
  </ul></li>
  <li><a href="#type-i-error-correction-for-simple-effects-and-cell-mean-comparisons" id="toc-type-i-error-correction-for-simple-effects-and-cell-mean-comparisons" class="nav-link" data-scroll-target="#type-i-error-correction-for-simple-effects-and-cell-mean-comparisons">10. Type I Error Correction for Simple Effects and Cell Mean Comparisons</a>
  <ul class="collapse">
  <li><a href="#treating-simple-effects-as-one-family" id="toc-treating-simple-effects-as-one-family" class="nav-link" data-scroll-target="#treating-simple-effects-as-one-family">Treating Simple Effects as One Family</a></li>
  <li><a href="#treating-simple-effects-as-seperate-families" id="toc-treating-simple-effects-as-seperate-families" class="nav-link" data-scroll-target="#treating-simple-effects-as-seperate-families">Treating Simple Effects as Seperate Families</a></li>
  </ul></li>
  <li><a href="#interaction-contrasts" id="toc-interaction-contrasts" class="nav-link" data-scroll-target="#interaction-contrasts">11. Interaction Contrasts</a>
  <ul class="collapse">
  <li><a href="#interaction-contrasts-in-spss" id="toc-interaction-contrasts-in-spss" class="nav-link" data-scroll-target="#interaction-contrasts-in-spss">Interaction Contrasts in SPSS</a></li>
  </ul></li>
  <li><a href="#applying-this-to-your-assignment" id="toc-applying-this-to-your-assignment" class="nav-link" data-scroll-target="#applying-this-to-your-assignment">12. Applying This to Your Assignment</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">13. Summary</a></li>
  <li><a href="#discussion-questions" id="toc-discussion-questions" class="nav-link" data-scroll-target="#discussion-questions">Discussion Questions</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">One-Way Within-Subjects ANOVA</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Michael Woller </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 data-anchor-id="introduction">1. Introduction</h2>
<p>Every lesson so far in this series has involved a single factor. We have had one grouping variable (drug therapy, biofeedback, dietary modification, combination) and asked how the levels of that one variable relate to an outcome. But a great deal of research involves crossing two factors at once. This is called a <strong>general factorial design</strong>, or more specifically here, a <strong>two-way between-subjects ANOVA</strong>.</p>
<p>In a two-way design, every subject belongs to one level of Factor A and one level of Factor B at the same time. This lets us ask three separate questions in a single analysis:</p>
<ol type="1">
<li>Does the outcome differ across levels of Factor A, ignoring Factor B? (<strong>main effect of A</strong>)</li>
<li>Does the outcome differ across levels of Factor B, ignoring Factor A? (<strong>main effect of B</strong>)</li>
<li>Does the effect of one factor depend on the level of the other factor? (<strong>interaction effect</strong>)</li>
</ol>
<p>That third question is the one one-way designs can never answer, and it is often the most interesting one. Crossing two factors does not just let you ask two questions for the price of one. It lets you ask a question you could not ask at all with either factor alone.</p>
<p>Two-way designs also have the benefit of controlling for more error variation, thus lowering the <span class="math inline">\(MS_{within}\)</span> (recall, within-group variation equals error variation). Thus, we are taking a larger chunk out of the error slice of the pie to fill <em>both</em> group effects as well as the interaction.</p>
<div class="concept-diagram">
<div style="display: flex; justify-content: center; gap: 40px; flex-wrap: wrap;">

<svg width="100%" viewbox="0 0 400 420" xmlns="http://www.w3.org/2000/svg" style="display: block; max-width: 320px;">
  <text x="200" y="30" class="title" font-size="18">One-way design</text>

  <path class="pie-a" d="M200,200 L200,50 A150,150 0 0,1 327.48,125 Z"></path>
  <path class="pie-error" d="M200,200 L327.48,125 A150,150 0 1,1 200,50 Z"></path>

  <text x="237" y="115" class="pie-label">A</text>
  <text x="178" y="260" class="pie-label">Error</text>
</svg>

<svg width="100%" viewbox="0 0 400 420" xmlns="http://www.w3.org/2000/svg" style="display: block; max-width: 320px;">
  <text x="200" y="30" class="title" font-size="18">Two-way design</text>

  <path class="pie-ab" d="M200,200 L200,50 A150,150 0 0,1 350,200 Z"></path>
  <path class="pie-error" d="M200,200 L350,200 A150,150 0 0,1 173.96,347.72 Z"></path>
  <path class="pie-a" d="M200,200 L173.96,347.72 A150,150 0 0,1 70.1,275 Z"></path>
  <path class="pie-b" d="M200,200 L70.1,275 A150,150 0 0,1 200,50 Z"></path>

  <text x="264" y="136" class="pie-label">A x B</text>
  <text x="258" y="269" class="pie-label">Error</text>
  <text x="148" y="274" class="pie-label">A</text>
  <text x="122" y="155" class="pie-label">B</text>
</svg>

</div>
</div>
<p>Both circles represent the same total variance for the same subjects, just split apart differently depending on which terms the model includes. On the left, a one-way ANOVA only has factor A in the model, so any variability connected to the other factor B, including the A*B interaction, has nowhere to go and gets absorbed into the error On the right, once B and the interaction are added to the model, that same variability gets pulled out into its own labeled slices, leaving a noticeably smaller error slice behind. A smaller error term generally means a more powerful test, since this causes the <span class="math inline">\(MS_{error}\)</span> to shrink and the <span class="math inline">\(F\)</span> statistic to grow for any effect you go on to test.</p>
<p>We will use the TwoWayBetween.sav dataset from throughout this lesson. This consists of an outcome variable called <strong>score</strong>, where lower scores mean a greater reduction in symptoms. This outcome is crossed with two factors:</p>
<ul>
<li><strong>Diagnosis</strong>: Schizophrenia or Depression (2 levels)</li>
<li><strong>Drug</strong>: Drug 1, Drug 2, or Drug 3 (3 levels)</li>
</ul>
<p>This is a 2x3 factorial design. By the end of the lesson you will be able to run the omnibus test, decide which follow-up procedure is appropriate based on what is and is not significant, and write the annotated MANOVA syntax for each one.</p>
<p>This is by far the densest lesson in the entire course as it introduces a lot of new concepts. Future lessons will be partially building on these concepts, so it is important to learn them here in just the two-way ANOVA context so you don’t need to worry about learning them in the future again.</p>
</section>
<section id="setting-up-the-data-file" class="level2">
<h2 data-anchor-id="setting-up-the-data-file">2. Setting Up the Data File</h2>
<p>To represent group membership in a study with two or more factors, you need multiple grouping variables. For a two-factor study, three columns are required:</p>
<ul>
<li>Scores on the dependent variable</li>
<li>Group membership for Factor A (diagnosis: Schizophrenia or Depression)</li>
<li>Group membership for Factor B (drug: 1, 2, or 3)</li>
</ul>
<p>Here is a small example dataset, shown first in the “wide” layout you might sketch by hand, and then in the long format SPSS actually needs.</p>
<p><strong>Wide layout (for your own reference, not how SPSS wants it):</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Drug 1</th>
<th>Drug 2</th>
<th>Drug 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Schizophrenia (A1)</strong></td>
<td>8, 4, 0</td>
<td>8, 10, 6</td>
<td>4, 6, 8</td>
</tr>
<tr class="even">
<td><strong>Depression (A2)</strong></td>
<td>10, 6, 14</td>
<td>0, 4, 2</td>
<td>15, 9, 12</td>
</tr>
</tbody>
</table>
<p><strong>Long format (how SPSS needs it):</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>score</th>
<th>diagnosis</th>
<th>drug</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>8</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td>4</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>0</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td>8</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="odd">
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="even">
<td>14</td>
<td>2</td>
<td>1</td>
</tr>
<tr class="odd">
<td>2</td>
<td>2</td>
<td>2</td>
</tr>
<tr class="even">
<td>12</td>
<td>2</td>
<td>3</td>
</tr>
</tbody>
</table>
<p>Each dependent variable lives in one column, and there should be as many grouping columns as there are between-subjects factors. Every row is a single subject’s score plus their group membership on both factors.</p>
<p>Importantly, this dataset is <strong>unbalanced</strong>, which means that there is not an equal number of individuals in each group combination, as opposed to a <strong>balanced</strong> design where group sizes are equal. This distinction matters because balanced designs have a convenient property: the sums of squares for each effect partition cleanly and add up to the total, so the order in which effects are entered into the model does not affect their tests. The bottom line for balanaced designs is that you can procede as normal without needing to adjust your model/syntax.</p>
<p>When a design is unbalanced, this clean partitioning of the sum of squares breaks down. The sums of squares for one effect can depend on which other effects are already in the model, meaning that different computational approaches can yield different results for the same hypothesis. SPSS offers three types of sums of squares to handle this situation, which we covered in the very first Introduction to SPSS and One-Way ANOVA lesson. The choice between them reflects a choice about what question is actually being asked. Type III sums of squares, which test each effect after accounting for all other effects in the model, is the default in SPSS MANOVA and is generally the most appropriate choice for testing the effects of interest in an unbalanced factorial design. So in order to get Type III sum of squares, we need to make additions to the SPSS syntax for unbalanaced designs, which I will bring up when we go over the code.</p>
</section>
<section id="key-concepts-main-effects-interactions-simple-effects-and-marginal-means" class="level2">
<h2 data-anchor-id="key-concepts-main-effects-interactions-simple-effects-and-marginal-means">3. Key Concepts: Main Effects, Interactions, Simple Effects, and Marginal Means</h2>
<p>Before touching any syntax, it helps to fix the vocabulary using the same 2x3 grid we will analyze. Here are the cell means we will use as our running example for the rest of the lesson:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Drug 1</th>
<th>Drug 2</th>
<th>Drug 3</th>
<th>Marginal mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Schizophrenia</strong></td>
<td>4.000</td>
<td>9.333</td>
<td>5.250</td>
<td>6.194</td>
</tr>
<tr class="even">
<td><strong>Depression</strong></td>
<td>9.500</td>
<td>1.500</td>
<td>13.333</td>
<td>8.111</td>
</tr>
<tr class="odd">
<td><strong>Marginal mean</strong></td>
<td>6.750</td>
<td>5.417</td>
<td>9.292</td>
<td></td>
</tr>
</tbody>
</table>
<p>A <strong>cell mean</strong> is the average score for one specific combination of factor levels, for example the mean of the Schizophrenia for Drug 1 is 4.000.</p>
<p>A <strong>marginal mean</strong> is the average for one level of one factor, collapsing across (averaging over) the other factor. The row marginal means collapsing across drug give you the overall mean for each diagnosis: 6.194 for Schizophrenia and 8.111 for Depression. The column marginal means collapse across diagnosis to give you the overall mean for each drug: Drug 1 = 6.750, Drug 2 = 5.417, and Drug 3 = 9.292)</p>
<p>The <strong>main effect of Drug</strong> asks whether the column marginal means differ from one another (i.e., are 6.750, 5.417, and 9.292 significantly different). The <strong>main effect of Diagnosis</strong> asks whether the row marginal means differ from one another (i.e., are 6.194 and 8.111 significantly different). Neither of these looks at the individual cells, only at the marginal averages.</p>
<p>The <strong>interaction effect</strong> asks whether the effect of Drug is the same across both levels of Diagnosis. Look at the table again: Drug 2 produces the lowest score for Depression (1.500) but the highest score for Schizophrenia among the three drugs aside from Drug 3 (9.333). The pattern of differences across drug is not the same in each row. At glance, this appears to be an interaction.</p>
<p>A <strong>simple effect</strong> is the effect of one factor at a single, fixed level of the other factor. For example, “the simple effect of Drug <em>within</em> Schizophrenia” only looks at the mean outcomes in the Schizophrenia row (4.000, 9.333, 5.250) and asks whether those three numbers differ. This is different from the main effect of Drug, which would average the Schizophrenia and Depression rows together first.</p>
<p>Keeping these four terms straight (main effect, interaction, simple effect, marginal mean) is the single most important thing in this lesson, because which one is significant determines which follow-up test you are allowed to run.</p>
</section>
<section id="the-full-and-reduced-models" class="level2">
<h2 data-anchor-id="the-full-and-reduced-models">4. The Full and Reduced Models</h2>
<p>Just like in the one-way case, every test in a two-way ANOVA is a comparison between a full model and a reduced model. Like before, these aren’t necessary to know, but they are helpful in undertanding what the ANOVA is actually doing. The simplest and most intuitive way to write this model is in <strong>effects notation</strong>, which describes each factor’s mean by pieces:</p>
<p><span class="math display">\[Y_{ijk} = \mu + \alpha_j + \beta_k + (\alpha\beta)_{jk} + \varepsilon_{ijk}\]</span></p>
<p>Here <span class="math inline">\(\mu\)</span> is the grand mean, <span class="math inline">\(\alpha_j\)</span> is the effect of Diagnosis level <span class="math inline">\(j\)</span>, <span class="math inline">\(\beta_k\)</span> is the effect of Drug level <span class="math inline">\(k\)</span>, and <span class="math inline">\((\alpha\beta)_{jk}\)</span> is the interaction term, and <span class="math inline">\(\varepsilon_{ijk}\)</span> is the part of the cell means that is not explained by any of the groups.</p>
<p>Each effect is tested by comparing this full model to a reduced model that removes one piece:</p>
<p><strong>Testing the interaction:</strong></p>
<ul>
<li>Full model: <span class="math inline">\(Y_{ijk} = \mu + \alpha_j + \beta_k + (\alpha\beta)_{jk} + \varepsilon_{ijk}\)</span></li>
<li>Reduced model: <span class="math inline">\(Y_{ijk} = \mu + \alpha_j + \beta_k + \varepsilon_{ijk}\)</span></li>
</ul>
<p><strong>Null Hypothesis:</strong> The interaction effect is 0. <span class="math inline">\((\alpha\beta)_{jk}=0\)</span></p>
<hr>
<p><strong>Testing the main effect of Diagnosis (A):</strong></p>
<ul>
<li>Full model: <span class="math inline">\(Y_{ijk} = \mu + \alpha_j + \beta_k + \varepsilon_{ijk}\)</span></li>
<li>Reduced model: <span class="math inline">\(Y_{ijk} = \mu + \beta_k + \varepsilon_{ijk}\)</span> (drop <span class="math inline">\(\alpha_j\)</span>)</li>
</ul>
<p><strong>Null Hypothesis:</strong> The main effect of Diagnosis (A) is 0. <span class="math inline">\(\alpha_j =0\)</span></p>
<hr>
<p><strong>Testing the main effect of Drug (B):</strong></p>
<ul>
<li>Full model: <span class="math inline">\(Y_{ijk} = \mu + \alpha_j + \beta_k + \varepsilon_{ijk}\)</span></li>
<li>Reduced model: <span class="math inline">\(Y_{ijk} = \mu + \alpha_j + \varepsilon_{ijk}\)</span> (drop <span class="math inline">\(\beta_k\)</span>)</li>
</ul>
<p><strong>Null Hypothesis:</strong> The main effect of Drug (B) is 0. <span class="math inline">\(\beta_k =0\)</span></p>
<section id="table-representation" class="level3">
<h3 data-anchor-id="table-representation">Table Representation</h3>
<p>One can understand the main effects in our scenario via the table below.</p>
<div class="concept-diagram">
<svg width="100%" viewbox="0 0 760 380" xmlns="http://www.w3.org/2000/svg" style="max-width: 850px; display: block; margin: 0 auto;">
  <defs>
    <marker id="arrow-orange" viewbox="0 0 10 10" refx="8" refy="5" markerwidth="7" markerheight="7" orient="auto-start-reverse">
      <path d="M0 0L10 5L0 10Z" fill="#e8923f"></path>
    </marker>
    <marker id="arrow-teal" viewbox="0 0 10 10" refx="8" refy="5" markerwidth="7" markerheight="7" orient="auto-start-reverse">
      <path d="M0 0L10 5L0 10Z" fill="#2c6e73"></path>
    </marker>
  </defs>

  <text x="345" y="26" class="title">Main effect</text>
  <text x="345" y="55" class="header">Drug</text>
  <text x="195" y="82" class="header">1</text>
  <text x="345" y="82" class="header">2</text>
  <text x="495" y="82" class="header">3</text>

  <text x="40" y="155" class="axis-label" transform="rotate(-90 40 155)" text-anchor="middle">Diagnosis</text>
  <text x="95" y="135" class="row-label">S</text>
  <text x="95" y="195" class="row-label">D</text>

  <rect x="120" y="95" width="450" height="120" fill="none" stroke="#999" stroke-width="1"></rect>
  <line x1="120" y1="155" x2="570" y2="155" stroke="#999" stroke-width="1"></line>
  <line x1="270" y1="95" x2="270" y2="215" stroke="#999" stroke-width="1"></line>
  <line x1="420" y1="95" x2="420" y2="215" stroke="#999" stroke-width="1"></line>

  <line x1="130" y1="130" x2="618" y2="130" stroke="#e8923f" stroke-width="2" marker-end="url(#arrow-orange)"></line>
  <line x1="130" y1="190" x2="618" y2="190" stroke="#e8923f" stroke-width="2" marker-end="url(#arrow-orange)"></line>

  <rect x="630" y="60" width="55" height="190" fill="none" stroke="#e8923f" stroke-width="1.5"></rect>
  <text x="657" y="155" class="callout-text" font-size="12" transform="rotate(-90 657 155)" text-anchor="middle">Main effect of diagnosis</text>

  <line x1="195" y1="95" x2="195" y2="282" stroke="#2c6e73" stroke-width="2" marker-end="url(#arrow-teal)"></line>
  <line x1="345" y1="95" x2="345" y2="282" stroke="#2c6e73" stroke-width="2" marker-end="url(#arrow-teal)"></line>
  <line x1="495" y1="95" x2="495" y2="282" stroke="#2c6e73" stroke-width="2" marker-end="url(#arrow-teal)"></line>

  <rect x="120" y="290" width="450" height="50" fill="none" stroke="#2c6e73" stroke-width="1.5"></rect>
  <text x="345" y="320" class="callout-text">Main effect of drug</text>
</svg>
</div>
<p>This diagram is a visual way to see what “averaging over the other factor” actually means. The orange arrows run horizontally, straight across the Schizophrenia (S) row and straight across the Depression (D) row, collapsing across all three drug columns to ask whether the diagnosis groups differ. That collapsing across drug is exactly what computing the diagnosis marginal means does, and it is why it is called the main effect of diagnosis: it looks only at the two row averages, ignoring which drug a person received.</p>
<p>The teal arrows do the same thing in the other direction. They run vertically straight down each drug column, collapsing across both rows of diagnosis, to ask whether the three drugs differ from one another. That is the main effect of drug: three column averages, ignoring which diagnosis group a person belonged to.</p>
<p>Neither arrow ever looks inside a single cell. That is the key distinction between a main effect and the cell-level detail you will need once an interaction is in play: a main effect only ever compares marginal averages, never individual cell means.</p>
<p>The interaction effect can be understood better with this table.</p>
<div class="concept-diagram">
<svg width="100%" viewbox="0 0 760 270" xmlns="http://www.w3.org/2000/svg" style="display: block; margin: 0 auto;">

  <text x="405" y="30" class="title">Interaction effect</text>

  <text x="215" y="75" class="header">1</text>
  <text x="405" y="75" class="header">2</text>
  <text x="595" y="75" class="header">3</text>

  <text x="40" y="160" class="axis-label" transform="rotate(-90 40 160)" text-anchor="middle">Diagnosis</text>
  <text x="95" y="130" class="row-label">S</text>
  <text x="95" y="200" class="row-label">D</text>

  <rect x="120" y="90" width="190" height="70" class="fill-pink"></rect>
  <rect x="310" y="90" width="190" height="70" class="fill-pink"></rect>
  <rect x="500" y="90" width="190" height="70" class="fill-pink"></rect>

  <rect x="120" y="160" width="190" height="70" class="fill-green"></rect>
  <rect x="310" y="160" width="190" height="70" class="fill-green"></rect>
  <rect x="500" y="160" width="190" height="70" class="fill-green"></rect>

  <rect x="120" y="90" width="570" height="140" fill="none" stroke="#999" stroke-width="1"></rect>
  <line x1="120" y1="160" x2="690" y2="160" stroke="#999" stroke-width="1"></line>
  <line x1="310" y1="90" x2="310" y2="230" stroke="#999" stroke-width="1"></line>
  <line x1="500" y1="90" x2="500" y2="230" stroke="#999" stroke-width="1"></line>

  <text x="405" y="113" class="cell-text">Effect of drug (Schizophrenia)</text>
  <rect x="388" y="150" width="34" height="20" fill="#ffffff" stroke="#999" stroke-width="0.5"></rect>
  <text x="405" y="164" class="cell-text">vs</text>
  <text x="405" y="205" class="cell-text">Effect of drug (Depression)</text>

</svg>
</div>
<p>This diagram shows what an interaction actually compares: not raw scores, but the size of an effect. The pink row asks how much Drug 2 changes the outcome relative to Drug 1 within Schizophrenia. The green row asks that same question within Depression. The interaction effect is the <em>VS</em> comparison sitting on the line between them, whether that drug effect is the same size in both diagnosis groups, or whether it differs. If the Schizophrenia effect and the Depression effect are roughly equal, there is no interaction. In that case, the lines drawn this way would look the same in both rows. If they differ, as they do in our dataset, the effect of drug genuinely depends on diagnosis, and a single marginal mean comparing Drug 1 to Drug 2 averaged across both diagnosis groups would blur together two very different stories.</p>
</section>
</section>
<section id="running-the-omnibus-test-in-spss" class="level2">
<h2 data-anchor-id="running-the-omnibus-test-in-spss">5. Running the Omnibus Test in SPSS</h2>
<p>The first thing you do in a two-way ANOVA is to run the <em>omnibus</em> test. We use the term “omnibus” because this test includes the interaction and the main effects in one.</p>
<p>The general MANOVA syntax for a two-way between-subjects design looks like this:</p>
<pre><code>MANOVA
    score BY diagnosis (1 2) drug (1 3)
   /NOPRINT PARAM(ESTIM)
   /PRINT CELLINFO(MEANS)
   /METHOD=UNIQUE
   /ERROR=WITHIN
   /DESIGN.</code></pre>
<p>Line by line:</p>
<ul>
<li><code>score BY diagnosis (1 2) drug (1 3)</code> tells SPSS that <strong>score</strong> is the dependent variable, <strong>diagnosis</strong> is the first factor with levels coded 1 through 2, and <strong>drug</strong> is the second factor with levels coded 1 through 3.</li>
<li><code>/NOPRINT PARAM(ESTIM)</code> suppresses the parameter estimate table. We are not asking for it here because the default <code>/DESIGN</code> does not produce contrast estimates worth reading. We will turn this back on once we add contrasts later, but for now it clutters the output.</li>
<li><code>/PRINT CELLINFO(MEANS)</code> requests the cell means and standard deviations table. This isn’t necessary but is helpful.</li>
<li><code>/METHOD=UNIQUE</code> tells SPSS to partition the sums of squares using the unique (Type III-equivalent) method, which is the standard choice and the only sensible one once cell sizes are unequal. This is important to include.</li>
<li><code>/ERROR=WITHIN</code> specifies that <span class="math inline">\(MS_{within}\)</span> (the within-cells mean square) is the error term for every <span class="math inline">\(F\)</span> test in the design. There are other options for this that you can use in different situations, such as a seperate error term, but we aren’t going to cover these.</li>
<li><code>/DESIGN.</code> with nothing after it requests the default full factorial model. SPSS will automatically test the diagnosis main effect, the drug main effect, and the diagnosis by drug interaction. This is equivalent to writing it out explicitly: <code>/DESIGN diagnosis, drug, diagnosis by drug.</code> But, by default, we don’t need to write this out.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/twoway-omnibus.png" class="img-fluid figure-img" alt="SPSS MANOVA output showing cell means and standard deviations by diagnosis and drug, followed by the omnibus ANOVA summary table with sums of squares, degrees of freedom, mean squares, F values, and significance for diagnosis, drug, and the diagnosis by drug interaction"></p>
<figcaption>Cell means and omnibus ANOVA table for the diagnosis by drug design</figcaption>
</figure>
</div>
<p>When looking at the output for the omnibus test results, we can see that the main effect of diagnosis is not significant, the main effect of drug is significant, and the interaction is significant.</p>
<p>When the interaction is significant, that’s usually the result worth chasing first. It means the effect of Drug is not the same across the two diagnosis groups, so the main effect of Drug describes an average pattern that may not hold for either group on its own. In fact, if your interaction is significant in a real experiment, you should ignore the main effects for the most part as they can’t be interpreted since marginalizing over the other factor is innapropriate.</p>
<p>For the rest of this lesson, though, we are going to treat each of these results as a separate hypothetical scenario so we can walk through every follow-up procedure on the same set of cell means. Think of it less as “here is what we did with this dataset” and more as “here is what you would do if your own data came back looking a certain way”</p>
</section>
<section id="choosing-your-follow-up-test-the-decision-tree" class="level2">
<h2 data-anchor-id="choosing-your-follow-up-test-the-decision-tree">6. Choosing Your Follow-Up Test: The Decision Tree</h2>
<p>Which follow-up test is appropriate depends entirely on which effects came back significant. Below is a flow chart to help you make these decisions. Start at the top of the chart by assessing whether your interaction is significant or not. If the interaction is not significant, go to the right to examine the main effects. If the interaction is significant, then go to the left to examine the simple effects.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    A[Is the A x B&lt;br/&gt;interaction significant?] --&gt;|Yes| B[Test simple effects&lt;br/&gt;OR interaction contrasts]
    A --&gt;|No| F[Is the main effect&lt;br/&gt;of A significant?]
    B --&gt; C[Simple effects: effect of&lt;br/&gt;one factor at each level&lt;br/&gt;of the other]
    B --&gt; D[Interaction contrasts: does&lt;br/&gt;a specific contrast on A&lt;br/&gt;depend on B?]
    C --&gt;|Significant&lt;br/&gt;simple effect| E[Cell means comparisons&lt;br/&gt;within that slice]
    F --&gt;|Yes| G[Individual contrasts&lt;br/&gt;for marginal means]
    F --&gt;|No| H[Is the main effect&lt;br/&gt;of B significant?]
    H --&gt;|Yes| I[Individual contrasts&lt;br/&gt;for marginal means]
    H --&gt;|No| J[Stop, nothing&lt;br/&gt;further to test]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>The same logic applies symmetrically if you are more interested in simple effects of A within levels of B rather than B within levels of A; you would just swap which factor is held fixed.</p>
<p>In words: if the interaction is not significant, you fall back to testing each main effect with marginal mean contrasts (covered next), exactly the way you tested contrasts among groups in Lesson 2. If the interaction is significant, marginal means become misleading (they average over a relationship that is not constant), so you instead test simple effects within each level of the other factor (covered later), and if those are significant, you compare individual cell means within that level.</p>
</section>
<section id="marginal-mean-comparisons-no-interaction-significant-main-effect" class="level2">
<h2 data-anchor-id="marginal-mean-comparisons-no-interaction-significant-main-effect">7. Marginal Mean Comparisons (No Interaction, Significant Main Effect)</h2>
<p>Suppose the interaction were not significant, but the main effect of Drug were. Averaging over diagnosis, the three drug marginal means (6.750, 5.417, 9.292) differ significantly from one another. But we do not yet know which pairs of drugs differ. A significant omnibus main effect tells you that the marginal means are not all equal, the same way a significant omnibus one-way ANOVA tells you the group means are not all equal, without telling you which pairs are responsible.</p>
<p>To understand it, here are table representations of both possible directions of marginal mean we can comapare.</p>
<p>The marginal means of drug is given as: <img src="images/MM1.png" class="img-fluid" alt="Table showing diagnosis by drug cell means, with Drug 1 shaded blue, Drug 2 shaded purple, and Drug 3 shaded pink, and a row of marginal means below for each drug column"></p>
<p>The marginal means of diagnosis are given as:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/MM2.png" class="img-fluid figure-img" alt="Table showing diagnosis by drug cell means, with the Schizophrenia row shaded yellow and the Depression row shaded red, and a marginal means column on the right showing 6.19 for Schizophrenia and 8.11 for Depression"></p>
<figcaption>Cell means table for the diagnosis marginal means, with the Schizophrenia row shaded yellow and the Depression row shaded red, and a marginal means column on the right</figcaption>
</figure>
</div>
<p>To find out, we build a contrast matrix for drug, the same way we built contrast matrices for groups back in Lesson 2, except now the contrasts are applied to the marginal means rather than to a single set of group means.</p>
<p>Both tables show the same cell means, the only thing that changes is which direction you collapse across. The first table averages straight down each drug column, ignoring diagnosis entirely, to give you the marginal means of drug: 6.75, 5.4165, and 9.2915. The second table averages straight across each diagnosis row, ignoring drug entirely, to give you the marginal means of diagnosis: 6.19 for Schizophrenia and 8.11 for Depression. A significant main effect tells you that the relevant set of marginal means is not all equal, but it stops there. It does not tell you which specific pair is responsible. That is exactly the gap contrasts are built to close.</p>
<p>To figure this out, like we would with an ordinary ANOVA, we use contrast testing to address specific questions. For instance, we can test whether Drug 1 differs from Drug 2, and tests it directly against those marginal means, the same logic from Lesson 2 applied here to averages across diagnosis rather than to raw group means. Once you have a significant main effect and want to know where the difference actually lives, the contrast syntax in the next section is how you get there.</p>
<section id="marginal-means-in-spss" class="level3">
<h3 data-anchor-id="marginal-means-in-spss">Marginal Means in SPSS</h3>
<p>Let’s say we want to compare the marginal means of Drug 1 against Drug 2 and Drug 3 in two pairwise comparisons. This corresponds to the table of marginal mean comparisons given as</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/MM-contrast1.png" class="img-fluid figure-img" alt="Table showing contrast for Drug 1 versus Drug 2, marginalizing across the diagnosis groups."></p>
<figcaption>Marginal mean comparisons for Drug 1 versus Drug 2</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/MM-contrast2.png" class="img-fluid figure-img" alt="Table showing contrast for Drug 1 versus Drug 3, marginalizing across the diagnosis groups."></p>
<figcaption>Marginal mean comparisons for Drug 1 versus Drug 3</figcaption>
</figure>
</div>
<p>The SPSS syntax for that would be</p>
<pre><code>MANOVA
    score BY diagnosis (1 2) drug (1 3)
   /NOPRINT PARAM(ESTIM)
   /PRINT CELLINFO(MEANS)
   /METHOD=UNIQUE
   /ERROR=WITHIN
   /CONTRAST(drug) = special (1  1  1
                               1 -1  0
                               1  0 -1)
   /DESIGN = drug(1), drug(2), diagnosis, diagnosis BY drug.</code></pre>
<p>A few things to notice here:</p>
<ul>
<li>The contrast matrix’s first row, <code>1 1 1</code>, is always the equal-weighting row that defines the grand mean contribution; it is not itself tested. The second row, <code>1 -1 0</code>, compares Drug 1 to Drug 2. The third row, <code>1 0 -1</code>, compares Drug 1 to Drug 3.</li>
<li>On the <code>/DESIGN</code> line, <code>drug(1)</code> refers to the first contrast of drug (1, -1, 0), and <code>drug(2)</code> refers to the second contrast. It’s easy to remember this as the number in the parenthese just references the order of the contrasts you specified.</li>
<li>Notice that diagnosis and diagnosis BY drug are also listed on the design line, even though we are not directly interested in testing them right now. This matters here specifically because our dataset is <strong>unbalanced</strong> (i.e., the sample sizes for each group are not equal). The /DESIGN line tells SPSS the full model to fit, and with unequal cell sizes, the drug contrasts are no longer orthogonal to the other effects in the model. If we left diagnosis and diagnosis BY drug off, SPSS would not be controlling for them, and our test of the drug contrasts would not match the omnibus analysis we already ran. With a <strong>balanced</strong> design (i.e., each group has the same sample size), this would not matter, since all the effects are mutually orthogonal and dropping unrelated terms would not change the result, the same reasoning you saw with the equal-n exception in the simple effects section later in this lesson. But since our cell sizes are unequal, the safest habit, and the one we will use throughout this lesson, is to include every effect that should remain in the model, not just the one you are testing.</li>
</ul>
<p>The SPSS output for this chunk of code is given as</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/MM-output.png" class="img-fluid figure-img" alt="SPSS MANOVA parameter estimate table showing the coefficient, standard error, t-value, and significance for the DRUG(1) and DRUG(2) contrasts testing Drug 1 versus Drug 2 and Drug 1 versus Drug 3 marginal means"></p>
<figcaption>Parameter estimates for the drug(1) and drug(2) marginal mean contrasts</figcaption>
</figure>
</div>
<p>From this output, you only want to focus on the lines that say DRUG(1) and DRUG(2), sa these are the outputs for our contrasts. From this output, we can see (via the <span class="math inline">\(F\)</span> test in the top table or the <span class="math inline">\(t\)</span> tests in the bottom tables) that both contrasts are not significant. So we would fail to reject that the marginal means of Drug 1 is not different than Drug 2 or Drug 3.</p>
<p>If you recall from the contrast lesson, if you wish to test more marginal mean contrasts, you will need multiple MANOVA chunks of code.</p>
<p>Also, keep in mind here that we are doing multiple comparisons, so we need to think about Type I error corrections. I planned these contrasts initially, and these are just two pairwise comparisons, so following the Multiple Comparison lesson, I could use Bonferroni or Tukey after checking for the critical values, though since there are only three groups, Bonferroni is likely the more powerful option (review that lesson if needed).</p>
</section>
</section>
<section id="simple-effects-significant-interaction" class="level2">
<h2 data-anchor-id="simple-effects-significant-interaction">8. Simple Effects (Significant Interaction)</h2>
<p>Now suppose the interaction is significant instead (which happens to be the situation that actually describes our dataset). Marginal means are no longer the right thing to test, because averaging Drug 2’s score across both diagnosis groups blends together a low score in Depression and a relatively high score in Schizophrenia. That average does not describe either group well.</p>
<p>Instead, we test the <strong>simple effect</strong> of Drug separately within each level of Diagnosis. This is conceptually just running two separate one-way ANOVAs of drug, one within Schizophrenia and one within Depression, except we do it inside a single MANOVA call so that both tests share the same pooled error term, <span class="math inline">\(MS_{within}\)</span>, from the full design.</p>
<blockquote class="blockquote">
<p>Note: It is possible to do Simple Effects test as distinct one-way ANOVAs by running an ANOVA for depression scores across the drug groups and another ANOVA for schizophrenia scores across the drug groups. However, this will be much less powerful, since it is not using the <span class="math inline">\(MS_{within}\)</span> from the two-way ANOVA. Look back at the pie chart above, and see that using the two-way method means we are controlling for more error and getting more powerful results!</p>
</blockquote>
<p>There are many possible simple effects for our model. The simple effects for diagnosis can be represented by these tables</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/MM-output.png" class="img-fluid figure-img" alt="This table shows the two simple effects for each diagnosis. On top is the simple effect of drug within schizophrenia represented by the colored line (there should be distinct colors for each cell, but I didn't get that to work for this table. The table on the bottom shows the simple effect of drug within depression by the colored groups. The means at the end of the simple effect rows represent the marginal mean."></p>
<figcaption>Table of the two simple effect comparisons within each diagnosis level</figcaption>
</figure>
</div>
<p>The null hypotheses of simple effects is that the means of factor A within a single level of factor B do not differ from one another. So for example in the first table above, the null hypothesis is that the drug means of 4, 9.333, and 5.25 within schizophrenia do not differ. The alternative is that at least one of these means will be significantly different than the others.</p>
<p>In addition of these simple effects of diagnosis, there are also three simple effects for the drug groups that compare schizophrenia against depression within each individual drug, but we won’t cover these.</p>
<section id="simple-effects-in-spss" class="level3">
<h3 data-anchor-id="simple-effects-in-spss">Simple Effects in SPSS</h3>
<p>We will be sticking with the simple effects within diagnosis. In SPSS, simple effects do not require a custom contrast matrix. They are requested with a <code>W</code> (for “within”) on the design line:</p>
<pre><code>MANOVA
    score BY diagnosis (1 2) drug (1 3)
   /NOPRINT PARAM(ESTIM)
   /PRINT CELLINFO(MEANS)
   /METHOD=UNIQUE
   /ERROR=WITHIN
   /DESIGN = drug W diagnosis(1), drug W diagnosis(2), diagnosis.</code></pre>
<p>Here <code>drug W diagnosis(1)</code> means “test the effect of drug within the first level of diagnosis (Schizophrenia),” and <code>drug W diagnosis(2)</code> means the same thing within the second level (Depression). Notice the <code>(1)</code> and <code>(2)</code> are to the <em>right</em> of the <code>W</code> here, so they refer to levels of diagnosis, not to rows of a contrast matrix. This is a common point of confusion. So make sure you understand that when a parenthese number comes after a <code>W</code> in the design line, it is referring to a specific level of that variable. In all other cases, it is discussing a contrast.</p>
<p>We also keep <code>diagnosis</code> on the design line becasue our data is not balanced (see above).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/2way-simple.png" class="img-fluid figure-img" alt="SPSS MANOVA output showing the simple effect of drug tested separately within diagnosis level 1 and diagnosis level 2, with sums of squares, degrees of freedom, mean squares, F values, and significance for each"></p>
<figcaption>Simple effects of drug within each level of diagnosis</figcaption>
</figure>
</div>
<p>Both simple effects are significant at the level of <span class="math inline">\(\alpha = .05\)</span>. So we can conclude that the drug an individual takes matters within Schizophrenia as well as Depression. But just like a main effect, a significant simple effect only tells us that the three drug means differ somewhere within that diagnosis group, not which specific drugs differ. That is the next step.</p>
</section>
</section>
<section id="cell-mean-comparisons-within-simple-effects" class="level2">
<h2 data-anchor-id="cell-mean-comparisons-within-simple-effects">9. Cell Mean Comparisons Within Simple Effects</h2>
<p>If a simple effect comes back significant, meaning that there is <em>a</em> difference amongst the means within a one of the diagnoses, the natural next step is to compare specific drug pairs within that diagnosis level. This combines the two techniques you have already seen: a contrast matrix applied within a specific level of the other factor (from simple effects testing).</p>
<p>There are a many number of possible cell mean comparisons. For example, within either depression or schizophrenia, we want to compare Drug 1 against Drug 2. These are two cell mean comparisons (Drug 1 v 2 within depression, and Drug 1 v 2 within schizophrenia). We can see what this would be like in the following table</p>
<p><img src="images/2way-cell1.png" class="img-fluid" alt="Table showing cell mean comparison contrast for Drug 1 versus Drug 2 within both schizophrenia and depression. The colors corespond to the means that are being compared."> Of course, there could be many many more. For example, we could do cell mean comparisons of Diagnosis just within Drug 1. However, if you notice, there are only two means within Diagnosis. So by nature, comparing both groups is the only cell mean comparison. This, as a matter in fact, is exactly what the simple effect for Drug 1 is already doing. Therefore, cell mean comparisons can only be done when the number of groups is greater than 2. This goes for all contrasts too, but it is helpful to keep that in mind now because the SPSS syntax for cell mean comparisons can get a bit confusing.</p>
<section id="cell-mean-comparisons-in-spss" class="level3">
<h3 data-anchor-id="cell-mean-comparisons-in-spss">Cell Mean Comparisons in SPSS</h3>
<p>As there are many types of cell mean comparisons, there are many ways to specify the syntax. As a rule, cell mean comparison syntax consists of two pieces:</p>
<ol type="1">
<li><p>A contrast piece (the cells you are comparing)</p></li>
<li><p>A simple effects piece (the specific levels you are testing on)</p></li>
</ol>
<p>Once you understand this, the process of specifying the code in SPSS will hopefully become a bit more inuitive.</p>
<p>Let’s say we want to compare Drug 1 against Drug 2, and we want to compare Drug 2 against Drug 3 (the contrast piece). Let’s say we want to do this within both levels of diagnosis (the simple effects piece). Visually, these four cell mean comparisons are described in the following table.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/2way-cell2.png" class="img-fluid figure-img" alt="Table showing cell mean comparison contrast for Drug 1 versus Drug 2 and Drug 2 versus Drug 3 within both schizophrenia and depression. The colors corespond to the means that are being compared."></p>
<figcaption>Four Cell Mean Comparisons for Drug 1 vs Drug 2 and Drug 2 vs Drug 3</figcaption>
</figure>
</div>
<p>The SPSS syntax is as follows.</p>
<pre><code>MANOVA
    score BY diagnosis (1 2) drug (1 3)
   /NOPRINT PARAM(ESTIM)
   /PRINT CELLINFO(MEANS)
   /METHOD=UNIQUE
   /ERROR=WITHIN
   /CONTRAST(drug) = special (1  1  1
                               1 -1  0
                               0  1 -1)
   /DESIGN = drug(1) W diagnosis(1), drug(2) W diagnosis(1),
             drug(1) W diagnosis(2), drug(2) W diagnosis(2),
             diagnosis.</code></pre>
<p>The contast piece is specified in the matrix’s second row (<code>1 -1 0</code>) compares Drug 1 to Drug 2, and the third row (<code>0 1 -1</code>) compares Drug 2 to Drug 3. This is akin to any contrast comparison. What is unique now is that within the design line, <strong>for each contrast</strong> we must specify we are testing them within each level of diagnosis. So, <code>drug(1) W diagnosis(1)</code> means “the first contrast (Drug 1 vs Drug 2) within the first level of diagnosis (schizophrenia),” and <code>drug(2) W diagnosis(2)</code> means “the second contrast (Drug 2 vs Drug 3) within the second level of diagnosis (depression). This follows suit for the others.</p>
<p>To help with making the syntax, recall what I said before. If you see a number in a parentheses <em>after</em> the <code>W</code>, it is talking about a specific level of the variable. Anywhere else, it is talking about a contrast.</p>
<p>It is necessary that you include all pieces of each cell mean comparison or else the sum of squares won’t get partitioned correctly and your results will be incorrect. So it is important you figure out how many cell means you are actually comparing. Finally, since our data is not balanced (not equal in group sample size), we must include the factor we are looking within (<code>diagnosis</code>) in the design line to let SPSS know we must treat this as unbalanced. If you have equal group sample size, you don’t need to do this.</p>
<p>The output for these tests is given below</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/2way-celloutput.png" class="img-fluid figure-img" alt="SPSS MANOVA parameter estimate table showing the four pairwise drug contrasts tested within each diagnosis level, with coefficients, standard errors, t-values, and significance"></p>
<figcaption>Output for the four cell mean comparisons</figcaption>
</figure>
</div>
<p>You can either look at the <span class="math inline">\(F\)</span> test table at the top or the get the <span class="math inline">\(t\)</span> statistics below to check significance. Please keep in mind what you labeled as each contrast and what levels represent yout <code>(1)</code> and <code>(2)</code> specification because you will have to find them on the output and interpret them correctly.</p>
<p>All four comparisons are significant in this example at the <span class="math inline">\(\alpha=.05\)</span> level. This means that Drug 1 and 2 differ within depression and schizophrenia, and Drug 2 and 3 also differ within depression and schizophrenia.</p>
<p>If you want to do more cell mean comparisons that are allowed in your contrast matrix, you will need to run another MANOVA chunk.</p>
</section>
</section>
<section id="type-i-error-correction-for-simple-effects-and-cell-mean-comparisons" class="level2">
<h2 data-anchor-id="type-i-error-correction-for-simple-effects-and-cell-mean-comparisons">10. Type I Error Correction for Simple Effects and Cell Mean Comparisons</h2>
<p>Just like all other types of follow up tests, you should consider Type I error corrections for simple effects and their cell mean comparisons. In fact, the number of tests you will be looking at will escalate quickly, so controlling for Type I error becomes even more pertinent. Look at the Multiple Comparison lesson if you are confused.</p>
<p>Unfortunately, when working with simple effects, there is not a clean and easy solution to controlling for Type I error rates, and Type I error control can get a bit more abstract, and honestly from my experience teaching this course, this is probably the most confusing part of the whole course for many people.</p>
<p>There are two main methods you can choose to go about it, and they differ in what you treat as a “family”.</p>
<blockquote class="blockquote">
<p>Recall that a “family” in testing is a set of comparisons that you group together for purposes of error control. The whole point of correcting for Type I error, whether by Bonferroni, Tukey, or Scheffe, is to control the probability of making at least one false positive across an entire family of tests, not just within any single test on its own. Everything depends on how you draw the boundary around that family, since the same set of tests can be split into one large family or several smaller ones, and each choice leads to a different correction.</p>
</blockquote>
<p>Previously, we talked about “experimentwise” error, which treats the whole experiment as one family. When working with simple effects, the family is the simple effects rather than the whole experiment. This means that you do not incorporate the omnibus tests at all (main effects or interaction) as a factor when controlling for Type I error. However, there are two different ways you can treat the simple effects as a family.</p>
<section id="treating-simple-effects-as-one-family" class="level3">
<h3 data-anchor-id="treating-simple-effects-as-one-family">Treating Simple Effects as One Family</h3>
<p>The standard approach is to treat all the simple effects of a single factor as a single family. For instance, we would treat the two simple effects of Drug across both levels of Diagnosis as a single family of related questions. In this scenario, you are really asking one bigger question, “does the type of drug an individual receives matter, and does that depend on their diagnosis,” and the two simple effect tests are two pieces of answering it. Under this view, you split your overall alpha across the b tests in the family, where b is the number of levels of the factor you are holding fixed:</p>
<p><span class="math display">\[\alpha_{per\,test} = \frac{\alpha}{b}\]</span></p>
<p>In our case, <span class="math inline">\(b = 2\)</span> as there are 2 levels of Diagnosis. So we get <span class="math inline">\(\alpha/2 = .025\)</span> per simple effect test. If you were instead testing simple effects of Diagnosis within each of the 3 drug levels, you would split alpha three ways, <span class="math inline">\(.05/3 \approx .017\)</span>.</p>
<p>When you move on to cell mean comparisons, you then control for Type I error based on this corrected <span class="math inline">\(\alpha\)</span> level. That is, all decisisions and adjustment are made from <span class="math inline">\(\alpha_{per~test}\)</span> as opposed to just <span class="math inline">\(\alpha = .05\)</span>. In our example, our decisions of the cell mean comparisons within the simple effects of the diagnosis levels should be using <span class="math inline">\(\alpha = .025\)</span> as the cut off. If you go back above to the SPSS in Section 9, you might actually notice the comparisons of Drug 1 vs Drug 2 in both depression and schizophrenia would no longer be significant.</p>
<p>However, it doesn’t stop there. That would be the case only if we were looking at a single cell mean comparison. But just like all contrasts, we must decide on Bonferroni vs Tukey vs Scheffé based on the criteria discusses in the Multiple Comparisons lesson. The big caveat is that the decisiions made for those methods is based on <span class="math inline">\(\alpha_{per~test}\)</span> <em>not</em> <span class="math inline">\(\alpha = .05\)</span>.</p>
<p>If you recall, the Bonferroni corrected <span class="math inline">\(\alpha\)</span> is</p>
<p><span class="math display">\[\alpha_{Bonferroni} = \frac{\alpha}{C}\]</span> where <span class="math inline">\(C\)</span> is the number of comparisons. When correcting for cell mean comparisons while treating all simple effects as a single family, we would divide <span class="math inline">\(\alpha_{per~test}\)</span> by C. So for our example, we would divide our <span class="math inline">\(\alpha_{per~test}=.025\)</span> by 4 as we are looking at 4 comparisons. This gets us a corrected Bonferroni alpha of</p>
<p><span class="math display">\[\alpha_{Bonferroni} = \frac{.025}{4}=.00625\]</span> In a nutshell, whenever you are using the basic <span class="math inline">\(\alpha = .05\)</span> for your Type I error control methods (like when calculating critical values), you need to use <span class="math inline">\(\alpha_{per~test}\)</span>.</p>
<p>As one can see, this starts to make the rejection criteria get very small very fast. Well, that is intentional. If you are doing a multi-way ANOVA and are testing <em>everything</em>, then you are just asking for a Type I error. Realistically, you should be planning only to test a certain limited number of contrasts. That way, you don’t need ridiculously low <span class="math inline">\(p\)</span> values to reject anything.</p>
<p>This is just one method of doing Type I error control for simple effects, however.</p>
</section>
<section id="treating-simple-effects-as-seperate-families" class="level3">
<h3 data-anchor-id="treating-simple-effects-as-seperate-families">Treating Simple Effects as Seperate Families</h3>
<p>The alternative is to argue that the simple effect within Schizophrenia and the simple effect within Depression are not really part of the same inferential claim, they are two distinct, separately motivated questions about two distinct populations, and a Type I error in one has no bearing on your confidence in the other. Under this view each test gets its own full <span class="math inline">\(\alpha = .05\)</span> uncorrected. So there is no need of getting an <span class="math inline">\(\alpha_{per~test}\)</span>. Thus, you can complete sidestep using different criteria in your Bonferroni/Tukey/Scheffé tests for the cell mean comparisons, and you can use just <span class="math inline">\(\alpha = .05\)</span> like normal instead. This has the immediate benefit of being much simpler.</p>
<p>This method is defensible, but it needs to be a deliberate choice you can justify, not a default you are choosing for convenience. In our example, if you cannot articulate why the two diagnosis groups represent genuinely separate research questions rather than two parts of one factorial story, the one-family, <span class="math inline">\(\alpha_{per~test}\)</span> approach is the safer and more conventional default.</p>
<p>SPSS doesn’t have easy ways to do Tukey with MANOVA, but you should be able to do the Bonferroni and Scheffé methods in the MANOVA functions as discussed in the Multiple Comparisons lesson. For Tukey, you will most likely need to hand calculate some values.</p>
<p>In general for higher order ANOVAs than just one-way, it is good practice to <em>plan</em> tests you are interested in. This is to drastically reduce potential Type I error inflation. As a result, Bonferroni is often the best adjustment you can use in most scenarios.</p>
</section>
</section>
<section id="interaction-contrasts" class="level2">
<h2 data-anchor-id="interaction-contrasts">11. Interaction Contrasts</h2>
<p>Now we move on to our last piece of two-way ANOVA, interaction contrasts.</p>
<p>Cell mean comparisons answer “which specific cells differ,” but some researchers argue they can be misleading on their own, because a cell mean difference blends together main effect variation and interaction variation. It does not isolate the interaction parameter, <span class="math inline">\((\alpha\beta)_{jk}\)</span>, by itself.</p>
<p>An <strong>interaction contrast</strong> does exactly that. It is a contrast of contrasts: the difference between a cell mean contrast in one level of A and the same cell mean contrast in another level of A. If the two contrasts are identical, the interaction contrast is zero (no interaction for that comparison). If they differ, that difference is a pure estimate of an interaction parameter.</p>
<p>As a concrete example with our data, let’s say we want to know whether symptom improvement of Drug 1 vs Drug 2 differs between schizophrenia and depression. It is possible that Drug 1 and Drug 2 differ from one another, however it is possible that Drug 1 decreases symptoms in schizophrenia and increases them in depression, whereas Drug 2 increases symptoms in schizophrenia but decreases them in depression. Basic cell mean comparisons won’t give you insight on this question.</p>
<p>This interaction contrast is represented in the table below</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/2way-int.png" class="img-fluid figure-img" alt="This table shows the two comparisons of Drug 1 vs Drug 2 against depression and schizophrenia. The colors represent the specific cell mean comparisons. The numbers in the center of the circle represent the mean differences being compared across the levels of diagnosis."></p>
<figcaption>Interaction Contrast of Drug 1 vs Drug 2 across Diagnosis</figcaption>
</figure>
</div>
<p>Essentially, each circle is its own simple comparison, Drug 1 minus Drug 2, computed separately within each diagnosis group. Within Schizophrenia, that difference is <span class="math inline">\(4 - 9.333 = -5.33\)</span>. Within Depression, that same comparison comes out to <span class="math inline">\(9.5 - 1.5 = 8\)</span>. Neither of those numbers by itself answers our question. They are just two ordinary cell mean comparisons. What we actually want to know is whether those two differences are themselves different from each other, whether the Drug 1 vs Drug 2 gap looks the same regardless of diagnosis, or whether it flips or changes size depending on which diagnosis group you are looking at.</p>
<p>That is exactly what the interaction contrast computes: a difference of differences.</p>
<p><span class="math display">\[(\bar{Y}_{schiz,1} - \bar{Y}_{schiz,2}) - (\bar{Y}_{dep,1} - \bar{Y}_{dep,2}) = -5.33 - 8 = -13.33\]</span></p>
<p>A value of zero here would mean the Drug 1 vs Drug 2 comparison is identical across diagnosis groups, aka the difference in benefits of Drug 1 vs Drug 2 is exactly the same for people with schizophrenia and people with depression. In this case, we could probably prescribe medication the same for individuals with either.</p>
<p>However, the further this contrast value sits from zero, the more the size (or direction) of the drug comparison depends on diagnosis. A value of <span class="math inline">\(-13.33\)</span> is a large gap, consistent with what the raw numbers already hint at: Drug 1 outperforms Drug 2 within Schizophrenia, while the opposite is true within Depression, exactly the kind of crossed pattern that a single cell mean comparison could never reveal on its own.</p>
<p>For another visual representation, here is a bar graph of the two groups.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/2way-intbar.png" class="img-fluid figure-img" alt="Bar graph showing cell means for Schizophrenia and Depression across Drug 1, Drug 2, and Drug 3. A line connects the Schizophrenia means across Drug 1 and Drug 2, and a separate line connects the Depression means across the same two drugs. The two lines cross between Drug 1 and Drug 2, visually showing the opposite direction of the drug effect across diagnosis groups."></p>
<figcaption>Bar graph of cell means by drug, split by diagnosis, with crossing lines connecting Drug 1 to Drug 2 within each diagnosis group</figcaption>
</figure>
</div>
<p>The table gave you the number, <span class="math inline">\(-13.33\)</span>. This chart gives you the shape behind it. An interaction contrast is essentially a comparison of slopes, and the blue line rising while the orange line falls is what a large, significant interaction contrast looks like when drawn out, two simple effects that are not just both present but pointing in opposite directions. Notice Drug 3 sits outside this picture entirely, since this particular contrast was built only to compare Drug 1 against Drug 2. Basically, the takeaway here is that we can see that Drug 1 vs 2 clearly have different effects that depend on the type of diagnosis the individual has.</p>
<section id="interaction-contrasts-in-spss" class="level3">
<h3 data-anchor-id="interaction-contrasts-in-spss">Interaction Contrasts in SPSS</h3>
<p>Interaction contrasts are requested by specifying two contrasts and seperating them with <code>BY</code> on the design line, which multiplies the coefficients from the two factors’ contrast matrices together. The syntax for our example is</p>
<pre><code>MANOVA
    score BY diagnosis (1 2) drug (1 3)
   /NOPRINT PARAM(ESTIM)
   /PRINT CELLINFO(MEANS)
   /METHOD=UNIQUE
   /ERROR=WITHIN
   /CONTRAST(diagnosis) = special (1  1
                                    1 -1)
   /CONTRAST(drug) = special (1  1  1
                               1 -1  0
                               1  0 -1)
   /DESIGN = drug(1) BY diagnosis(1), drug(2) BY diagnosis(1),
             drug, diagnosis.</code></pre>
<p>We have two contrast chunks, one for <code>drug</code>, which is the Drug 1 vs Drug 2 comparison we are interest in. I also threw in Drug 1 vs Drug 3 as an additional comparison because we must include one more. For <code>diagnosis</code> there was only one possible comparison we could make, which is just schizophrenia vs depression. One could imagine in a scenario where we introduce a third diagnosis, like general anxiety disorder, then we might need to specify in this <code>/CONTRAST(diagnosis)</code> line that we are only comparing schizophrenia and depression, but we are not looking at anxiety. In contexts where you only have 2 levels of a factor, however, there is only one possible comparisons.</p>
<p>In the <code>/DESIGN</code> line, we have to call the specific interactions by specifying the contrast against the other.</p>
<p><code>drug(1) BY diagnosis(1)</code> tests whether the Drug 1 vs Drug 2 difference is the same in Schizophrenia as it is in Depression:</p>
<p><span class="math display">\[(4.000 - 9.333) - (9.500 - 1.500) = -5.333 - 8.000 = -13.333\]</span></p>
<p><code>drug(2) BY diagnosis(1)</code> tests whether the Drug 1 vs Drug 3 difference is the same across diagnosis groups:</p>
<p><span class="math display">\[(4.000 - 5.250) - (9.500 - 13.333) = -1.250 - (-3.833) = 2.583\]</span></p>
<p>In this case, since there is no <code>W</code> anywhere, all numbered parenthese represent contrasts: <code>drug(1)</code> is Drug 1 vs Drug 2, <code>drug(2)</code> is Drug 1 vs Drug 3, and <code>diagnosis(1)</code> is schizophrenia vs depression. Including the <code>BY</code> inbetween the contrasts lets SPSS know we want to see their interaction.</p>
<p>Lastly, since we have unbalanced data (non-equal group sample sizes), we need to include the factors in the design line as well, with <code>drug</code> and <code>diagnosis</code>. If your data is balanced, this is not necessary.</p>
<p>The output for this SPSS code is given below:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/2way-intoutput.png" class="img-fluid figure-img" alt="SPSS MANOVA parameter estimate table showing the two interaction contrasts testing whether the Drug 1 versus Drug 2 difference and the Drug 1 versus Drug 3 difference are consistent across diagnosis groups"></p>
<figcaption>Interaction contrast output</figcaption>
</figure>
</div>
<p>From this, we can conclude the Drug 1 vs Drug 2 pattern is significantly different across diagnosis groups, but the Drug 1 vs Drug 3 pattern is not. Therefore, the way Drug 1 compares to Drug 2 genuinely depends on diagnosis, not just numerically but in a way that crosses direction entirely: Drug 1 outperforms Drug 2 in Schizophrenia, while Drug 2 outperforms Drug 1 in Depression. A clinician choosing between these two drugs would need to know the patient’s diagnosis before that choice means anything. The Drug 1 vs Drug 3 relationship, by contrast, behaves consistently enough across diagnosis groups that the interaction contrast cannot rule out a constant effect, so whatever advantage or disadvantage Drug 3 has relative to Drug 1 does not depend on which diagnosis group you are looking at.</p>
<p>A useful equivalence to notice: omnibus <code>diagnosis BY drug</code> in Section 5 had 2 degrees of freedom, exactly <span class="math inline">\((a-1)(b-1) = (2-1)(3-1) = 2\)</span>. Testing <code>drug(1) BY diagnosis(1)</code> and <code>drug(2) BY diagnosis(1)</code> together is the same thing as testing the full interaction omnibus, just broken into two separate single-degree-of-freedom pieces. The omnibus interaction test is the joint test of all possible interaction contrasts at once; an individual interaction contrast like <code>drug(1) BY diagnosis(1)</code> tests just one of them.</p>
<p>Interaction contrasts can be planned in advance, the same way any other planned contrast can, which means you are not required to wait for a significant omnibus interaction before testing one. If your hypothesis was specifically about whether two particular drugs behave differently across diagnosis groups, you can test that directly.</p>
<p>Finally, issues of Type I error must be considered, and you should treat them in a similar manner to the general contrasts.</p>
</section>
</section>
<section id="applying-this-to-your-assignment" class="level2">
<h2 data-anchor-id="applying-this-to-your-assignment">12. Applying This to Your Assignment</h2>
<p>The lab assignment the graduate students were supposed to follow is given below if you want to try yourself.</p>
<p>The assignment uses <strong>TwoWayBetween.sav</strong>, with Drug (Drug X, Drug Y, Drug Z) crossed with Feedback (Present, Absent). Every syntax pattern from this lesson carries over directly, you are just swapping <code>diagnosis</code> for <code>feedback</code> and adjusting level counts as needed. The templates below assume <code>feedback (1 2)</code> and <code>drug (1 3)</code>, with drug coded so that 1 = Drug X, 2 = Drug Y, 3 = Drug Z.</p>
<p><strong>Omnibus ANOVA:</strong></p>
<pre><code>MANOVA
    score BY feedback (1 2) drug (1 3)
   /NOPRINT PARAM(ESTIM)
   /PRINT CELLINFO(MEANS)
   /METHOD=UNIQUE
   /ERROR=WITHIN
   /DESIGN.</code></pre>
<p><strong>Marginal means of Drug X vs Drug Y, Drug X vs Drug Z, Drug Y vs Drug Z (Section 7 pattern):</strong> build a 3x3 special contrast matrix for drug with each pairwise row you need, and keep <code>feedback</code> and <code>feedback BY drug</code> on the design line alongside the drug contrast rows you are testing.</p>
<p><strong>Marginal means of Feedback Present vs Absent (Section 7 pattern):</strong> this is testing whether, averaging across all three drugs, the presence or absence of feedback changes the outcome on its own.</p>
<p><strong>Simple effects of Feedback within all levels of Drug, and simple effects of Drug within Feedback Absent (Section 8 pattern):</strong> use <code>feedback W drug(1)</code>, <code>feedback W drug(2)</code>, <code>feedback W drug(3)</code> for the first; use <code>drug W feedback(2)</code> alone (assuming Absent is coded 2) for the second, since you only need the one level.</p>
<p><strong>Drug X vs Drug Y within Feedback Present, and within Feedback Absent; Drug Y and Z vs Drug X within both feedback levels; Drug X and Z vs Drug Y within both feedback levels (Section 9 pattern):</strong> these are cell mean comparisons. Build a drug contrast matrix with the specific pairwise and complex comparisons you need, then list <code>drug(row) W feedback(1)</code> and <code>drug(row) W feedback(2)</code> for every row and every level on the design line.</p>
<p><strong>Test whether the effect of Drug X vs Drug Y is the same within Feedback Present and Absent, and the same for Drug Y vs Drug Z (Section 10 pattern):</strong> these are interaction contrasts. Build contrast matrices for both feedback and drug, then use <code>drug(row) BY feedback(1)</code> on the design line for each comparison.</p>
<p>As you work through each of these, repeat the image-placeholder pattern from this lesson (<code>images/5.8.png</code>, <code>images/5.9.png</code>, and so on) for each output you generate, with alt text describing what that particular output shows.</p>
</section>
<section id="summary" class="level2">
<h2 data-anchor-id="summary">13. Summary</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Situation</th>
<th>What to test</th>
<th>SPSS pattern</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Interaction not significant, a main effect is</td>
<td>Contrasts among the marginal means of that factor</td>
<td>Contrast matrix + factor level numbers on design line, other main effect and interaction kept on design line</td>
</tr>
<tr class="even">
<td>Interaction significant</td>
<td>Simple effects of one factor within each level of the other</td>
<td><code>W</code> with no contrast matrix needed</td>
</tr>
<tr class="odd">
<td>Simple effect significant</td>
<td>Cell mean comparisons within that level</td>
<td>Contrast matrix + <code>W</code> combined</td>
</tr>
<tr class="even">
<td>Testing whether a specific comparison’s size changes across the other factor</td>
<td>Interaction contrast</td>
<td>Contrast matrices for both factors + <code>BY</code></td>
</tr>
</tbody>
</table>
<p>Every one of these is still a full versus reduced model comparison underneath, just like every test in this series has been. The cell means model is the most general thing you can fit; main effects, interactions, simple effects, and interaction contrasts are all just different ways of asking which pieces of that full model you can remove without losing meaningful fit.</p>
</section>
<section id="discussion-questions" class="level2">
<h2 data-anchor-id="discussion-questions">Discussion Questions</h2>
<p><strong>Question 1: Does it matter what order the rows appear in the dataset?</strong></p>
<details>
<summary>
Click to reveal answer
</summary>
<p>No.&nbsp;MANOVA, like the regression-based models underlying it, treats each row as an independent observation. Sums of squares, means, and F values are computed from the full set of scores within each cell, not from the order those scores happen to appear in the file. Reordering the rows will not change any result.</p>
</details>
<hr>
<p><strong>Question 2: Does it matter whether diagnosis is coded as 0,1 or as 1,2?</strong></p>
<details>
<summary>
Click to reveal answer
</summary>
<p>No, as long as the coding is specified correctly in the syntax (for example <code>diagnosis (0 1)</code> instead of <code>diagnosis (1 2)</code>). The numbers are just labels for group membership. The F tests, sums of squares, and significance values will be identical either way; only the internal parameter labeling changes.</p>
</details>
<hr>
<p><strong>Question 3: Why don’t we know where the specific differences in a significant main effect are yet?</strong></p>
<details>
<summary>
Click to reveal answer
</summary>
<p>A significant omnibus main effect, just like a significant one-way ANOVA, only tells you that the marginal means are not all equal somewhere among the levels. It does not identify which specific pairs differ. That requires planned or post hoc contrasts among the marginal means, the same logic from Lesson 2 and Lesson 3 applied to marginal rather than raw group means.</p>
</details>
<hr>
<p><strong>Question 4: Would the answer to Question 3 be different if the factor had only 2 levels instead of 3?</strong></p>
<details>
<summary>
Click to reveal answer
</summary>
<p>Yes. With exactly 2 levels, the omnibus main effect test and the single possible pairwise comparison are the same test. There is only one way two means can differ, so a significant 2-level main effect already tells you which two means differ and in which direction. With 3 or more levels, multiple comparisons are possible, so a significant omnibus result no longer pins down which specific pair (or pairs) is responsible.</p>
</details>
<hr>
<p><strong>Question 5: If there was a significant main effect of Diagnosis (a 2-level factor), would we know which means of Diagnosis differ?</strong></p>
<details>
<summary>
Click to reveal answer
</summary>
<p>Yes, by the same logic as Question 4. With only two levels, the main effect test is equivalent to comparing the two levels directly, so significance immediately tells you that Schizophrenia and Depression differ, with the direction given by which marginal mean is larger.</p>
</details>
<hr>
<p><strong>Question 6: Could we just include <code>drug(1)</code> on the design line, if that is the only contrast we care about?</strong></p>
<details>
<summary>
Click to reveal answer
</summary>
<p>Only safely if the contrasts are orthogonal, which is guaranteed with equal cell sizes but not with unequal ones. With unbalanced data, leaving other contrast rows or other effects off the design line can change how the sums of squares are partitioned, which changes the test of the one contrast you do care about. The safer default is to include every row of the contrast matrix and every other effect that belongs in the full model, even if you only plan to report one of them.</p>
</details>
<hr>
<p><strong>Question 7: When should we definitely keep <code>diagnosis</code> and <code>diagnosis BY drug</code> on the design line when testing drug marginal mean contrasts?</strong></p>
<details>
<summary>
Click to reveal answer
</summary>
<p>Always, when those terms belong in the model you are trying to match. The design line specifies the complete model SPSS fits. If <code>diagnosis</code> and <code>diagnosis BY drug</code> were part of the omnibus model you ran in Section 5, they need to stay in every follow-up model too, or the error term and degrees of freedom will no longer correspond to the same analysis, and your contrast test will not mean what you think it means.</p>
</details>
<hr>
<p><strong>Question 8: Will testing simple effects (Section 8) tell us which specific drugs differ within a given diagnosis group?</strong></p>
<details>
<summary>
Click to reveal answer
</summary>
<p>No.&nbsp;A significant simple effect, like a significant omnibus main effect, only tells you that the three drug means within that diagnosis group are not all equal. It does not say which pairs of drugs are responsible. That requires the cell mean comparisons from Section 9.</p>
</details>
<hr>
<p><strong>Question 9: What does the <code>(1)</code> mean in <code>drug W diagnosis(1)</code> on the design line?</strong></p>
<details>
<summary>
Click to reveal answer
</summary>
<p>Here the <code>(1)</code> is to the right of <code>W</code>, so it refers to a level of the factor, not a row of a contrast matrix. <code>drug W diagnosis(1)</code> means “test the omnibus effect of drug within the first level of diagnosis (Schizophrenia).”</p>
</details>
<hr>
<p><strong>Question 10: Why do we have to list so many effects on the design line for cell mean comparisons, when we only care about one pairwise contrast?</strong></p>
<details>
<summary>
Click to reveal answer
</summary>
<p>Because once contrasts are tested within separate levels of the other factor, they are not guaranteed to be orthogonal unless cell sizes are equal. SPSS needs the full set of contrasts and levels listed so it can correctly compute each one’s unique contribution to the sums of squares. Leaving terms off can silently change the test of the one comparison you actually want.</p>
</details>
<hr>
<p><strong>Question 11: What is the difference between the <code>(1)</code> next to <code>drug</code> and the <code>(1)</code> next to <code>diagnosis</code> on a design line like <code>drug(1) W diagnosis(1)</code>?</strong></p>
<details>
<summary>
Click to reveal answer
</summary>
<p>The <code>(1)</code> next to <code>drug</code>, appearing to the left of <code>W</code>, refers to the first row of the drug contrast matrix (a specific comparison, such as Drug 1 vs Drug 2). The <code>(1)</code> next to <code>diagnosis</code>, appearing to the right of <code>W</code>, refers to the first level of the diagnosis factor (Schizophrenia). Same symbol, different meaning, depending on which side of the <code>W</code> it sits on.</p>
</details>
<hr>
<p><strong>Question 12: If we are only interested in testing contrasts within level 1 of diagnosis, do we also have to include the contrasts within the other levels of diagnosis?</strong></p>
<details>
<summary>
Click to reveal answer
</summary>
<p>It depends on whether cell sizes are equal. With equal n, contrasts tested within separate levels of the other factor are always orthogonal to each other, so you can safely leave out the levels you are not interested in. With unequal n, that orthogonality is not guaranteed, so it is safest to include the contrasts within every level of diagnosis, even the ones you will not report, plus the main effect of diagnosis itself to fully account for the model’s degrees of freedom.</p>
</details>
<hr>
<p><strong>Question 13: When do we test interaction contrasts, before or after conducting the omnibus test?</strong></p>
<details>
<summary>
Click to reveal answer
</summary>
<p>Like any other planned comparison, an interaction contrast can be tested before the omnibus interaction test if it reflects a specific hypothesis you had going in. You are not required to find a significant omnibus interaction first. If instead you are exploring after the fact, without a specific prediction, you are in post hoc territory and should treat the interaction contrasts the way you would treat any unplanned comparison, including correcting for the number of tests run.</p>
</details>
<hr>
<p><strong>Question 14: Why is it unnecessary to compute interaction contrasts in a 2x2 design?</strong></p>
<details>
<summary>
Click to reveal answer
</summary>
<p>In a 2x2 design, each factor has only 1 degree of freedom, so the interaction term itself also has only <span class="math inline">\((2-1)(2-1) = 1\)</span> degree of freedom. The omnibus interaction test already is the single possible interaction contrast; there is no finer breakdown to test, since there is only one way each factor can be compared.</p>
</details>


</section>

</main> <!-- /main -->
<!-- MailerLite Universal -->
<script>
    (function(w,d,e,u,f,l,n){w[f]=w[f]||function(){(w[f].q=w[f].q||[])
    .push(arguments);},l=d.createElement(e),l.async=1,l.src=u,
    n=d.getElementsByTagName(e)[0],n.parentNode.insertBefore(l,n);})
    (window,document,'script','https://assets.mailerlite.com/js/universal.js','ml');
    ml('account', '2295583');
</script>
<!-- End MailerLite Universal -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/infogothic\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>