project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://infogothic.com 
  title: "InfoGothic"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/michaelwoller
      - icon: bluesky
        href: https://bsky.app/profile/infogothic.bsky.social
format:
  html:
    theme: [darkly, custom.scss]
    css: styles.css

editor: visual

