project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://infogothic.com 
  title: "InfoGothic"
  favicon: /images/favicon.png
  navbar:
    right:
      - about.qmd
      - tutorials.qmd
      - blog-posts.qmd
      - text: "Obsidian Notes"
        href: "https://notes.infogothic.com"
      - icon: github
        href: https://github.com/michaelwoller
      - icon: bluesky
        href: https://bsky.app/profile/infogothic.bsky.social
format:
  html:
    theme: [darkly, custom.scss]
    css: styles.css

editor: visual

