<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Michael Woller">

<title>Inference and Multiple Correlations – InfoGothic</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-f418161beb48e0141c760e455f12af2c.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-4d14f3be7bc8eb7ec2287338953877e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
document.addEventListener("DOMContentLoaded", function() {
  var nav = document.querySelector(".navbar-nav");
  var li = document.createElement("li");
  li.className = "nav-item";
  li.innerHTML = '<a class="nav-link ml-onclick-form" href="javascript:void(0)" onclick="ml(\'show\', \'18mxag\', true)">Mail List</a>';
  var icons = nav.querySelector(".nav-item:has(.bi)");
  nav.insertBefore(li, icons);
});
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Inference and Multiple Correlations – InfoGothic">
<meta property="og:description" content="Gothic Flavor of Statistics, Psychology, Economics">
<meta property="og:site_name" content="InfoGothic">
<meta name="twitter:title" content="Inference and Multiple Correlations – InfoGothic">
<meta name="twitter:description" content="Gothic Flavor of Statistics, Psychology, Economics">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">InfoGothic</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../tutorials.html"> 
<span class="menu-text">Courses &amp; Tutorials</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog-posts.html"> 
<span class="menu-text">Blog Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://publish.obsidian.md/infogothic/Home"> 
<span class="menu-text">Open Notes</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/michaelwoller"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://bsky.app/profile/infogothic.bsky.social"> <i class="bi bi-bluesky" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#the-dataset" id="toc-the-dataset" class="nav-link" data-scroll-target="#the-dataset">The Dataset</a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a></li>
  </ul></li>
  <li><a href="#coefficient-significance" id="toc-coefficient-significance" class="nav-link" data-scroll-target="#coefficient-significance">1. Coefficient Significance</a>
  <ul class="collapse">
  <li><a href="#coefficient-t-tests" id="toc-coefficient-t-tests" class="nav-link" data-scroll-target="#coefficient-t-tests">Coefficient t Tests</a></li>
  <li><a href="#inferential-statements" id="toc-inferential-statements" class="nav-link" data-scroll-target="#inferential-statements">Inferential Statements</a></li>
  <li><a href="#inference-with-confidence-intervals" id="toc-inference-with-confidence-intervals" class="nav-link" data-scroll-target="#inference-with-confidence-intervals">Inference with Confidence Intervals</a></li>
  </ul></li>
  <li><a href="#r2-f-tests" id="toc-r2-f-tests" class="nav-link" data-scroll-target="#r2-f-tests">2. <span class="math inline">\(R^2\)</span> F Tests</a>
  <ul class="collapse">
  <li><a href="#r2-f-tests-1" id="toc-r2-f-tests-1" class="nav-link" data-scroll-target="#r2-f-tests-1"><span class="math inline">\(R^2\)</span> F Tests</a></li>
  <li><a href="#r2-inferential-statements" id="toc-r2-inferential-statements" class="nav-link" data-scroll-target="#r2-inferential-statements"><span class="math inline">\(R^2\)</span> Inferential Statements</a></li>
  </ul></li>
  <li><a href="#model-comparison-tests" id="toc-model-comparison-tests" class="nav-link" data-scroll-target="#model-comparison-tests">3. Model Comparison Tests</a>
  <ul class="collapse">
  <li><a href="#model-comparisons" id="toc-model-comparisons" class="nav-link" data-scroll-target="#model-comparisons">Model Comparisons</a></li>
  <li><a href="#model-comparison-using-anova" id="toc-model-comparison-using-anova" class="nav-link" data-scroll-target="#model-comparison-using-anova">Model Comparison Using anova()</a></li>
  <li><a href="#manually-checking-model-r2s" id="toc-manually-checking-model-r2s" class="nav-link" data-scroll-target="#manually-checking-model-r2s">Manually Checking Model <span class="math inline">\(R^2\)</span>s</a></li>
  <li><a href="#delta-r2-inference" id="toc-delta-r2-inference" class="nav-link" data-scroll-target="#delta-r2-inference"><span class="math inline">\(\Delta R^2\)</span> Inference</a></li>
  <li><a href="#model-comparisons-of-one-predictor" id="toc-model-comparisons-of-one-predictor" class="nav-link" data-scroll-target="#model-comparisons-of-one-predictor">Model Comparisons of One Predictor</a></li>
  </ul></li>
  <li><a href="#squared-multiple-correlations" id="toc-squared-multiple-correlations" class="nav-link" data-scroll-target="#squared-multiple-correlations">4. Squared Multiple Correlations</a>
  <ul class="collapse">
  <li><a href="#squared-multiple-correlations-1" id="toc-squared-multiple-correlations-1" class="nav-link" data-scroll-target="#squared-multiple-correlations-1">Squared Multiple Correlations</a></li>
  <li><a href="#partialling-out-multiple-variables" id="toc-partialling-out-multiple-variables" class="nav-link" data-scroll-target="#partialling-out-multiple-variables">Partialling Out Multiple Variables</a></li>
  <li><a href="#calculating-semi-partial-multiple-correlations" id="toc-calculating-semi-partial-multiple-correlations" class="nav-link" data-scroll-target="#calculating-semi-partial-multiple-correlations">Calculating Semi-Partial Multiple Correlations</a></li>
  <li><a href="#semi-partial-squared-correlations-interpretation" id="toc-semi-partial-squared-correlations-interpretation" class="nav-link" data-scroll-target="#semi-partial-squared-correlations-interpretation">Semi-Partial Squared Correlations Interpretation</a></li>
  <li><a href="#semi-partial-squared-correlations-equal-delta-r2" id="toc-semi-partial-squared-correlations-equal-delta-r2" class="nav-link" data-scroll-target="#semi-partial-squared-correlations-equal-delta-r2">Semi-Partial Squared Correlations Equal <span class="math inline">\(\Delta R^2\)</span></a></li>
  <li><a href="#squared-partial-multiple-correlations" id="toc-squared-partial-multiple-correlations" class="nav-link" data-scroll-target="#squared-partial-multiple-correlations">Squared Partial Multiple Correlations</a></li>
  <li><a href="#partial-correlations-from-semi-partial-correlations" id="toc-partial-correlations-from-semi-partial-correlations" class="nav-link" data-scroll-target="#partial-correlations-from-semi-partial-correlations">Partial Correlations from Semi-Partial Correlations</a></li>
  </ul></li>
  <li><a href="#tolerance-and-variance-inflation-factor" id="toc-tolerance-and-variance-inflation-factor" class="nav-link" data-scroll-target="#tolerance-and-variance-inflation-factor">5. Tolerance and Variance Inflation Factor</a>
  <ul class="collapse">
  <li><a href="#tolerance" id="toc-tolerance" class="nav-link" data-scroll-target="#tolerance">Tolerance</a></li>
  <li><a href="#vif" id="toc-vif" class="nav-link" data-scroll-target="#vif">VIF</a></li>
  <li><a href="#getting-vif-with-vif" id="toc-getting-vif-with-vif" class="nav-link" data-scroll-target="#getting-vif-with-vif">Getting VIF with vif()</a></li>
  </ul></li>
  <li><a href="#well-done" id="toc-well-done" class="nav-link" data-scroll-target="#well-done">Well Done!</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Inference and Multiple Correlations</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Michael Woller </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 data-anchor-id="introduction">Introduction</h2>
<p>In this lesson we will cover regression inference and multiple correlations. Previously, you learned about interpretations of what we observe. Inference has to do with how what we observe can apply to the population. These are two separate concepts, so keep this in mind.</p>
<section id="the-dataset" class="level3">
<h3 data-anchor-id="the-dataset">The Dataset</h3>
<p>Data for this lesson is courtesy of Dr.&nbsp;Egamaria Alacam, an avid reggaeton enjoyer (and I simulated some too). It consists of the variables</p>
<ul>
<li><code>Age</code> — how old the individual is (continuous scale)</li>
<li><code>Enjoy</code> — how much the individual enjoys reggaeton (1–5 continuous)</li>
<li><code>RL</code> — how much the individual likes Rauw Alejandro (1–5 continuous)</li>
<li><code>Span</code> — self reported scale on the individual’s Spanish proficiency (1–10 scale)</li>
<li><code>LatMed</code> — how many hours per week the individual spends consuming Latin America media (interval scale)</li>
<li><code>LatClub</code> — how many hours per month the individual spends in a Latin American club (interval)</li>
</ul>
<p>We will be predicting how much an individual enjoys the music of Rauw Alejandro (<code>Enjoy</code>) by their age (<code>Age</code>) and how much they like reggaeton (<code>RL</code>).</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/CFPLIaMpGrY" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
</section>
<section id="section" class="level3">
<h3 data-anchor-id="section"></h3>
<p>The dataset is <code>rauw</code>. We remove missing values on <code>Age</code> and <code>RL</code> before proceeding.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>rauw <span class="ot">&lt;-</span> rauw[<span class="fu">complete.cases</span>(rauw<span class="sc">$</span>Age) <span class="sc">&amp;</span> <span class="fu">complete.cases</span>(rauw<span class="sc">$</span>RL),]</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># N = 1549</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<hr>
</section>
</section>
<section id="coefficient-significance" class="level2">
<h2 data-anchor-id="coefficient-significance">1. Coefficient Significance</h2>
<section id="coefficient-t-tests" class="level3">
<h3 data-anchor-id="coefficient-t-tests">Coefficient t Tests</h3>
<p>All regression output will give you significance tests for the slopes by default. These will be t tests with degrees of freedom equal to <span class="math inline">\(df = N - k - 1\)</span>, where <span class="math inline">\(N\)</span> is your sample size and <span class="math inline">\(k\)</span> is the number of predictors in the model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Enjoy <span class="sc">~</span> RL <span class="sc">+</span> Age, <span class="at">data =</span> rauw)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Enjoy ~ RL + Age, data = rauw)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.65050 -0.58972 -0.05694  0.66104  2.67046 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.37944    0.23824   5.790  8.5e-09 ***
RL           0.32712    0.01426  22.947  &lt; 2e-16 ***
Age          0.01401    0.01032   1.358    0.175    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9077 on 1546 degrees of freedom
Multiple R-squared:  0.2543,    Adjusted R-squared:  0.2534 
F-statistic: 263.7 on 2 and 1546 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Here we can see that the intercept and slope of <code>RL</code> are significant at the <span class="math inline">\(\alpha = .05\)</span> rejection level, however <code>Age</code> is not significant.</p>
</section>
<section id="inferential-statements" class="level3">
<h3 data-anchor-id="inferential-statements">Inferential Statements</h3>
<p>Inference involves a null hypothesis about the population. “Null” coming from the fact that it assumes a baseline fact about the population, which for a coefficient t test is that the coefficient equals 0.</p>
<p>When addressing inference, “significance” applies to your sample statistic (i.e., the coefficient you estimated from the sample). The null hypothesis is about the population.</p>
<ul>
<li>It is <strong>NOT</strong> appropriate to say you reject/fail to reject the null that your slope equals 0. The hypothesis is that the <em>population</em> slope is 0.</li>
<li>It is <strong>NOT</strong> appropriate to say that the slope is significantly different than in the population. Significance applies to what you observe from your regression model.</li>
<li>It <strong>IS</strong> appropriate to say you reject/fail to reject the null that the <strong>population</strong> slope equals 0.</li>
<li>It <strong>IS</strong> appropriate to say that your model’s coefficient is significantly different than 0.</li>
</ul>
<p>A correct inferential statement also ALWAYS includes the test you used (t test), the proper degrees of freedom, and the p value (unless it is below .001, in which case you just say <span class="math inline">\(p &lt; .001\)</span>). You should also report confidence intervals and their width (95%).</p>
<p><strong>Intercept:</strong></p>
<blockquote class="blockquote">
<p>The intercept was significant <span class="math inline">\(t(1546) = 5.78\)</span>, <span class="math inline">\(p &lt; .001\)</span>, 95% CI [.91, 1.85]. This means that the model intercept was significant, so we reject the null that the intercept is 0 in the population.</p>
</blockquote>
<p><strong>RL Slope:</strong></p>
<blockquote class="blockquote">
<p>The slope of RL was significant <span class="math inline">\(t(1546) = 22.94\)</span>, <span class="math inline">\(p &lt; .001\)</span>, 95% CI [.30, .36]. This means that the slope of RL was significant, so we reject the null that how much an individual enjoys reggaeton does not predict how much they enjoy Rauw Alejandro in the population.</p>
</blockquote>
<p><strong>Age Slope:</strong></p>
<blockquote class="blockquote">
<p>The slope of Age was not significant <span class="math inline">\(t(1546) = 1.36\)</span>, <span class="math inline">\(p = .17\)</span>, 95% CI [-.01, .03]. This means that the slope of Age was not significant, so we fail to reject the null that an individual’s age does not predict how much an individual enjoys Rauw Alejandro in the population.</p>
</blockquote>
</section>
<section id="inference-with-confidence-intervals" class="level3">
<h3 data-anchor-id="inference-with-confidence-intervals">Inference with Confidence Intervals</h3>
<p>It is possible to do inference with confidence intervals. To do this, you need to see if the confidence interval contains your null hypothesis. Since our null for the coefficients is 0, and we are using the 95% confidence level (determined by your alpha rejection rate), we will see if the 95% confidence intervals for each coefficient contain 0.</p>
<p>You need to use the <code>confint()</code> function, which gives 95% confidence intervals by default.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   2.5 %     97.5 %
(Intercept)  0.912139756 1.84674816
RL           0.299160783 0.35508485
Age         -0.006228713 0.03425818</code></pre>
</div>
</div>
<p>Looking at the output, we see that the confidence intervals for the intercept and slope of <code>RL</code> do not contain 0, while the interval of <code>Age</code> does contain 0. So we would conclude that our intercept and slope of <code>RL</code> are significant, but the slope of <code>Age</code> is not significant.</p>
<p>If you are using a different alpha level than .05, you will need to manually change the confidence interval width.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Alpha = .01 and a 99% Confidence Interval</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model1, <span class="at">level =</span> .<span class="dv">99</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 0.5 %     99.5 %
(Intercept)  0.7650244 1.99386349
RL           0.2903579 0.36388777
Age         -0.0126017 0.04063116</code></pre>
</div>
</div>
<p>Even with the new alpha level, we would still reject the null of the intercept and <code>RL</code>.</p>
<hr>
</section>
</section>
<section id="r2-f-tests" class="level2">
<h2 data-anchor-id="r2-f-tests">2. <span class="math inline">\(R^2\)</span> F Tests</h2>
<section id="r2-f-tests-1" class="level3">
<h3 data-anchor-id="r2-f-tests-1"><span class="math inline">\(R^2\)</span> F Tests</h3>
<p>The <span class="math inline">\(R^2\)</span> coefficient also has a significance test associated with it. It tests whether or not the model explains a significant amount of the variation in the outcome or not. Inference on <span class="math inline">\(R^2\)</span> is about the “population” <span class="math inline">\(R^2\)</span>. This can be thought of as the “true” relationship your predictors have on the outcome. Your model only estimates this true relationship, but we want to make direct inferences on it as well.</p>
<p>R will give you the <span class="math inline">\(R^2\)</span> F test as default output. It is at the bottom of the <code>summary()</code> output.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Enjoy ~ RL + Age, data = rauw)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.65050 -0.58972 -0.05694  0.66104  2.67046 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.37944    0.23824   5.790  8.5e-09 ***
RL           0.32712    0.01426  22.947  &lt; 2e-16 ***
Age          0.01401    0.01032   1.358    0.175    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9077 on 1546 degrees of freedom
Multiple R-squared:  0.2543,    Adjusted R-squared:  0.2534 
F-statistic: 263.7 on 2 and 1546 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The F-statistic line gives the F test statistic, the degrees of freedom, and p value.</p>
<p>Note the adjusted-<span class="math inline">\(R^2\)</span> value does NOT have a significance test associated with it. All <span class="math inline">\(R^2\)</span> tests are for unadjusted <span class="math inline">\(R^2\)</span>s. The degrees of freedom for this F test follow:</p>
<p><span class="math display">\[df_1 = k \qquad df_2 = N - k - 1\]</span></p>
<p>where <span class="math inline">\(N\)</span> is the sample size and <span class="math inline">\(k\)</span> is the number of predictors.</p>
</section>
<section id="r2-inferential-statements" class="level3">
<h3 data-anchor-id="r2-inferential-statements"><span class="math inline">\(R^2\)</span> Inferential Statements</h3>
<p>Inferential statements about <span class="math inline">\(R^2\)</span> follow the same idea that significance is for the statistic from the model, and the null hypothesis conclusion is for the population relationship. A correct inferential statement needs to include both. It also needs to include the F statistic, both degrees of freedom, and the p value.</p>
<blockquote class="blockquote">
<p>The <span class="math inline">\(R^2\)</span> = .25 coefficient was significant <span class="math inline">\(F(2, 1546) = 263.7\)</span>, <span class="math inline">\(p &lt; .001\)</span>. Thus, we reject the null hypothesis that how much an individual loves reggaeton and the individual’s age does not explain variation of how much individuals like Rauw Alejandro in the population.</p>
</blockquote>
<hr>
</section>
</section>
<section id="model-comparison-tests" class="level2">
<h2 data-anchor-id="model-comparison-tests">3. Model Comparison Tests</h2>
<section id="model-comparisons" class="level3">
<h3 data-anchor-id="model-comparisons">Model Comparisons</h3>
<p>t tests of model coefficients allow you to test single parameter slopes. However, it is often desirable to test multiple slopes <em>combined</em>. To do this, you need to do a model comparison test (or multiple parameter test). A common one is to test the change in <span class="math inline">\(R^2\)</span>, or <span class="math inline">\(\Delta R^2\)</span>.</p>
<p>If a slope t test determines if a single variable is significant in explaining Y, a <span class="math inline">\(\Delta R^2\)</span> F test can determine if multiple variables at a time are significant in explaining Y.</p>
<p>The default model <span class="math inline">\(R^2\)</span> F test compares all the variables in the model to an “empty” model with no predictors. It is possible to do this type of comparison, but to just test a select subset of variables rather than every variable.</p>
<p>The main model we are going to consider is to predict how much an individual enjoys the music of Rauw Alejandro (<code>Enjoy</code>) predicted by their age (<code>Age</code>), how much they like reggaeton music (<code>RL</code>), and a set of predictors making up “Latin American cultural experience.” This set of variables consists of self-report competency in Spanish (<code>Span</code>), the amount of hours per week an individual engages with Latin American media (<code>LatMed</code>), and the amount of hours per week the individual spends in a Latin American based club (<code>LatClub</code>).</p>
<p>We will be looking at whether or not the Latin American cultural experience variable set explains a significant amount of variance in <code>Enjoy</code>, after controlling for <code>Age</code> and <code>RL</code>.</p>
</section>
<section id="model-comparison-using-anova" class="level3">
<h3 data-anchor-id="model-comparison-using-anova">Model Comparison Using anova()</h3>
<p>In order to do a <span class="math inline">\(\Delta R^2\)</span> F test, you need to first save two different models, one being “nested” within the other. “Nested” means that one model is just a reduced version of the other, with a subset of the predictors.</p>
<p>First fit a “full” model that includes all relevant variables.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>model_full <span class="ot">&lt;-</span> <span class="fu">lm</span>(Enjoy <span class="sc">~</span> RL <span class="sc">+</span> Age <span class="sc">+</span> Span <span class="sc">+</span> LatMed <span class="sc">+</span> LatClub, <span class="at">data =</span> rauw)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Then fit a “reduced” model that includes the variables you do NOT want to test. Aka, remove the variables you are testing.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>model_reduced <span class="ot">&lt;-</span> <span class="fu">lm</span>(Enjoy <span class="sc">~</span> RL <span class="sc">+</span> Age, <span class="at">data =</span> rauw)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The idea here is that we are going to check how good the reduced model is already, and then see if the extra Latin American cultural variables in the full model significantly increase the <span class="math inline">\(R^2\)</span> or not. If so, then they, as a group, are useful. If not, then they, as a group, are not helpful. Note that we are checking the group, not individual predictors.</p>
<p>To test this, we can use the <code>anova()</code> function with the model objects. The order does not really matter, but you can put the reduced model first.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model_reduced, model_full)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Enjoy ~ RL + Age
Model 2: Enjoy ~ RL + Age + Span + LatMed + LatClub
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1   1546 1273.7                           
2   1543 1272.0  3    1.6972 0.6863 0.5604</code></pre>
</div>
</div>
<p>This F test compares the <span class="math inline">\(R^2\)</span> between the two models, and as you can see from the <span class="math inline">\(p = .56\)</span> value, our predictor set does not significantly increase the <span class="math inline">\(R^2\)</span>. Therefore, we can conclude that the set of variables that make up Latin American cultural experience does not increase our ability to explain enjoyment of Rauw Alejandro. It turns out Rauw is for everybody.</p>
</section>
<section id="manually-checking-model-r2s" class="level3">
<h3 data-anchor-id="manually-checking-model-r2s">Manually Checking Model <span class="math inline">\(R^2\)</span>s</h3>
<p>You can double check the F test above manually.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>R2_full    <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_full)<span class="sc">$</span>r.squared</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>R2_reduced <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_reduced)<span class="sc">$</span>r.squared</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Manually find the difference in the two models (full - reduced)</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>delta_r2 <span class="ot">&lt;-</span> R2_full <span class="sc">-</span> R2_reduced</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>delta_r2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0009935905</code></pre>
</div>
</div>
<p>This .0009 (very tiny) is the change in <span class="math inline">\(R^2\)</span> that the <code>anova()</code> above is testing. You can also test the <span class="math inline">\(\Delta R^2\)</span> manually. This is just for demonstration purposes.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>n         <span class="ot">&lt;-</span> <span class="fu">nrow</span>(rauw)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>df_full    <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">coef</span>(model_full)) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>df_reduced <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">coef</span>(model_reduced)) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate F statistic</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>f_stat <span class="ot">&lt;-</span> ((R2_full <span class="sc">-</span> R2_reduced) <span class="sc">/</span> (df_full <span class="sc">-</span> df_reduced)) <span class="sc">/</span> </span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>          ((<span class="dv">1</span> <span class="sc">-</span> R2_full) <span class="sc">/</span> (n <span class="sc">-</span> df_full <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>f_stat</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6862555</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check p value</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pf</span>(f_stat, <span class="at">df1 =</span> df_full <span class="sc">-</span> df_reduced, <span class="at">df2 =</span> n <span class="sc">-</span> df_full <span class="sc">-</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5604439</code></pre>
</div>
</div>
<p>This is the same F statistic and p value as the <code>anova()</code> output.</p>
</section>
<section id="delta-r2-inference" class="level3">
<h3 data-anchor-id="delta-r2-inference"><span class="math inline">\(\Delta R^2\)</span> Inference</h3>
<p>Inferential statements for <span class="math inline">\(\Delta R^2\)</span> tests follow the same idea as other tests. You should report all relevant statistics, make a conclusion based on the p value if the found <span class="math inline">\(\Delta R^2\)</span> is significant or not, then make a conclusion about the change in <span class="math inline">\(R^2\)</span> at the population level.</p>
<p>The degrees of freedom for the <span class="math inline">\(\Delta R^2\)</span> F tests are:</p>
<p><span class="math display">\[df_1 = k_{full} - k_{reduced} \qquad df_2 = N - k_{full} - 1\]</span></p>
<blockquote class="blockquote">
<p>The <span class="math inline">\(\Delta R^2 = .01\)</span> statistic was not significant <span class="math inline">\(F(3, 1543) = .79\)</span>, <span class="math inline">\(p = .56\)</span>. Therefore, we fail to reject that an individual’s Latin American cultural experience does not explain a significant more amount of variation of their enjoyment of Rauw Alejandro in the population after accounting for their age and how much they like reggaeton.</p>
</blockquote>
</section>
<section id="model-comparisons-of-one-predictor" class="level3">
<h3 data-anchor-id="model-comparisons-of-one-predictor">Model Comparisons of One Predictor</h3>
<p>Something important to mention that will occasionally come back up is doing a <span class="math inline">\(\Delta R^2\)</span> model comparison test for a single variable. That is, the reduced model only differs from the full model by one variable.</p>
<p><strong>Example:</strong></p>
<ul>
<li>Full model: <code>Enjoy = RL + Age + Span + LatMed + LatClub</code></li>
<li>Reduced model: <code>Enjoy = Age + Span + LatMed + LatClub</code></li>
</ul>
<p>If you were to calculate a <span class="math inline">\(\Delta R^2\)</span> F test for the difference of <span class="math inline">\(R^2\)</span> between these two models, this will be analytically equivalent to the t test for the slope of <code>RL</code> in the full model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>model_full2    <span class="ot">&lt;-</span> <span class="fu">lm</span>(Enjoy <span class="sc">~</span> RL <span class="sc">+</span> Age <span class="sc">+</span> Span <span class="sc">+</span> LatMed <span class="sc">+</span> LatClub, <span class="at">data =</span> rauw)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>model_reduced2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Enjoy <span class="sc">~</span> Age <span class="sc">+</span> Span <span class="sc">+</span> LatMed <span class="sc">+</span> LatClub, <span class="at">data =</span> rauw)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate F test with anova()</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model_reduced2, model_full2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Enjoy ~ Age + Span + LatMed + LatClub
Model 2: Enjoy ~ RL + Age + Span + LatMed + LatClub
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1   1544 1707.4                                  
2   1543 1272.0  1     435.4 528.16 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Now look at the t test for RL in the full model</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_full2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Enjoy ~ RL + Age + Span + LatMed + LatClub, data = rauw)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.62706 -0.59206 -0.05455  0.66169  2.68763 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.469995   0.281569   5.221 2.02e-07 ***
RL           0.328126   0.014278  22.982  &lt; 2e-16 ***
Age          0.013947   0.010326   1.351    0.177    
Span        -0.017998   0.014656  -1.228    0.220    
LatMed       0.006832   0.010492   0.651    0.515    
LatClub     -0.003552   0.008001  -0.444    0.657    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9079 on 1543 degrees of freedom
Multiple R-squared:  0.2553,    Adjusted R-squared:  0.2529 
F-statistic: 105.8 on 5 and 1543 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># If we square the t statistic for RL...</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fl">22.982</span><span class="sc">^</span><span class="dv">2</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 528.1723</code></pre>
</div>
</div>
<p>We get the same F statistic as the <code>anova()</code> output! Thus, an F test for a model comparison for a single variable is identical to the t test of the coefficient in the full model. The F statistic is just the t statistic squared.</p>
<p>Conceptually, you can think of the model comparison test as analyzing whether a model that adds <code>RL</code> significantly explains more variance in <code>Enjoy</code> than a model without <code>RL</code>. It turns out that this is exactly what the slope test of <code>RL</code> is doing - it checks whether or not <code>RL</code> is significant for explaining <code>Enjoy</code>.</p>
<hr>
</section>
</section>
<section id="squared-multiple-correlations" class="level2">
<h2 data-anchor-id="squared-multiple-correlations">4. Squared Multiple Correlations</h2>
<section id="squared-multiple-correlations-1" class="level3">
<h3 data-anchor-id="squared-multiple-correlations-1">Squared Multiple Correlations</h3>
<p>Previously, we have learned correlations between two variables (e.g., correlation between Y and X). However, it is possible to get a “correlation” between one variable and a set of predictors (e.g., correlation between Y and X1, X2, X3). Since there are multiple predictors in this desired correlation, the only way to format it is by making it a “squared” correlation, akin to an <span class="math inline">\(R^2\)</span> statistic.</p>
</section>
<section id="partialling-out-multiple-variables" class="level3">
<h3 data-anchor-id="partialling-out-multiple-variables">Partialling Out Multiple Variables</h3>
<p>Previously, we learned how to partial out one variable from Y and another predictor. However, it is possible to partial multiple variables at a time to get a partial or semi-partial squared multiple correlation. The result is a statistic that explains the relationship between a set of variables and the outcome while removing the influence of other variables.</p>
</section>
<section id="calculating-semi-partial-multiple-correlations" class="level3">
<h3 data-anchor-id="calculating-semi-partial-multiple-correlations">Calculating Semi-Partial Multiple Correlations</h3>
<p>To calculate multiple squared correlations, there is no easy built-in method in R. Instead, we have to manually calculate these by saving partialled residuals.</p>
<p>Basically, you add the variables you want to partial from as outcomes in many regression models, and the variable(s) you want to partial out as the predictor.</p>
<p>As a running example, we want to partial out <code>Age</code> from each other variable besides the outcome of <code>Enjoy</code> (since this is “semi-partial”).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>resid_rl      <span class="ot">&lt;-</span> <span class="fu">lm</span>(RL      <span class="sc">~</span> Age, <span class="at">data =</span> rauw)<span class="sc">$</span>residuals</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>resid_span    <span class="ot">&lt;-</span> <span class="fu">lm</span>(Span    <span class="sc">~</span> Age, <span class="at">data =</span> rauw)<span class="sc">$</span>residuals</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>resid_lat_med  <span class="ot">&lt;-</span> <span class="fu">lm</span>(LatMed  <span class="sc">~</span> Age, <span class="at">data =</span> rauw)<span class="sc">$</span>residuals</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>resid_lat_club <span class="ot">&lt;-</span> <span class="fu">lm</span>(LatClub <span class="sc">~</span> Age, <span class="at">data =</span> rauw)<span class="sc">$</span>residuals</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Then you need to add these residuals as the predictors in a model that predicts <code>Enjoy</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>semi_part_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Enjoy <span class="sc">~</span> resid_rl <span class="sc">+</span> resid_span <span class="sc">+</span> resid_lat_med <span class="sc">+</span> resid_lat_club,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> rauw)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># All you need is the R^2 of this model (everything else is not useful)</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(semi_part_model)<span class="sc">$</span>r.squared</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2549719</code></pre>
</div>
</div>
<p>Thus, the semi-partial squared multiple correlation is .25.</p>
</section>
<section id="semi-partial-squared-correlations-interpretation" class="level3">
<h3 data-anchor-id="semi-partial-squared-correlations-interpretation">Semi-Partial Squared Correlations Interpretation</h3>
<p>The interpretation of semi-partial squared correlations follows an <span class="math inline">\(R^2\)</span>.</p>
<blockquote class="blockquote">
<p>The proportion of variance explained in Rauw Alejandro enjoyment that is uniquely attributed to reggaeton enjoyment and Latin American cultural experience, after we accounted for Age already. So for our example, reggaeton enjoyment and Latin American cultural experience uniquely explain 25% of the variation in Rauw Alejandro enjoyment, after accounting for age.</p>
</blockquote>
</section>
<section id="semi-partial-squared-correlations-equal-delta-r2" class="level3">
<h3 data-anchor-id="semi-partial-squared-correlations-equal-delta-r2">Semi-Partial Squared Correlations Equal <span class="math inline">\(\Delta R^2\)</span></h3>
<p>An interesting fact about the semi-partial squared multiple correlations is that they actually equal a <span class="math inline">\(\Delta R^2\)</span> test for whatever you are partialling.</p>
<p>Consider the following full and reduced models:</p>
<ul>
<li>Full model: <code>Enjoy = RL + Age + Span + LatMed + LatClub</code></li>
<li>Reduced model: <code>Enjoy = Age</code></li>
</ul>
<p>The reduced model only has <code>Age</code>. When we compare these two models, we are essentially comparing how much the other set of variables can explain <code>Enjoy</code> after already accounting for <code>Age</code>. To demonstrate:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>model_full3    <span class="ot">&lt;-</span> <span class="fu">lm</span>(Enjoy <span class="sc">~</span> RL <span class="sc">+</span> Age <span class="sc">+</span> Span <span class="sc">+</span> LatMed <span class="sc">+</span> LatClub, <span class="at">data =</span> rauw)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>model_reduced3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Enjoy <span class="sc">~</span> Age, <span class="at">data =</span> rauw)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>R2_full3    <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_full3)<span class="sc">$</span>r.squared</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>R2_reduced3 <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_reduced3)<span class="sc">$</span>r.squared</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>R2_full3 <span class="sc">-</span> R2_reduced3</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2549719</code></pre>
</div>
</div>
<p>The <span class="math inline">\(\Delta R^2\)</span> is .255. This is identical to the semi-partial squared multiple correlation we found using residuals.</p>
</section>
<section id="squared-partial-multiple-correlations" class="level3">
<h3 data-anchor-id="squared-partial-multiple-correlations">Squared Partial Multiple Correlations</h3>
<p>To get the squared <em>partial</em> multiple correlations, we must also partial out <code>Age</code> from the <code>Enjoy</code> outcome along with the predictors.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>resid_enjoy <span class="ot">&lt;-</span> <span class="fu">lm</span>(Enjoy <span class="sc">~</span> Age, <span class="at">data =</span> rauw)<span class="sc">$</span>residuals</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Run a model with the residuals for each partialled variable</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>part_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(resid_enjoy <span class="sc">~</span> resid_rl <span class="sc">+</span> resid_span <span class="sc">+</span> resid_lat_med <span class="sc">+</span> resid_lat_club,</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> rauw)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(part_model)<span class="sc">$</span>r.squared</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2550621</code></pre>
</div>
</div>
<p>From this, we can see that the partial squared correlation is .2551.</p>
</section>
<section id="partial-correlations-from-semi-partial-correlations" class="level3">
<h3 data-anchor-id="partial-correlations-from-semi-partial-correlations">Partial Correlations from Semi-Partial Correlations</h3>
<p>It is possible to get the partial squared multiple correlation directly from the semi-partial squared correlations. You need the semi-partial multiple correlation (<span class="math inline">\(\Delta R^2\)</span>) and the <span class="math inline">\(R^2\)</span> from the reduced model (the model where we partialled out <code>Age</code> from <code>Enjoy</code>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>R2_age <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">lm</span>(Enjoy <span class="sc">~</span> Age, <span class="at">data =</span> rauw))<span class="sc">$</span>r.squared</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>d_r2   <span class="ot">&lt;-</span> <span class="fu">summary</span>(semi_part_model)<span class="sc">$</span>r.squared</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># delta-R^2 / (1 - R^2_reduced)</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>d_r2 <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> R2_age)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2550621</code></pre>
</div>
</div>
<p>You can see this is identical to the partial squared multiple correlation from Section 4.6.</p>
<hr>
</section>
</section>
<section id="tolerance-and-variance-inflation-factor" class="level2">
<h2 data-anchor-id="tolerance-and-variance-inflation-factor">5. Tolerance and Variance Inflation Factor</h2>
<section id="tolerance" class="level3">
<h3 data-anchor-id="tolerance">Tolerance</h3>
<p>Tolerance is the proportion of variance that is unexplained. In other words: <span class="math inline">\(\text{Tolerance} = 1 - R^2_j\)</span>, where <span class="math inline">\(R^2_j\)</span> is the <span class="math inline">\(R^2\)</span> you get from predicting <span class="math inline">\(X_j\)</span> from all the other X’s in the model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example: R^2_RL</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>R2_rl <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">lm</span>(RL <span class="sc">~</span> Age <span class="sc">+</span> Span <span class="sc">+</span> LatMed <span class="sc">+</span> LatClub, <span class="at">data =</span> rauw))<span class="sc">$</span>r.squared</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>R2_rl</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.002977562</code></pre>
</div>
</div>
<p>Essentially, this tells you how well we can predict <code>RL</code> from the other variables. Tolerance thus is how much unique variance does this predictor still have?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tolerance for RL</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> R2_rl</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9970224</code></pre>
</div>
</div>
<p>Since the tolerance is so high in <code>RL</code>’s case, hardly any of the predictive ability for <code>RL</code> is due to the presence of other variables. Tolerance is inherently unrelated to the size of correlation between predictors and outcome. It is typically used as a transitionary step to get other statistics.</p>
</section>
<section id="vif" class="level3">
<h3 data-anchor-id="vif">VIF</h3>
<p>The Variance Inflation Factor (VIF) is the extent to which a slope coefficient’s standard error is affected by the correlation to another variable. It acts as a measure of collinearity:</p>
<p><span class="math display">\[VIF = \frac{1}{\text{Tolerance}} = \frac{1}{1 - R^2_j}\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># VIF for RL</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> R2_rl)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.002986</code></pre>
</div>
</div>
<p>The larger the VIF for a specific slope, the more collinear that predictor is with the other predictors. The traditional cutoff for non-ignorable collinearity is when a predictor’s VIF <span class="math inline">\(\geq\)</span> 1.10. Keep in mind that the higher the collinearity of the predictors, the less valid your inference is.</p>
</section>
<section id="getting-vif-with-vif" class="level3">
<h3 data-anchor-id="getting-vif-with-vif">Getting VIF with vif()</h3>
<p>Use the <code>vif()</code> function from the <code>car</code> package by plugging your model object in.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(model_full)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      RL      Age     Span   LatMed  LatClub 
1.002986 1.001000 1.002607 1.002242 1.001438 </code></pre>
</div>
</div>
<p>As you can see, the VIF for each variable is tiny. So none of the variables are collinear with each other. If you want the tolerance, you can manually calculate it.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">/</span> <span class="fu">vif</span>(model_full)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       RL       Age      Span    LatMed   LatClub 
0.9970224 0.9990007 0.9973998 0.9977630 0.9985637 </code></pre>
</div>
</div>
<hr>
</section>
</section>
<section id="well-done" class="level2">
<h2 data-anchor-id="well-done">Well Done!</h2>
<p>You have completed the Inference and Multiple Correlations tutorial. Here is a summary of what was covered:</p>
<ul>
<li>Coefficient t tests and how to write correct inferential statements</li>
<li>Using confidence intervals for inference with <code>confint()</code></li>
<li><span class="math inline">\(R^2\)</span> F tests and how to write <span class="math inline">\(R^2\)</span> inferential statements</li>
<li><span class="math inline">\(\Delta R^2\)</span> model comparison tests with <code>anova()</code> and how to do them manually</li>
<li>The equivalence between a single-variable <span class="math inline">\(\Delta R^2\)</span> F test and the coefficient t test</li>
<li>Squared semi-partial and partial multiple correlations computed via saved residuals</li>
<li>The equivalence between semi-partial squared multiple correlations and <span class="math inline">\(\Delta R^2\)</span></li>
<li>Tolerance and VIF with <code>vif()</code> from the <code>car</code> package</li>
</ul>
<p>The next lesson covers regression diagnostics.</p>


</section>

</main> <!-- /main -->
<!-- MailerLite Universal -->
<script>
    (function(w,d,e,u,f,l,n){w[f]=w[f]||function(){(w[f].q=w[f].q||[])
    .push(arguments);},l=d.createElement(e),l.async=1,l.src=u,
    n=d.getElementsByTagName(e)[0],n.parentNode.insertBefore(l,n);})
    (window,document,'script','https://assets.mailerlite.com/js/universal.js','ml');
    ml('account', '2295583');
</script>
<!-- End MailerLite Universal -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/infogothic\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>