---
title: "Success Must Fail"
date: "2026-05-13"
description: "Old ideas of what it means to be successful must change for the good of all of us"
author: "Michael Woller"
draft: true
categories: [goth, analysis]
---

Through my experiences in grad school, I've started to get very concerned about the attitudes I have seen in academic circles and just general society at large. This is by no means an attempt to come at academia as a higher institution or a "here's why academia sucks" as I don't think what I'm going to way to it applies to it uniquely. Being in a doctorate program has just painted my perspective towards academics specifically.

When I first joined graduate school, I was very gung ho and motivated to prove myself to the world I wanted to be a part of. That is, I wanted to show I can be a part of the circle of intelligentsia I held in high esteem up to that point. Which, if I had to guess, is a common sentiment with many people entering a doctorate program at UCLA.

However, things happened that made me change my attitude. I went through very deep isolation and suicidal depression at the end of my first year leading through my second year. This was due to a few factors outside of school, but the pressure of me needing to succeed and me needing to go far to gain approval of this community I held in such high esteem. To what end? So that I would feel good about myself I suppose. For my own reasons, I convinced myself that this type of success is very important and would help me get past these issues of self esteem and sadness.

Eventually, I realized the irony that my desire of success was a non negligible contribution to my misery, and that it felt like everything was trying to help me get over my issues just to achieve these notions of success and perpetuate my misery. Very Budhist. Academic accolades. Celebrations in the department of winning fellowships. h-index, publishing in great journals, follower numbers, just getting a general "you are going to go far" congratulations from professors were imposed on all of us grad students from every end, both within and outside of our labs.

Of course, people want their students to succeed. What are they going to celebrate and hold your hands while you fail? We are far past those stages of our life. Many students don't really care about these things. Some people enjoyed this game and were motivated by the recognition. Other students get a sense of inferiority when they do not succeed in these metrics. But for what purpose? These matters of success don't matter after all?

It's very easy to tell yourself this as a solution to the success anxiety. That was my initial coping mechanism. *Actually, succeeding in these ways doesn't matter. I don't need this kind of recognition.* Sometimes this line of thinking even leads you to *actually, academia and academics are the real issue*, though I always try to control angst from getting me that far as I don't think that's honest.

What is honest is that of course this kind of success matters. It's celebrated for a reason. It's difficult to balance this. Me not wanting to engage with this kind of stuff for my own mental health, but being shown everywhere around me that this is the stuff that matters. This is what success is. It made me feel like a black sheep in my program.

Of course, there's a million ways to "criticize" the common notions of success, especially in academia. But the fact of the matter is, that this is valued by society and we get constant bombardment both in and outside of academia of the things that people value. You can hold close to the things you value yourself, and I think you should, but it is hard to get to that point in your life, and frankly, I think a lot of people are deluding themselves that they are detached from societies expectations. I wonder how many people of Forbes 30 under 30 tell themselves similar things, and then ask them why they did the interview and photo shoots. I'm not convinced by words when the actions will choose the thing that reaffirms.

I guess I'm not convinced by people who claiming they have their own values that happen to overlap heavily with the expected values of society, but to each there own.

At the end of this, however, you have to wonder something practically. Who can actually achieve this? My faith and esteem wavered when I started to seriously question this for myself. And instead of trying to get over my self doubt and insecurity in order to achieve victory, I decided to dive deeper into that source of self loathing.

The fact of the matter is that not everyone can succeed. I don't think most people would even argue against this. But what people ignore is the consequences of this. Most people will be failures by conventional standards. Of course, the follow up is usually then trying to redefine the terms of failing to encompass different types of success. But I find it curious how no one really attacks these notions of success.

Why *do* we need to achieve success? Why *do* we need to achieve prestigious fellowships, publications, acknowledgements, etc.? If you think we don't *need* to, then let me ask the individual how much they are pesronally motivated? We are taught this is socially desirable, something that needs to be done to achieve some kind of success that we all value.

No one attacks this, but there is all the pressure for failing individuals to conform to success. After they failed they can then focus on redefining success sin order to fit into some kind of definition.

This can cause a lot of misery for those who tried but couldn't succeed on similar facets.

As more and more people are born, more and more college students graduate and try to get into grad programs, but the rate of accepting graduate students has not increased at the same rate. And the rate of arbitrary success measures haven't even really increased at all (especially with a cut of funding for prestige). So what do we get from this, a growing population of generation of people who have to redefine success for themselves since they couldn't "go far".

Of course, there are so many reasons that this can be. With more competition, it gets harder to get into programs, and then it gets harder to compete for the prestige. Inevitably, people are going to succeed by margins and luck than any true merit, and yet these people have been sorted into the failure bin who weren't able to get far.

But then what? Oh there's just different methods of going far. But why do we preach this stuff if we have to constantly make up new terms? At what point are we just going to call out the bullshit and stop pretending we have to fit into these categories. This is what I mean when I say we *need* to succeed. If we didn't we wouldn't make up new categories when we fail out of another.

Is there no wonder there's a growing population of discontent in the country? Because this doesn't just apply to graduate school and academia. The same notions can be applied pretty much anywhere, sometimes to a much more obvious extent like with being a successful artist or writer.

I've grown to despise pop-culture notions intelligentsia. Not because it is due to projecting insecurities (well, it somewhat is, and I have to try to clear my mind of those emotions while constructing my arguments), but because it promotes the same societal rot of success.

Is it so wrong to tell people they don't need to succeed in anything per se. Well probably because that might not even be inherently true and also because that in itself might create a lot of issues inter-personally that would grow to societal.

It's just the issue to me is so clear and I feel as though I am the only one who wishes to acknowledge it. But it is faux paw to bring it up while in my program even though promoting the culture of success that makes grad students suicidal (sometime even homicidal) is ok and expected. It's bizarre has made me unhealthily spiteful.

The question remains what to do. The number one think would be to acknowledge success for what it is. An issue that needs to be killed off in search of something that can be more fulfilling to everyone, and something we don't have to constantly lie to ourselves about.

I'll get no acknowledgement for these thoughts by big wigs, partially because no one will even see this, but partially because people will object if they did (as they should, all arguments can be scrupled). My question though is how much of the motivation to rebuttal these ideas is motivated by protecting your own notion of your own success? Would a "failure" be more likely to agree? Would that be just due to their motivated reasoning? Well what about the motivated reasoning of the successful? If I were to say the failure is just as capable or intelligent as the successful, would you take them more seriously or would you think them as bitter?

There's more failures than the successful out there, and this ratio will become even more skewed towards failure. There's a lot of motivated reasoning out there that people partake in.

Motivated reasoning is not bad. I was motivated to this position by my own bad experiences, but this doesn't mean I am wrong. Those who have been more successful will be more motivated to disagree with me innately, but of course maybe they could be right.

I personally wish people would rather support the opinions I say, as they lead to possibilities to uplift more people than defend the few who can succeed.

Thoughts that will keep me as a black sheep.
