<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Michael Woller">

<title>Simple Linear Regression – InfoGothic</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/favicon.ico" rel="icon">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-f418161beb48e0141c760e455f12af2c.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-4d14f3be7bc8eb7ec2287338953877e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">InfoGothic</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../tutorials.html"> 
<span class="menu-text">Courses &amp; Tutorials</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../blog-posts.html"> 
<span class="menu-text">Blog Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://notes.infogothic.com"> 
<span class="menu-text">Obsidian Notes</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/michaelwoller"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://bsky.app/profile/infogothic.bsky.social"> <i class="bi bi-bluesky" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#correlations-in-r" id="toc-correlations-in-r" class="nav-link" data-scroll-target="#correlations-in-r">1. Correlations in R</a>
  <ul class="collapse">
  <li><a href="#correlations-with-cor" id="toc-correlations-with-cor" class="nav-link" data-scroll-target="#correlations-with-cor">Correlations with <code>cor()</code></a></li>
  </ul></li>
  <li><a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link" data-scroll-target="#simple-linear-regression">2. Simple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#fitting-simple-linear-regression-with-lm" id="toc-fitting-simple-linear-regression-with-lm" class="nav-link" data-scroll-target="#fitting-simple-linear-regression-with-lm">Fitting Simple Linear Regression with lm()</a></li>
  <li><a href="#interpretations-of-coefficients" id="toc-interpretations-of-coefficients" class="nav-link" data-scroll-target="#interpretations-of-coefficients">Interpretations of Coefficients</a></li>
  <li><a href="#what-is-stored-in-the-model-object" id="toc-what-is-stored-in-the-model-object" class="nav-link" data-scroll-target="#what-is-stored-in-the-model-object">What Is Stored in the Model Object?</a></li>
  <li><a href="#alternative-functions-for-extracting-model-information" id="toc-alternative-functions-for-extracting-model-information" class="nav-link" data-scroll-target="#alternative-functions-for-extracting-model-information">Alternative Functions for Extracting Model Information</a></li>
  <li><a href="#save-residuals-and-predicted-values-with-transform" id="toc-save-residuals-and-predicted-values-with-transform" class="nav-link" data-scroll-target="#save-residuals-and-predicted-values-with-transform">Save Residuals and Predicted Values with transform()</a></li>
  <li><a href="#save-them-with-the-operator" id="toc-save-them-with-the-operator" class="nav-link" data-scroll-target="#save-them-with-the-operator">Save Them with the <code>$</code> Operator</a></li>
  </ul></li>
  <li><a href="#plotting-the-data-and-the-model" id="toc-plotting-the-data-and-the-model" class="nav-link" data-scroll-target="#plotting-the-data-and-the-model">3. Plotting the Data and the Model</a>
  <ul class="collapse">
  <li><a href="#using-gf_point-for-raw-data" id="toc-using-gf_point-for-raw-data" class="nav-link" data-scroll-target="#using-gf_point-for-raw-data">Using <code>gf_point()</code> for Raw Data</a></li>
  <li><a href="#using-gf_lm-to-fit-a-line" id="toc-using-gf_lm-to-fit-a-line" class="nav-link" data-scroll-target="#using-gf_lm-to-fit-a-line">Using <code>gf_lm()</code> to Fit a Line</a></li>
  <li><a href="#using-gf_point-for-predicted-scores" id="toc-using-gf_point-for-predicted-scores" class="nav-link" data-scroll-target="#using-gf_point-for-predicted-scores">Using <code>gf_point()</code> for Predicted Scores</a></li>
  <li><a href="#using-gf_point-for-residuals" id="toc-using-gf_point-for-residuals" class="nav-link" data-scroll-target="#using-gf_point-for-residuals">Using <code>gf_point()</code>() for Residuals</a></li>
  <li><a href="#using-plot-for-raw-data" id="toc-using-plot-for-raw-data" class="nav-link" data-scroll-target="#using-plot-for-raw-data">Using <code>plot()</code> for Raw Data</a></li>
  <li><a href="#fitting-regression-lines-on-plot" id="toc-fitting-regression-lines-on-plot" class="nav-link" data-scroll-target="#fitting-regression-lines-on-plot">Fitting Regression Lines on plot()</a></li>
  <li><a href="#plotting-predicted-scores-and-residuals-with-plot" id="toc-plotting-predicted-scores-and-residuals-with-plot" class="nav-link" data-scroll-target="#plotting-predicted-scores-and-residuals-with-plot">Plotting Predicted Scores and Residuals with <code>plot()</code></a></li>
  </ul></li>
  <li><a href="#well-done" id="toc-well-done" class="nav-link" data-scroll-target="#well-done">Well Done!</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Simple Linear Regression</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Michael Woller </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 data-anchor-id="introduction">Introduction</h2>
<p>In this lesson we will cover simple linear regression by predicting one continuous outcome from one continuous predictor. We will start with correlations, then move into fitting and interpreting regression models, extracting model information, and plotting results using both <code>ggformula</code> and base R. Note, this lesson assumes you have a basic understanding of R, though I will touch on some of R as we go. The interactable shiny app for this lesson has intro to R material in it, if you wish to review.</p>
<p>We will be using the built-in <code>faithful</code> dataset, which contains data on eruptions of the Old Faithful geyser in Yellowstone National Park. The dataset consists of two columns:</p>
<ul>
<li><code>eruptions</code> - the length of an Old Faithful eruption (in minutes)</li>
<li><code>waiting</code> - the length between Old Faithful eruptions (in minutes)</li>
</ul>
<hr>
</section>
<section id="correlations-in-r" class="level2">
<h2 data-anchor-id="correlations-in-r">1. Correlations in R</h2>
<section id="correlations-with-cor" class="level3">
<h3 data-anchor-id="correlations-with-cor">Correlations with <code>cor()</code></h3>
<p>Before fitting a regression model, it is often useful to look at the correlation between the predictor and the outcome. You can use the <code>cor()</code> function in R to find a correlation between two variables.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(faithful<span class="sc">$</span>eruptions, faithful<span class="sc">$</span>waiting)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9008112</code></pre>
</div>
</div>
<p>This computes the Pearson correlation between <code>eruptions</code> and <code>waiting</code>. For those who are new to R, the <code>$</code> operator lets you select specific variables from a dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>faithful<span class="sc">$</span>eruptions</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 3.600 1.800 3.333 2.283 4.533 2.883 4.700 3.600 1.950 4.350 1.833 3.917
 [13] 4.200 1.750 4.700 2.167 1.750 4.800 1.600 4.250 1.800 1.750 3.450 3.067
 [25] 4.533 3.600 1.967 4.083 3.850 4.433 4.300 4.467 3.367 4.033 3.833 2.017
 [37] 1.867 4.833 1.833 4.783 4.350 1.883 4.567 1.750 4.533 3.317 3.833 2.100
 [49] 4.633 2.000 4.800 4.716 1.833 4.833 1.733 4.883 3.717 1.667 4.567 4.317
 [61] 2.233 4.500 1.750 4.800 1.817 4.400 4.167 4.700 2.067 4.700 4.033 1.967
 [73] 4.500 4.000 1.983 5.067 2.017 4.567 3.883 3.600 4.133 4.333 4.100 2.633
 [85] 4.067 4.933 3.950 4.517 2.167 4.000 2.200 4.333 1.867 4.817 1.833 4.300
 [97] 4.667 3.750 1.867 4.900 2.483 4.367 2.100 4.500 4.050 1.867 4.700 1.783
[109] 4.850 3.683 4.733 2.300 4.900 4.417 1.700 4.633 2.317 4.600 1.817 4.417
[121] 2.617 4.067 4.250 1.967 4.600 3.767 1.917 4.500 2.267 4.650 1.867 4.167
[133] 2.800 4.333 1.833 4.383 1.883 4.933 2.033 3.733 4.233 2.233 4.533 4.817
[145] 4.333 1.983 4.633 2.017 5.100 1.800 5.033 4.000 2.400 4.600 3.567 4.000
[157] 4.500 4.083 1.800 3.967 2.200 4.150 2.000 3.833 3.500 4.583 2.367 5.000
[169] 1.933 4.617 1.917 2.083 4.583 3.333 4.167 4.333 4.500 2.417 4.000 4.167
[181] 1.883 4.583 4.250 3.767 2.033 4.433 4.083 1.833 4.417 2.183 4.800 1.833
[193] 4.800 4.100 3.966 4.233 3.500 4.366 2.250 4.667 2.100 4.350 4.133 1.867
[205] 4.600 1.783 4.367 3.850 1.933 4.500 2.383 4.700 1.867 3.833 3.417 4.233
[217] 2.400 4.800 2.000 4.150 1.867 4.267 1.750 4.483 4.000 4.117 4.083 4.267
[229] 3.917 4.550 4.083 2.417 4.183 2.217 4.450 1.883 1.850 4.283 3.950 2.333
[241] 4.150 2.350 4.933 2.900 4.583 3.833 2.083 4.367 2.133 4.350 2.200 4.450
[253] 3.567 4.500 4.150 3.817 3.917 4.450 2.000 4.283 4.767 4.533 1.850 4.250
[265] 1.983 2.250 4.750 4.117 2.150 4.417 1.817 4.467</code></pre>
</div>
</div>
<p>If your dataset contains missing values, <code>cor()</code> can fail unless you tell R how to handle them.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(faithful<span class="sc">$</span>eruptions, faithful<span class="sc">$</span>waiting, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9008112</code></pre>
</div>
</div>
<p>The option <code>use = "complete.obs"</code> tells R to use only cases that have non-missing values on both variables.</p>
<p>You can interpret this correlation value as a standardized difference. Old Faithful eruption length are highly correlated with its waiting time between eruptions with cor = .9. In reality, the correlation just tells how many standard deviations apart are two eruption lengths.</p>
<p>A full and proper definition would follow as: between two eruptions of Old Faithful that differ in one standard deviation of eruption length, we expect the longer eruption length to also have a .9 standard deviation increase in wait time for the next eruption.</p>
<hr>
</section>
</section>
<section id="simple-linear-regression" class="level2">
<h2 data-anchor-id="simple-linear-regression">2. Simple Linear Regression</h2>
<p>A simple linear regression asks whether one variable (the predictor) helps us predict another variable (the outcome).</p>
<p>Here:</p>
<ul>
<li>Outcome (Y) = <code>waiting</code></li>
<li>Predictor (X) = <code>eruptions</code></li>
</ul>
<section id="fitting-simple-linear-regression-with-lm" class="level3">
<h3 data-anchor-id="fitting-simple-linear-regression-with-lm">Fitting Simple Linear Regression with lm()</h3>
<p>Use <code>lm()</code> to fit a linear model (“lm” stands for “linear model”). The following code does a linear regression predicting wait time from eruptions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>faithful_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(waiting <span class="sc">~</span> eruptions, <span class="at">data =</span> faithful)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The <code>~</code> can be viewed as an <code>=</code> sign for the purpose of regression. The formula <code>waiting ~ eruptions</code> means: predict <code>waiting</code> from <code>eruptions</code>.</p>
<p>The <code>faithful_model</code> object contains much information about the regression. However, to extract the information, you need to do different things. Simply entering the model will only give you the coefficients (intercept and slope).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>faithful_model</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = waiting ~ eruptions, data = faithful)

Coefficients:
(Intercept)    eruptions  
      33.47        10.73  </code></pre>
</div>
</div>
<p>Typically, people use the <code>summary()</code> function to get a display of the majority of relevant model output.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(faithful_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = waiting ~ eruptions, data = faithful)

Residuals:
     Min       1Q   Median       3Q      Max 
-12.0796  -4.4831   0.2122   3.9246  15.9719 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  33.4744     1.1549   28.98   &lt;2e-16 ***
eruptions    10.7296     0.3148   34.09   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.914 on 270 degrees of freedom
Multiple R-squared:  0.8115,    Adjusted R-squared:  0.8108 
F-statistic:  1162 on 1 and 270 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The <code>summary()</code> output gives useful model information, including:</p>
<ul>
<li>Regression coefficient values (under Estimate)</li>
<li>Standard errors (under Std. Error)</li>
<li>t test statistics (under t value)</li>
<li>p values (under Pr(&gt;|t|))</li>
</ul>
<p>For ease, significance coding (for a criteria of .05) is given in <code>*</code> asterisks. At the top of the output, you can also see the general range of residual values. At the bottom, you can see other model fit statistics:</p>
<ul>
<li>Residual Standard Error (RSE) gives the typical size of prediction error</li>
<li>Multiple <span class="math inline">\(R^2\)</span> is the <span class="math inline">\(R^2\)</span> for the model</li>
<li>Adjusted <span class="math inline">\(R^2\)</span> is the adjusted-<span class="math inline">\(R^2\)</span> for the model</li>
<li>F-statistic and the values in that line is the F test for the model <span class="math inline">\(R^2\)</span></li>
</ul>
<p>If you want confidence intervals, you need to use the <code>confint()</code> function.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(faithful_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>               2.5 %   97.5 %
(Intercept) 31.20069 35.74810
eruptions   10.10996 11.34932</code></pre>
</div>
</div>
</section>
<section id="interpretations-of-coefficients" class="level3">
<h3 data-anchor-id="interpretations-of-coefficients">Interpretations of Coefficients</h3>
<p>Recall that interpretations need to discuss differences between two points, need to mention expected/predicted outcome values, and need to mention directionality (which is the direction of the relationship—positive or negative). Avoid within-subject causal language like “change” or “increase” because a regression model is comparing two separate data points, not changing the same point of data.</p>
<p><strong>Intercept:</strong></p>
<blockquote class="blockquote">
<p>For an Old Faithful eruption that lasted 0 minutes, the wait time is expected to be 33.47 minutes. Obviously this doesn’t make sense given the context.</p>
</blockquote>
<p><strong>Slope:</strong></p>
<blockquote class="blockquote">
<p>For two different Old Faithful eruptions that differ in their length by one minute, there is expected to be a 10.73 minute longer wait time for the longer eruption.</p>
</blockquote>
<p>This is a rather finicky definition, but it is technically correct. Most people interpret regression coefficients improperly with “change” type language, which implies that we are taking an individual point and maneuvering it, but this isn’t true. We are simply looking at average differences between two independent eruptions. This technicality is almost universally ignored, to the point that, practically, no one cares. But if you want to do proper psychological research you need to be aware that you are <em>not</em> making causal judgement here! That is a whole unique domain within psychological statistics.</p>
</section>
<section id="what-is-stored-in-the-model-object" class="level3">
<h3 data-anchor-id="what-is-stored-in-the-model-object">What Is Stored in the Model Object?</h3>
<p>When you fit a model in R, the result is stored as an <code>lm</code> object. To check you can use <code>class()</code>, which tells you the class of any R object.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(faithful_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "lm"</code></pre>
</div>
</div>
<p><code>lm</code> objects contain many pieces of information about whichever regression model they represent. The <code>attributes()</code> function gives a list of everything within an object.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(faithful_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$names
 [1] "coefficients"  "residuals"     "effects"       "rank"         
 [5] "fitted.values" "assign"        "qr"            "df.residual"  
 [9] "xlevels"       "call"          "terms"         "model"        

$class
[1] "lm"</code></pre>
</div>
</div>
<p>Here, under <code>$names</code> (<code>names</code> being a placeholder), we can see everything that R has automatically calculated. Some especially important pieces are the following (note, I am putting each into the <code>head()</code> function to keep the output to only give me the first 10 of the outputs as opposed to hundreds of points):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>faithful_model<span class="sc">$</span>coefficients        <span class="co"># regression coefficients</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)   eruptions 
   33.47440    10.72964 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(faithful_model<span class="sc">$</span>residuals)     <span class="co"># residuals</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3         4         5         6 
 6.898894  1.212248  4.763708  4.029832  2.888139 -9.407953 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(faithful_model<span class="sc">$</span>fitted.values) <span class="co"># predicted values</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6 
72.10111 52.78775 69.23629 57.97017 82.11186 64.40795 </code></pre>
</div>
</div>
<ul>
<li><code>coefficients</code>: the estimated intercept and slope</li>
<li><code>residuals</code>: the difference between observed and predicted scores</li>
<li><code>fitted.values</code>: the predicted Y values from the regression line</li>
</ul>
<p>Recall that a predicted score is the model’s estimated value of Y for each case. A residual is the difference between the observed Y value and the predicted Y value. In other words: residual = observed score - predicted score. If the residual is large, the model predicted that case poorly. If the residual is small, the model predicted that case well.</p>
<p>Since these two values are so universally used, there is actually shorthand for them:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>faithful_model<span class="sc">$</span>coef</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)   eruptions 
   33.47440    10.72964 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(faithful_model<span class="sc">$</span>resid)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3         4         5         6 
 6.898894  1.212248  4.763708  4.029832  2.888139 -9.407953 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(faithful_model<span class="sc">$</span>fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6 
72.10111 52.78775 69.23629 57.97017 82.11186 64.40795 </code></pre>
</div>
</div>
</section>
<section id="alternative-functions-for-extracting-model-information" class="level3">
<h3 data-anchor-id="alternative-functions-for-extracting-model-information">Alternative Functions for Extracting Model Information</h3>
<p>There are also built-in functions that extract the same information.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(faithful_model)            <span class="co"># coefficients</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)   eruptions 
   33.47440    10.72964 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">resid</span>(faithful_model))     <span class="co"># residuals</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3         4         5         6 
 6.898894  1.212248  4.763708  4.029832  2.888139 -9.407953 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">predict</span>(faithful_model))   <span class="co"># predicted values</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6 
72.10111 52.78775 69.23629 57.97017 82.11186 64.40795 </code></pre>
</div>
</div>
<p>These functions are often preferred because they work across many different model objects, not just <code>lm()</code> models.</p>
</section>
<section id="save-residuals-and-predicted-values-with-transform" class="level3">
<h3 data-anchor-id="save-residuals-and-predicted-values-with-transform">Save Residuals and Predicted Values with transform()</h3>
<p>One way to save new variables into the dataset is with <code>transform()</code>. This function mutates your inputted dataset with whatever new variables you specify.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>faithful <span class="ot">&lt;-</span> <span class="fu">transform</span>(faithful, </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">faithful_resid =</span> <span class="fu">resid</span>(faithful_model),</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">faithful_pred  =</span> <span class="fu">predict</span>(faithful_model))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This adds two new variables to the <code>faithful</code> dataset: <code>faithful_resid</code> = residual scores and <code>faithful_pred</code> = predicted scores. You can choose different variable names if you want.</p>
</section>
<section id="save-them-with-the-operator" class="level3">
<h3 data-anchor-id="save-them-with-the-operator">Save Them with the <code>$</code> Operator</h3>
<p>Another way to save new variables is with the <code>$</code> operator. This method is very useful since it is quick. You can do this with any variable so long as its length matches the number of rows in the dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>faithful<span class="sc">$</span>res  <span class="ot">&lt;-</span> <span class="fu">resid</span>(faithful_model)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>faithful<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(faithful_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This does the same thing as <code>transform()</code>, but on separate lines. The general pattern is: <code>dataset$new_variable &lt;- values</code>.</p>
<hr>
</section>
</section>
<section id="plotting-the-data-and-the-model" class="level2">
<h2 data-anchor-id="plotting-the-data-and-the-model">3. Plotting the Data and the Model</h2>
<p>Graphs are extremely useful in regression because they help us see the relationship between X and Y directly. We will focus on basic scatterplots. There are many methods of plotting. We will mainly be using the <code>ggformula</code> package, but we will also show the default R function.</p>
<p>A scatterplot shows the relationship between two quantitative variables. Here, X-axis = <code>eruptions</code> and Y-axis = <code>waiting</code>. Each point represents one observation in the dataset.</p>
<ul>
<li>If the points generally move upward from left to right, that suggests a positive relationship.</li>
<li>If they move downward from left to right, that suggests a negative relationship.</li>
</ul>
<p>For plotting regression lines: the regression line shows the predicted value of <code>waiting</code> for each value of <code>eruptions</code>. In other words, the line is the model’s best-fitting straight line through the data.</p>
<p>For residual plots: residuals tell us how far each observed score is from the model’s predicted score. For a well-behaved linear regression model, we generally want residuals to be scattered around 0 without a strong pattern. If the residuals show a curve, funnel shape, or clustering pattern, that can suggest problems with model assumptions.</p>
<section id="using-gf_point-for-raw-data" class="level3">
<h3 data-anchor-id="using-gf_point-for-raw-data">Using <code>gf_point()</code> for Raw Data</h3>
<p>The <code>gf_point()</code> function from the <code>ggformula</code> package gives a large variety of options for visualization. The benefit of this function is that you can conveniently specify your model within the function instead of plugging in variables manually. Though there are almost an uncountable ammount of methods you can do plotting in R.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(waiting <span class="sc">~</span> eruptions, <span class="at">data =</span> faithful)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="simple-linear-regression_files/figure-html/gf-scatter-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="using-gf_lm-to-fit-a-line" class="level3">
<h3 data-anchor-id="using-gf_lm-to-fit-a-line">Using <code>gf_lm()</code> to Fit a Line</h3>
<p>In <code>ggformula</code>, you can add the fitted regression line with <code>gf_lm()</code>. You have to first add a piping operator from the <code>dplyr</code> package at the end of the <code>gf_point()</code> function.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(waiting <span class="sc">~</span> eruptions, <span class="at">data =</span> faithful) <span class="sc">%&gt;%</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lm</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="simple-linear-regression_files/figure-html/gf-lm-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This line matches the predicted scores from the regression.</p>
</section>
<section id="using-gf_point-for-predicted-scores" class="level3">
<h3 data-anchor-id="using-gf_point-for-predicted-scores">Using <code>gf_point()</code> for Predicted Scores</h3>
<p>Since <code>gf_point()</code> works on a selected dataset, you need your dataset to have the predicted scores saved within it.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(faithful_pred <span class="sc">~</span> eruptions, <span class="at">data =</span> faithful)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="simple-linear-regression_files/figure-html/gf-pred-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="using-gf_point-for-residuals" class="level3">
<h3 data-anchor-id="using-gf_point-for-residuals">Using <code>gf_point()</code>() for Residuals</h3>
<p>Same stipulations for the predicted scores using <code>gf_point()</code> matter here.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(faithful_resid <span class="sc">~</span> eruptions, <span class="at">data =</span> faithful)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="simple-linear-regression_files/figure-html/gf-resid-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="using-plot-for-raw-data" class="level3">
<h3 data-anchor-id="using-plot-for-raw-data">Using <code>plot()</code> for Raw Data</h3>
<p>Base R has the <code>plot()</code> function that can give basic scatterplots. I mainly use <code>plot()</code> for very quick visualizations to just get the idea of what data looks like. There are two methods. Manually specifying the variables using the <code>$</code> operator:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(faithful<span class="sc">$</span>eruptions, faithful<span class="sc">$</span>waiting)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="simple-linear-regression_files/figure-html/base-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>You could also do this using the <code>with()</code> function, where you basically say do <code>plot()</code> with <code>faithful</code>. Whichever method is up to you.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(faithful, <span class="fu">plot</span>(eruptions, waiting))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="simple-linear-regression_files/figure-html/with-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="fitting-regression-lines-on-plot" class="level3">
<h3 data-anchor-id="fitting-regression-lines-on-plot">Fitting Regression Lines on plot()</h3>
<p>If you want to add a fitted line with <code>plot()</code>, use <code>abline()</code> with your model object in the next line. This will add the line on top of the previously generated plot.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(faithful, <span class="fu">plot</span>(eruptions, waiting))</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(faithful_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="simple-linear-regression_files/figure-html/abline-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="plotting-predicted-scores-and-residuals-with-plot" class="level3">
<h3 data-anchor-id="plotting-predicted-scores-and-residuals-with-plot">Plotting Predicted Scores and Residuals with <code>plot()</code></h3>
<p>There is nothing special about this. Just take wherever you saved the predicted scores and residuals and put them in <code>plot()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(faithful<span class="sc">$</span>faithful_pred, faithful<span class="sc">$</span>waiting)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="simple-linear-regression_files/figure-html/plot-pred-resid-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(faithful<span class="sc">$</span>faithful_resid, faithful<span class="sc">$</span>waiting)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="simple-linear-regression_files/figure-html/plot-pred-resid-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="well-done" class="level2">
<h2 data-anchor-id="well-done">Well Done!</h2>
<p>You have completed the Simple Linear Regression tutorial. Here is a summary of what was covered:</p>
<ul>
<li>Computing correlations with <code>cor()</code> and handling missing values with <code>use = "complete.obs"</code></li>
<li>Fitting simple linear regression with <code>lm()</code> and reading the <code>summary()</code> output</li>
<li>Interpreting intercept and slope coefficients correctly</li>
<li>Extracting model components with <code>$</code> notation and functions like <code>coef()</code>, <code>resid()</code>, and <code>predict()</code></li>
<li>Saving residuals and predicted values with <code>transform()</code> and the <code>$</code> operator</li>
<li>Plotting raw data, regression lines, predicted scores, and residuals with <code>ggformula</code> and base R</li>
</ul>
<p>The next lesson covers multiple linear regression.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/infogothic\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>