<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Michael Woller">

<title>Nonlinear Regression – InfoGothic</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-f418161beb48e0141c760e455f12af2c.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-4d14f3be7bc8eb7ec2287338953877e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
document.addEventListener("DOMContentLoaded", function() {
  var nav = document.querySelector(".navbar-nav");
  var li = document.createElement("li");
  li.className = "nav-item";
  li.innerHTML = '<a class="nav-link ml-onclick-form" href="javascript:void(0)" onclick="ml(\'show\', \'18mxag\', true)">Mail List</a>';
  var icons = nav.querySelector(".nav-item:has(.bi)");
  nav.insertBefore(li, icons);
});
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Nonlinear Regression – InfoGothic">
<meta property="og:description" content="Gothic Flavor of Statistics, Psychology, Economics">
<meta property="og:image" content="https://infogothic.com/tutorials/regression-lessons/nonlinear-regression_files/figure-html/viz-nonlinear-1.png">
<meta property="og:site_name" content="InfoGothic">
<meta property="og:image:height" content="960">
<meta property="og:image:width" content="1344">
<meta name="twitter:title" content="Nonlinear Regression – InfoGothic">
<meta name="twitter:description" content="Gothic Flavor of Statistics, Psychology, Economics">
<meta name="twitter:image" content="https://infogothic.com/tutorials/regression-lessons/nonlinear-regression_files/figure-html/viz-nonlinear-1.png">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">InfoGothic</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../tutorials.html"> 
<span class="menu-text">Courses &amp; Tutorials</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog-posts.html"> 
<span class="menu-text">Blog Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://publish.obsidian.md/infogothic/Home"> 
<span class="menu-text">Open Notes</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/michaelwoller"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://bsky.app/profile/infogothic.bsky.social"> <i class="bi bi-bluesky" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#the-dataset" id="toc-the-dataset" class="nav-link" data-scroll-target="#the-dataset">The Dataset</a></li>
  </ul></li>
  <li><a href="#visualizing-nonlinearity" id="toc-visualizing-nonlinearity" class="nav-link" data-scroll-target="#visualizing-nonlinearity">1. Visualizing Nonlinearity</a></li>
  <li><a href="#polynomial-models" id="toc-polynomial-models" class="nav-link" data-scroll-target="#polynomial-models">2. Polynomial Models</a>
  <ul class="collapse">
  <li><a href="#what-is-a-polynomial-model" id="toc-what-is-a-polynomial-model" class="nav-link" data-scroll-target="#what-is-a-polynomial-model">What Is a Polynomial Model?</a></li>
  <li><a href="#fitting-a-quadratic-model" id="toc-fitting-a-quadratic-model" class="nav-link" data-scroll-target="#fitting-a-quadratic-model">Fitting a Quadratic Model</a></li>
  <li><a href="#plotting-polynomial-models" id="toc-plotting-polynomial-models" class="nav-link" data-scroll-target="#plotting-polynomial-models">Plotting Polynomial Models</a></li>
  </ul></li>
  <li><a href="#piecewise-regression" id="toc-piecewise-regression" class="nav-link" data-scroll-target="#piecewise-regression">3. Piecewise Regression</a>
  <ul class="collapse">
  <li><a href="#what-is-piecewise-regression" id="toc-what-is-piecewise-regression" class="nav-link" data-scroll-target="#what-is-piecewise-regression">What Is Piecewise Regression?</a></li>
  <li><a href="#segmented-piecewise-regression" id="toc-segmented-piecewise-regression" class="nav-link" data-scroll-target="#segmented-piecewise-regression">Segmented Piecewise Regression</a></li>
  <li><a href="#joint-piecewise-regression" id="toc-joint-piecewise-regression" class="nav-link" data-scroll-target="#joint-piecewise-regression">Joint Piecewise Regression</a></li>
  </ul></li>
  <li><a href="#log-transformations" id="toc-log-transformations" class="nav-link" data-scroll-target="#log-transformations">4. Log Transformations</a>
  <ul class="collapse">
  <li><a href="#what-is-a-log-transformation" id="toc-what-is-a-log-transformation" class="nav-link" data-scroll-target="#what-is-a-log-transformation">What Is a Log Transformation?</a></li>
  <li><a href="#visualizing-log-transformations" id="toc-visualizing-log-transformations" class="nav-link" data-scroll-target="#visualizing-log-transformations">Visualizing Log Transformations</a></li>
  <li><a href="#log-transformation-interpretations" id="toc-log-transformation-interpretations" class="nav-link" data-scroll-target="#log-transformation-interpretations">Log Transformation Interpretations</a></li>
  <li><a href="#box-cox-transformations" id="toc-box-cox-transformations" class="nav-link" data-scroll-target="#box-cox-transformations">Box-Cox Transformations</a></li>
  </ul></li>
  <li><a href="#well-done" id="toc-well-done" class="nav-link" data-scroll-target="#well-done">Well Done!</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Nonlinear Regression</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Michael Woller </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 data-anchor-id="introduction">Introduction</h2>
<p>Though it might seem like an oxymoron, linear regression can be used to model <strong>nonlinear relationships</strong>. The “linear” in linear regression actually refers to the fact that the model is linear in its <em>coefficients</em> (the betas), not that the relationship between the predictors and the outcome must be a straight line. This means we can include transformed predictors - such as squared terms, cubic terms, or other functions of variables - to capture curved relationships, while still estimating the model using linear regression techniques.</p>
<p>For example, including a term like <span class="math inline">\(X^2\)</span> allows the model to fit a curve rather than a straight line. As long as the model remains linear in the coefficients (e.g., <span class="math inline">\(\beta_1 X + \beta_2 X^2\)</span>), it is still considered a linear model, even though the relationship between X and the outcome is nonlinear.</p>
<p>There are multiple types of nonlinear models you can run depending on what type of nonlinearity is present in the data.</p>
<section id="the-dataset" class="level3">
<h3 data-anchor-id="the-dataset">The Dataset</h3>
<p>For this lesson we will use a <strong>haunted house</strong> dataset that was collected after individuals walked through a haunted house that some psychologists cooked up. Specifically, for this lesson, of interest was a “piggy” jump scare, in which someone in a pig mask jumps out with a chainsaw. The data we will look at is:</p>
<ul>
<li><code>FearPiggy</code> — how much you were afraid of the piggy jump scare (1–10 scale)</li>
<li><code>EnjoyPiggy</code> — how much you enjoyed the piggy jump scare (1–10 scale)</li>
</ul>
<p>We are exploring the nonlinearity of how much an individual was afraid of a “piggy jump scare” at the haunted house (<code>FearPiggy</code>) in predicting how much they enjoyed the piggy jump scare (<code>EnjoymentPiggy</code>).</p>
<p>It is possible that individuals only enjoyed the piggy when it was not scary or was very scary, but did not care for it when it was moderately scary. This would be a nonlinear relationship.</p>
<p>Note, the dataset that was given to develop the lab lesson proved to not really have any nonlinearities (spoiler), so this isn’t the best example to teach with. If I ever get a hold on nonlinear data and can be bothered to come back and change some of these, I might in the future.</p>
<hr>
</section>
</section>
<section id="visualizing-nonlinearity" class="level2">
<h2 data-anchor-id="visualizing-nonlinearity">1. Visualizing Nonlinearity</h2>
<p>Typically it is important to visualize your data before finalizing your model, but this is especially the case when your model might be nonlinear. We need to see the type of nonlinearity present to determine what kind of nonlinear model to fit. If the relationship is a U shape, we might want a quadratic model. If it is more like a W, maybe a quartic model would be better.</p>
<p>We will be plotting using the <code>ggformula</code> package. Also make sure you have the <code>dplyr</code> package loaded in order to use the <code>%&gt;%</code> piping operator later on.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(EnjoymentPiggy <span class="sc">~</span> FearPiggy, <span class="at">data =</span> feardata) <span class="sc">+</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="nonlinear-regression_files/figure-html/viz-nonlinear-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The scatterplot does not seem super nonlinear, but you can see how the clustering of points starts to become lower on the ends of the plot. This might be due to some trace amount of nonlinearity in a <span class="math inline">\(\cap\)</span> shape. The fitted linear line is very flat, which suggests there may not be much of a linear relationship. However, keep in mind that a flat linear line can still manifest as a curved polynomial line (think how the average of a U shape would still amount to a flat line).</p>
<p>To further investigate, we can plot the residuals against <code>FearPiggy</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>linear_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(EnjoymentPiggy <span class="sc">~</span> FearPiggy, <span class="at">data =</span> feardata)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">resid</span>(linear_model) <span class="sc">~</span> FearPiggy, <span class="at">data =</span> feardata) <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="nonlinear-regression_files/figure-html/residual-viz-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>By looking at the left and right ends of the plot, we can see the largest deviations from the predicted line. Our straight line fits the worst at the ends, which is roughly what we took away from the previous plot. These residual plots are helpful at diagnosing at what points in the predictor range the linear line fits the worst.</p>
<p><em>Note: the nonlinear models also do not fit very well in this dataset - it was not originally designed with a strong nonlinear relationship. The goal here is to learn the methods, not to find significant effects.</em></p>
<hr>
</section>
<section id="polynomial-models" class="level2">
<h2 data-anchor-id="polynomial-models">2. Polynomial Models</h2>
<section id="what-is-a-polynomial-model" class="level3">
<h3 data-anchor-id="what-is-a-polynomial-model">What Is a Polynomial Model?</h3>
<p>A polynomial line is a line that has one or more inflection points (a local minimum or maximum). Polynomial lines are determined by an exponential:</p>
<ul>
<li><span class="math inline">\(X\)</span> = straight line (not polynomial)</li>
<li><span class="math inline">\(X^2\)</span> = quadratic line (one minimum or maximum, basically a U shape)</li>
<li><span class="math inline">\(X^3\)</span> = cubic line (one minimum and one maximum)</li>
</ul>
<p>Typically a cubic line is the highest you will go, as models with higher exponents are very rare, and you want to avoid <strong>overfitting</strong>. This would be building a model that fits the current dataset so closely (including random noise) that it does not generalize well to the population.</p>
<p>Whenever you make a polynomial line, you must include all lower-degree terms. For a quadratic model: <span class="math display">\[Y = b_0 + b_1 X + b_2 X^2\]</span></p>
<p>For a cubic model: <span class="math display">\[Y = b_0 + b_1 X + b_2 X^2 + b_3 X^3\]</span></p>
</section>
<section id="fitting-a-quadratic-model" class="level3">
<h3 data-anchor-id="fitting-a-quadratic-model">Fitting a Quadratic Model</h3>
<p>You have two options. Option 1 is to create a new squared variable:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>feardata<span class="sc">$</span>FearPiggy2 <span class="ot">&lt;-</span> feardata<span class="sc">$</span>FearPiggy<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>polynomial_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(EnjoymentPiggy <span class="sc">~</span> FearPiggy <span class="sc">+</span> FearPiggy2, <span class="at">data =</span> feardata)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(polynomial_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = EnjoymentPiggy ~ FearPiggy + FearPiggy2, data = feardata)

Residuals:
   Min     1Q Median     3Q    Max 
-5.770 -2.573  1.009  2.797  3.648 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  5.35235    1.07042   5.000 2.48e-06 ***
FearPiggy    0.51208    0.46905   1.092    0.278    
FearPiggy2  -0.05175    0.04395  -1.177    0.242    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.114 on 99 degrees of freedom
Multiple R-squared:  0.01436,   Adjusted R-squared:  -0.005556 
F-statistic: 0.721 on 2 and 99 DF,  p-value: 0.4888</code></pre>
</div>
</div>
<p>Option 2 is to use the <code>I()</code> function inside <code>lm()</code>, which allows you to transform a variable mid-formula:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>polynomial_model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(EnjoymentPiggy <span class="sc">~</span> FearPiggy <span class="sc">+</span> <span class="fu">I</span>(FearPiggy<span class="sc">^</span><span class="dv">2</span>), <span class="at">data =</span> feardata)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(polynomial_model2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = EnjoymentPiggy ~ FearPiggy + I(FearPiggy^2), data = feardata)

Residuals:
   Min     1Q Median     3Q    Max 
-5.770 -2.573  1.009  2.797  3.648 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     5.35235    1.07042   5.000 2.48e-06 ***
FearPiggy       0.51208    0.46905   1.092    0.278    
I(FearPiggy^2) -0.05175    0.04395  -1.177    0.242    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.114 on 99 degrees of freedom
Multiple R-squared:  0.01436,   Adjusted R-squared:  -0.005556 
F-statistic: 0.721 on 2 and 99 DF,  p-value: 0.4888</code></pre>
</div>
</div>
<p>As we can see from these outputs, the quadratic line is not a good fit. The quadratic term is not significant (<span class="math inline">\(t(99) = -1.77\)</span>, <span class="math inline">\(p = .242\)</span>), so we fail to reject that there is a quadratic relationship. You can also do a <span class="math inline">\(\Delta R^2\)</span> test with and without the nonlinear term to test this more formally.</p>
<p>Generally, you do not interpret the polynomial term because its interpretation does not make intuitive sense. You can interpret the linear <code>FearPiggy</code> as the linear relationship (similar to what is done normally).</p>
<p>If you want to understand the coefficient intuitively, you can think of the <span class="math inline">\(X^2\)</span> term as an interaction, where the effect of <code>FearPiggy</code> depends on the level of <code>FearPiggy</code> itself. Knowing the polynomial coefficient is about -.05, as <code>FearPiggy</code> increases, the effect of <code>FearPiggy</code> on <code>EnjoymentPiggy</code> decreases.</p>
</section>
<section id="plotting-polynomial-models" class="level3">
<h3 data-anchor-id="plotting-polynomial-models">Plotting Polynomial Models</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Residuals of the polynomial model</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">resid</span>(polynomial_model) <span class="sc">~</span> FearPiggy, <span class="at">data =</span> feardata)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="nonlinear-regression_files/figure-html/plot-polynomial-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predicted quadratic line (don't fit a geom_smooth line here)</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">predict</span>(polynomial_model) <span class="sc">~</span> FearPiggy, <span class="at">data =</span> feardata)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="nonlinear-regression_files/figure-html/plot-polynomial2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>NOTE: Do not be fooled by the shape here. Note the range of the Y-axis. It is very small, meaning the quadratic line is actually very flat, which is why it is non-significant.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot predicted scores and residuals together</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">resid</span>(polynomial_model) <span class="sc">~</span> FearPiggy, </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> feardata, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_point</span>(<span class="fu">predict</span>(polynomial_model) <span class="sc">~</span> FearPiggy, </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> feardata, <span class="at">color =</span> <span class="st">"blue"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="nonlinear-regression_files/figure-html/plot-both-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The residuals are generally much lower than the quadratic line predicted. As I said, you can see how the quadratic line is much flatter than the unadjusted plot shows. In conclusion, a polynomial nonlinear model was a poor fit for our data.</p>
<hr>
</section>
</section>
<section id="piecewise-regression" class="level2">
<h2 data-anchor-id="piecewise-regression">3. Piecewise Regression</h2>
<section id="what-is-piecewise-regression" class="level3">
<h3 data-anchor-id="what-is-piecewise-regression">What Is Piecewise Regression?</h3>
<p>Piecewise regression fits <strong>separate linear relationships</strong> across different ranges of a predictor variable by introducing one or more <strong>breakpoints</strong> (also called knots). Instead of assuming a single straight line describes the entire relationship, piecewise regression allows the slope to change at specified values of the predictor. This results in multiple line segments joined together at the breakpoints.</p>
<p>This is especially useful when the effect of a variable is not constant - for example, when a predictor has little effect up to a certain point and then becomes stronger, weaker, or changes direction. A common example is A/B clinical designs.</p>
<p>As a side note, piecewise regression is a type of “spline” regression. It is also related to moderation in both its interpretation and its function - the piecewise line is basically an interaction term! If you have not yet done the Moderation lesson, come back to this after.</p>
</section>
<section id="segmented-piecewise-regression" class="level3">
<h3 data-anchor-id="segmented-piecewise-regression">Segmented Piecewise Regression</h3>
<p>A segmented piecewise model fits two disconnected line segments with different slopes and intercepts.</p>
<p>First, create a breakpoint indicator variable (0 for values below the breakpoint, 1 for values at or above it). We will use <code>FearPiggy</code> = 5 as the breakpoint. Always include the breakpoint in the second line segment.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>feardata<span class="sc">$</span>XJ <span class="ot">&lt;-</span> (feardata<span class="sc">$</span>FearPiggy <span class="sc">&gt;=</span> <span class="dv">5</span>) <span class="co"># &gt;= is greater than or equal to</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the interaction for the second line segment's slope</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>feardata<span class="sc">$</span>FearPiggyXJ <span class="ot">&lt;-</span> (feardata<span class="sc">$</span>FearPiggy <span class="sc">*</span> feardata<span class="sc">$</span>XJ)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Then fit a model with the original predictor, the breakpoint indicator, and the interaction:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>piecewise1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(EnjoymentPiggy <span class="sc">~</span> FearPiggy <span class="sc">+</span> XJ <span class="sc">+</span> FearPiggyXJ, <span class="at">data =</span> feardata)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(piecewise1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = EnjoymentPiggy ~ FearPiggy + XJ + FearPiggyXJ, data = feardata)

Residuals:
   Min     1Q Median     3Q    Max 
-5.819 -2.256  1.027  2.898  3.197 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   5.8034     1.0854   5.347 5.85e-07 ***
FearPiggy     0.1132     0.3905   0.290    0.772    
XJTRUE        2.4426     2.5726   0.949    0.345    
FearPiggyXJ  -0.3829     0.4858  -0.788    0.432    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.138 on 98 degrees of freedom
Multiple R-squared:  0.009671,  Adjusted R-squared:  -0.02065 
F-statistic: 0.319 on 3 and 98 DF,  p-value: 0.8116</code></pre>
</div>
</div>
<p>Looking at the output:</p>
<ul>
<li>The slope of the first line segment (<code>FearPiggy</code> = .20) is not significant.</li>
<li><code>FearPiggyXJ</code> (-.42) is the <strong>difference</strong> between the slope of the first and second line segments. Since this is also not significant, there is no significant difference between the two slopes.</li>
</ul>
<p>To get the slope of the second line segment, add the two slopes together:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">0.3829</span> <span class="sc">-</span> <span class="fl">0.1132</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.4961</code></pre>
</div>
</div>
<p>To get the <strong>significance</strong> of the second line segment slope, switch the indicator coding and rerun:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>feardata<span class="sc">$</span>XJ2          <span class="ot">&lt;-</span> (feardata<span class="sc">$</span>FearPiggy <span class="sc">&lt;</span> <span class="dv">5</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>feardata<span class="sc">$</span>FearPiggyXJ2 <span class="ot">&lt;-</span> (feardata<span class="sc">$</span>FearPiggy <span class="sc">*</span> feardata<span class="sc">$</span>XJ2)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>piecewise2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(EnjoymentPiggy <span class="sc">~</span> FearPiggy <span class="sc">+</span> XJ2 <span class="sc">+</span> FearPiggyXJ2, <span class="at">data =</span> feardata)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(piecewise2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = EnjoymentPiggy ~ FearPiggy + XJ2 + FearPiggyXJ2, 
    data = feardata)

Residuals:
   Min     1Q Median     3Q    Max 
-5.819 -2.256  1.027  2.898  3.197 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    8.2460     2.3325   3.535 0.000624 ***
FearPiggy     -0.2697     0.2889  -0.933 0.352875    
XJ2TRUE       -2.4426     2.5726  -0.949 0.344726    
FearPiggyXJ2   0.3829     0.4858   0.788 0.432427    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.138 on 98 degrees of freedom
Multiple R-squared:  0.009671,  Adjusted R-squared:  -0.02065 
F-statistic: 0.319 on 3 and 98 DF,  p-value: 0.8116</code></pre>
</div>
</div>
<p>The slope of the second line segment is not significant. Note that the magnitude of the interaction is the same (.38) but the sign changes to keep the arithmetic consistent.</p>
<p><strong>Interpretation example (first segment slope):</strong></p>
<blockquote class="blockquote">
<p>For two individuals who are below a score of 5 in their fear of the piggy jump scare and differ in one unit of fear, the individual who was more afraid is expected to be about .11 point higher in their enjoyment of the piggy jump scare.</p>
</blockquote>
<p><strong>Interpretation example (interaction):</strong></p>
<blockquote class="blockquote">
<p>The difference in slopes for individuals who have a fear piggy score of less than 5 and those who have a score of 5 or greater is about .38.</p>
</blockquote>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">predict</span>(piecewise1) <span class="sc">~</span> FearPiggy, <span class="at">data =</span> feardata)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="nonlinear-regression_files/figure-html/segmented-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>You can see the two different line segments with different projections. Don’t be confused by the scale of the Y-axis. These are actually very small slopes. Adding the residuals shows the full picture:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">resid</span>(piecewise1) <span class="sc">~</span> FearPiggy, </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> feardata, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_point</span>(<span class="fu">predict</span>(piecewise1) <span class="sc">~</span> FearPiggy, </span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> feardata, <span class="at">color =</span> <span class="st">"blue"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="nonlinear-regression_files/figure-html/segmented-plot-full-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="joint-piecewise-regression" class="level3">
<h3 data-anchor-id="joint-piecewise-regression">Joint Piecewise Regression</h3>
<p>The joint piecewise regression is a more popular technique as it allows a trend to continue directly from one line to another at the knot point, like a door-hinge. Mathematically, it is two lines with different slopes but the same intercept, where one line goes to the right from the joint and one line goes left.</p>
<p>To make this model, create the indicator term, then <strong>center your predictor at the joint</strong> by subtracting the breakpoint value. This makes <code>FearPiggy</code> = 5 become 0, all values less than 5 become negative, and all values greater than 5 become positive. <strong>DO NOT add the indicator <code>XJ</code> term</strong> - doing so results in a segmented (disconnected) piecewise line instead.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>feardata<span class="sc">$</span>XJ      <span class="ot">&lt;-</span> (feardata<span class="sc">$</span>FearPiggy <span class="sc">&gt;=</span> <span class="dv">5</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>feardata<span class="sc">$</span>FearPiggyc  <span class="ot">&lt;-</span> feardata<span class="sc">$</span>FearPiggy <span class="sc">-</span> <span class="dv">5</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>feardata<span class="sc">$</span>FearPiggycXJ <span class="ot">&lt;-</span> (feardata<span class="sc">$</span>FearPiggyc <span class="sc">*</span> feardata<span class="sc">$</span>XJ)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>piecewise3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(EnjoymentPiggy <span class="sc">~</span> FearPiggyc <span class="sc">+</span> FearPiggycXJ, <span class="at">data =</span> feardata)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(piecewise3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = EnjoymentPiggy ~ FearPiggyc + FearPiggycXJ, data = feardata)

Residuals:
   Min     1Q Median     3Q    Max 
-5.846 -2.490  1.027  2.888  3.337 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    6.6962     0.7313   9.156 7.57e-15 ***
FearPiggyc     0.2067     0.2830   0.730    0.467    
FearPiggycXJ  -0.4191     0.4725  -0.887    0.377    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.124 on 99 degrees of freedom
Multiple R-squared:  0.008439,  Adjusted R-squared:  -0.01159 
F-statistic: 0.4213 on 2 and 99 DF,  p-value: 0.6574</code></pre>
</div>
</div>
<ul>
<li><code>FearPiggyc</code> (.21) is the slope <strong>before</strong> the joint</li>
<li><code>FearPiggycXJ</code> (-.42) is the <strong>difference</strong> in slopes before and after the joint</li>
</ul>
<p>To get the slope after the joint:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">0.4191</span> <span class="sc">+</span> <span class="fl">0.2067</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.2124</code></pre>
</div>
</div>
<p>To get the significance of the after-joint slope, switch the indicator:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>feardata<span class="sc">$</span>XJ2           <span class="ot">&lt;-</span> (feardata<span class="sc">$</span>FearPiggy <span class="sc">&lt;</span> <span class="dv">5</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>feardata<span class="sc">$</span>FearPiggycXJ2 <span class="ot">&lt;-</span> (feardata<span class="sc">$</span>FearPiggyc <span class="sc">*</span> feardata<span class="sc">$</span>XJ2)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>piecewise4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(EnjoymentPiggy <span class="sc">~</span> FearPiggyc <span class="sc">+</span> FearPiggycXJ2, <span class="at">data =</span> feardata)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(piecewise4)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = EnjoymentPiggy ~ FearPiggyc + FearPiggycXJ2, data = feardata)

Residuals:
   Min     1Q Median     3Q    Max 
-5.846 -2.490  1.027  2.888  3.337 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     6.6962     0.7313   9.156 7.57e-15 ***
FearPiggyc     -0.2124     0.2367  -0.897    0.372    
FearPiggycXJ2   0.4191     0.4725   0.887    0.377    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.124 on 99 degrees of freedom
Multiple R-squared:  0.008439,  Adjusted R-squared:  -0.01159 
F-statistic: 0.4213 on 2 and 99 DF,  p-value: 0.6574</code></pre>
</div>
</div>
<p>The slope of the line after the joint at 5 is not significant, as we expected. The magnitude of the interaction is the same (.42) but the sign changes to keep the arithmetic consistent.</p>
<p><strong>Interpretation example (before-joint slope):</strong></p>
<blockquote class="blockquote">
<p>For two individuals who are below a score of 5 in their fear of the piggy jump scare and differ in one unit of fear, the individual who was more afraid is expected to be about .21 point higher in their enjoyment of the piggy jump scare.</p>
</blockquote>
<p><strong>Interpretation example (interaction at joint):</strong></p>
<blockquote class="blockquote">
<p>The difference in slopes for individuals who have a fear piggy score of less than 5 and those who have a score of 5 or greater is about .41.</p>
</blockquote>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">predict</span>(piecewise3) <span class="sc">~</span> FearPiggy, <span class="at">data =</span> feardata)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="nonlinear-regression_files/figure-html/joint-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Unlike the segmented piecewise model, this model connects when <code>FearPiggy</code> equals 5! You can imagine the Y-axis splitting at <code>FearPiggy</code> = 5, with one line going left and one going right - both meeting at the same intercept at the joint.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">resid</span>(piecewise3) <span class="sc">~</span> FearPiggy, </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> feardata, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_point</span>(<span class="fu">predict</span>(piecewise3) <span class="sc">~</span> FearPiggy, </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> feardata, <span class="at">color =</span> <span class="st">"blue"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="nonlinear-regression_files/figure-html/joint-plot-full-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The piecewise segments in blue are incredibly flat - the model is a poor fit because the slopes were not significant. If you ever wanted to do more than one joint, you can add more knots, but instead of being dummy coded like <code>XJ</code> was, you need to use sequential coding (see the Multicategorical Predictors lesson).</p>
<hr>
</section>
</section>
<section id="log-transformations" class="level2">
<h2 data-anchor-id="log-transformations">4. Log Transformations</h2>
<section id="what-is-a-log-transformation" class="level3">
<h3 data-anchor-id="what-is-a-log-transformation">What Is a Log Transformation?</h3>
<p>Log transformations are probably the most universally applied method for dealing with nonlinearity. When you have a variable that is notably skewed, you can rescale it using logarithms, which reshapes the distribution by pulling in large values and spreading out smaller ones. This often makes relationships more linear, stabilizes variance, and improves model fit.</p>
<p><strong>NOTE:</strong> Whenever you see “log” in statistics, it always refers to the <strong>natural log</strong> (otherwise denoted as “ln” in other domains). The <code>log()</code> function in R gives you the natural log by default. The <code>exp()</code> function gives you the inverse. For quick reference: <code>exp(log(X)) = X</code> and <code>log(exp(X)) = X</code>.</p>
<p>A caveat: the variable must be positive. If you have negative values or zeros, you need to shift your data first.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Shift variables up by 1 to avoid log(0) = -Infinity</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>feardata<span class="sc">$</span>FearPiggyc2    <span class="ot">&lt;-</span> feardata<span class="sc">$</span>FearPiggy <span class="sc">+</span> <span class="dv">1</span> </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>feardata<span class="sc">$</span>EnjoymentPiggyc <span class="ot">&lt;-</span> feardata<span class="sc">$</span>EnjoymentPiggy <span class="sc">+</span> <span class="dv">1</span> </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="visualizing-log-transformations" class="level3">
<h3 data-anchor-id="visualizing-log-transformations">Visualizing Log Transformations</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Non-transformed model</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(EnjoymentPiggyc <span class="sc">~</span> FearPiggyc2, <span class="at">data =</span> feardata) <span class="sc">%&gt;%</span> <span class="fu">gf_lm</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="nonlinear-regression_files/figure-html/log-viz-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Log-transformed Y</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">log</span>(EnjoymentPiggyc) <span class="sc">~</span> FearPiggyc2, <span class="at">data =</span> feardata) <span class="sc">%&gt;%</span> <span class="fu">gf_lm</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="nonlinear-regression_files/figure-html/log-viz-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Log-transformed X</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(EnjoymentPiggyc <span class="sc">~</span> <span class="fu">log</span>(FearPiggyc2), <span class="at">data =</span> feardata) <span class="sc">%&gt;%</span> <span class="fu">gf_lm</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="nonlinear-regression_files/figure-html/log-viz-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Both Y and X log-transformed</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(<span class="fu">log</span>(EnjoymentPiggyc) <span class="sc">~</span> <span class="fu">log</span>(FearPiggyc2), <span class="at">data =</span> feardata) <span class="sc">%&gt;%</span> <span class="fu">gf_lm</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="nonlinear-regression_files/figure-html/log-viz-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>What you can note in the above plots is the scale of the axes. They become more condensed. Logs scale in magnitudes of distance from 0, so points further out become more compressed while points close to 0 do not get compressed as much.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(feardata<span class="sc">$</span>EnjoymentPiggyc)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="nonlinear-regression_files/figure-html/log-hist-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">log</span>(feardata<span class="sc">$</span>EnjoymentPiggyc))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="nonlinear-regression_files/figure-html/log-hist-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>You can add slight modifications to the logarithms to adjust the severity of the transformation, but you should not really play around with this unless you know what you are doing. It is bad practice to guess numbers and transform - you <strong>will</strong> get critique in reviewer feedback about this.</p>
</section>
<section id="log-transformation-interpretations" class="level3">
<h3 data-anchor-id="log-transformation-interpretations">Log Transformation Interpretations</h3>
<p><strong>Log-transformed outcome:</strong></p>
<p>When you log-transform Y, the coefficients are essentially <strong>percentage changes</strong> of the outcome.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>logmodel <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(EnjoymentPiggyc) <span class="sc">~</span> FearPiggyc2, <span class="at">data =</span> feardata)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logmodel)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(EnjoymentPiggyc) ~ FearPiggyc2, data = feardata)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.8917 -0.2142  0.2728  0.5258  0.5641 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.90872    0.19348   9.865   &lt;2e-16 ***
FearPiggyc2 -0.01702    0.02446  -0.696    0.488    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7087 on 100 degrees of freedom
Multiple R-squared:  0.00482,   Adjusted R-squared:  -0.005132 
F-statistic: 0.4843 on 1 and 100 DF,  p-value: 0.4881</code></pre>
</div>
</div>
<p><strong>Interpretation of b1:</strong> Between two individuals who differ in FearPiggy by 1 point, the more afraid person is expected to be .01 lower in log-units of EnjoymentPiggy.</p>
<p>To get the exact <strong>percent change</strong> of the outcome: <span class="math display">\[\%\Delta Y = (e^{b_1} - 1) \times 100\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.017</span>) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.685632</code></pre>
</div>
</div>
<p>For two individuals who differ in FearPiggy by 1 point, the more afraid is expected to be 1.68% lower in EnjoymentPiggy.</p>
<p><strong>Log-transformed predictor:</strong></p>
<p>When you log-transform X, you cannot simply take the exponential of the slope to back-transform, because the slope now represents the change in Y for a one-unit change in <span class="math inline">\(\log(X)\)</span>, not X itself. The effect of X depends on its current value, so there is no single back-transformed slope on the original scale.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>logmodel2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(EnjoymentPiggyc <span class="sc">~</span> <span class="fu">log</span>(FearPiggyc2), <span class="at">data =</span> feardata)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logmodel2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = EnjoymentPiggyc ~ log(FearPiggyc2), data = feardata)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.1400 -2.0878  0.9857  2.8600  3.1330 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        6.8670     1.0017   6.855 5.96e-10 ***
log(FearPiggyc2)   0.1186     0.5107   0.232    0.817    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.12 on 100 degrees of freedom
Multiple R-squared:  0.0005389, Adjusted R-squared:  -0.009456 
F-statistic: 0.05392 on 1 and 100 DF,  p-value: 0.8168</code></pre>
</div>
</div>
<p><strong>Interpretation of b1:</strong> Between two individuals who differ in <span class="math inline">\(\log(\text{FearPiggy})\)</span> by 1 unit, the individual with the higher FearPiggy is expected to be .1186 units higher in EnjoymentPiggy.</p>
<p>A 1-unit difference in <span class="math inline">\(\log(X)\)</span> corresponds to multiplying X by <span class="math inline">\(e \approx 2.72\)</span>. To express this as a percent change:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">exp</span>(<span class="fl">0.1186</span>) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.59195</code></pre>
</div>
</div>
<p>For two individuals where one has about 2.72 times higher FearPiggy than the other, the person with higher FearPiggy is expected to have about 12.6% higher EnjoymentPiggy.</p>
</section>
<section id="box-cox-transformations" class="level3">
<h3 data-anchor-id="box-cox-transformations">Box-Cox Transformations</h3>
<p><strong>Box-Cox transformations</strong> give you a data-driven way to find the optimal transformation of the outcome to better meet regression assumptions. Instead of choosing a preset transformation (like log) by guesswork, the Box-Cox method searches across a range of possible exponential transformations and identifies the one that is most optimal for improving model fit. You can do the Box-Cox transformation using <code>boxcox()</code> from the <code>MASS</code> package.</p>
<p>The transformation is controlled by a parameter <span class="math inline">\(\lambda\)</span>, where different values correspond to different transformations (<span class="math inline">\(\lambda = 1\)</span> is no change, <span class="math inline">\(\lambda = 0\)</span> approximates a log transformation, <span class="math inline">\(\lambda = 0.5\)</span> is a square root).</p>
<p>The downside is that Box-Cox transformations destroy interpretability. Once you transform your variable, the coefficients cannot be understood conceptually. For this reason, the method is not very popular since most researchers care about interpretability.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>feardata<span class="sc">$</span>FearPiggyc <span class="ot">&lt;-</span> feardata<span class="sc">$</span>FearPiggy <span class="sc">-</span> <span class="fu">mean</span>(feardata<span class="sc">$</span>FearPiggy)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>piggy_linear <span class="ot">&lt;-</span> <span class="fu">lm</span>(EnjoymentPiggyc <span class="sc">~</span> FearPiggyc, <span class="at">data =</span> feardata)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>bc <span class="ot">&lt;-</span> <span class="fu">boxcox</span>(piggy_linear, <span class="at">lambda =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="nonlinear-regression_files/figure-html/boxcox-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The plot shows the log-likelihoods of the model for every <span class="math inline">\(\lambda\)</span> checked. The range within the vertical dotted lines gives the best fits, with the center dotted line being the most optimal.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>best_lambda <span class="ot">&lt;-</span> bc<span class="sc">$</span>x[<span class="fu">which</span>(bc<span class="sc">$</span>y <span class="sc">==</span> <span class="fu">max</span>(bc<span class="sc">$</span>y))]</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>best_lambda</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.424242</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>feardata<span class="sc">$</span>EnjoymentPiggyBEST <span class="ot">&lt;-</span> feardata<span class="sc">$</span>EnjoymentPiggyc <span class="sc">^</span> best_lambda</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>boxcox_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(EnjoymentPiggyBEST <span class="sc">~</span> FearPiggyc, <span class="at">data =</span> feardata)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(boxcox_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = EnjoymentPiggyBEST ~ FearPiggyc, data = feardata)

Residuals:
    Min      1Q  Median      3Q     Max 
-16.362  -7.435   2.005   9.249   9.266 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 17.314239   0.918185  18.857   &lt;2e-16 ***
FearPiggyc  -0.007468   0.319986  -0.023    0.981    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.273 on 100 degrees of freedom
Multiple R-squared:  5.447e-06, Adjusted R-squared:  -0.009994 
F-statistic: 0.0005447 on 1 and 100 DF,  p-value: 0.9814</code></pre>
</div>
</div>
<p>So this is the most optimal transformation, which really did not do much since the model was not nonlinear and was a poor fit in general. And now the coefficient cannot be meaningfully interpreted.</p>
<hr>
</section>
</section>
<section id="well-done" class="level2">
<h2 data-anchor-id="well-done">Well Done!</h2>
<p>You have completed the Nonlinear Regression tutorial. Here is a summary of what was covered:</p>
<ul>
<li>Visualizing nonlinearity with scatterplots and residual plots</li>
<li>Polynomial models (quadratic) using squared terms and the <code>I()</code> function</li>
<li>Piecewise regression: segmented (disconnected) and joint (connected at a knot)</li>
<li>How piecewise regression relates to interaction terms in its setup and interpretation</li>
<li>Log transformations for the outcome and predictor, including percent change interpretations</li>
<li>Box-Cox transformations as a data-driven but interpretability-destroying approach</li>
</ul>


</section>

</main> <!-- /main -->
<!-- MailerLite Universal -->
<script>
    (function(w,d,e,u,f,l,n){w[f]=w[f]||function(){(w[f].q=w[f].q||[])
    .push(arguments);},l=d.createElement(e),l.async=1,l.src=u,
    n=d.getElementsByTagName(e)[0],n.parentNode.insertBefore(l,n);})
    (window,document,'script','https://assets.mailerlite.com/js/universal.js','ml');
    ml('account', '2295583');
</script>
<!-- End MailerLite Universal -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/infogothic\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>